### ISSUE TITLE
Make mutually exclusive: 'Locate near a Bike Share Station' and 'Install Bike Share Station' and revise tooltip 

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#1007]
### Overview
Make TDM Strategy mutually exclusive 'Locate near a Bike Share Station' and 'Install Bike Share Station' and revise tooltip 

### Action Items
Consolidate 'Locate near a Bike Share Station' and 'Install Bike Share Station' as drop down options under a single strategy named: '**Bike Share Station**'

Under Possible points Column for '**Bike Share Station**' revise as '2-5 pts'
with 'Locate near a Bike Share Station' receiving 2 points and 'Install Bike Share Station' receiving 5 Points 

Revise and consolidate in a single tooltip to read:

> **Locate near a Bike Share Station:** Project is located within 600 feet of an existing bike share station - [Bike Share Location Map](https://bikeshare.metro.net/stations/). LADOT shall pre-approve the selection of this TDM Strategy. 
>
> **Install Bike Share Station:** Install a publicly accessible bike share station with a minimum of 10 docks. Must meet LADOT Bike Share Siting Guidelines and be pre-approved by qualified LADOT bike share program staff.

Make sure to make the active link to Metro's Bike Share Location Map

**Comment by entrotech** [comment]
On the tooltip, I could not make the paragraph headings bolder than the paragraph text, because the current tooltip design makes the paragraph text bold.
I was able to make the link into a hyperlink, but with the current tooltip, it is not possible to click on the link, since moving your mouse off the target control to press on the link hides the tooltip.

Both of these issues should be resolved with the tooltip re-design of Issue #957
