### ISSUE TITLE
Fix padding/margins on accordions

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1059]
### Overview

There is a padding  issue on the accordions that is causing too much space at the bottom of test in the drop down. this appears to be 

### Action Items

- [x] identify which Accordions have this space 
- [x] determine source of issue (html coming from the database?)
- [x] make margins and padding consistent on all accordions.

**Comment by ExperimentsInHonesty** [comment]
@KPHowley and Ebi (don't know her github handle and her name is not in her github).

This issue needs screenshots, moving back to new issue approval until they are added.

**Comment by ExperimentsInHonesty** [comment]
@jahpe777 if you are working on this issue, please add screenshots that illustrate the problem before you start so that we can have positive confirmation of what the issue is about.  Also, please move it to in progress if you are currently working on it. And remove yourself as an assignee if you are not.

**Comment by jahpe777** [comment]
Fixed padding/margins on accordions #1059
