### ISSUE TITLE
Add icons for Accordion having external links

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#1068]
### Overview
For any text having links to external websites, we should be adding an icon that indicates that.
### Action Items

- [ ] For external links add the icon that shows its going to an external website (https://designsystem.digital.gov/components/link/ )
![image](https://user-images.githubusercontent.com/20568596/153102023-5dc4e0d1-2961-4aa1-a73b-4b794790eace.png)

- [ ] Add the image for the external links on the AIN/APN row on page 1
- [ ] Add the image for the external links on the Bike Share on page 2
- [ ] Add the image for the external links on the About Us page

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by entrotech** [comment]
Let's start by fixing up the external links on the About page, since that is front-end only. There are 6 external links on the About page that should have the "external link" appended to the body of the <a> tag.  Here is what I think we should do:
1. We have been using the icons from the react-fontawesome library, which uses V5 of the @Fortawesome icon set, and we want to use the free icons, so if you add the following imports to the About.js, it will get an icon close to the one suggested in the description:
  import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
  import { faExternalLinkAlt } from "@fortawesome/free-solid-svg-icons";
2. You can follow the example usage of an icon on the ProjectMeasures.js to see how to use and style the icon. In this case, the color should match the text of the link, and there should be a horizontal gap (maybe 0.5em or so) between the end of the text and the icon, and neither the gap nor the icon should be underlined.
3. You should also modify the anchor so that if the user clicks on it, the linked page is opened in a new browser tab, instead of replacing the TDM application in the current browser tab.

**Comment by Biuwa** [comment]
[](https://github.com/hackforla/tdm-calculator/issues/888)
