### ISSUE TITLE
Users wanted instruction on how to enter numbers

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1161]
### Overview
We need to evaluate the adding of clarification for units of measure to know if this is a big enough problem to warrant making a change to the app.

### Action Items
- [ ] Review usability testing 2 to identify how many people brought this up (out of how many interviewed)
- [ ] If less 30% check usability testing 1 for same
- [ ] Bring findings to the Stakeholder meeting and ask them for what other forms the users might be familiar with that have the number clarification

### Resources/Instructions
Notes from Research: Users wanted clear instruction to avoid using habits from other forms/tools that could result in entry errors in the TDM calculator. For example, some tools ask for numbers assuming they represent thousands.

Potential solution: Add link or CTA to general instructions for each page, or include in "help"/page instructions in top level navigation.

**Comment by Biuwa** [comment]
#975

**Comment by Jane4925** [comment]
@pmeda12 I went through the data analysis spreadsheet as well as the miro board, so far found 2 participants (P3 and P7) out of total 8 participants who have made the comments about: 1) have comma with numbers (e.g. 1,000 instead of 1000), 2) inconsistence between TDM and VMT, or 3) units of measures (e.g. if unit of 1000 sq ft, then meaning only input 1 instead 1000 on page 2 when your project is 1000 sq ft). Could you review the recordings of the other participants and see if any of them made similar comments?

**Comment by Biuwa** [comment]
- #975

**Comment by pmeda12** [comment]
Progress: Reviewed all recordings of user testing 2 and found no further mention of unit of measurment difficulties. ((1) have comma with numbers (e.g. 1,000 instead of 1000), 2) inconsistence between TDM and VMT, or 3) units of measures (e.g. if unit of measure is 1000 sq ft, then meaning only input 1 instead 1000 on page 2 when your project is 1000 sq ft). )

Blockers: No time!!

Availability: this week is difficult but next week and the weekend I should have a few hours

ETA: Not sure, depends on what other tasks are needed. It would take me a while to go through user testing 1 recordings.

**Comment by mojimoh** [comment]
Given that only 25% of Users mentioned this as an issue, this is does not rise to the level of a feature change. Decision also recorded in [Design Issue Tracker](https://docs.google.com/spreadsheets/d/1SWcf55uRkXV41uCMTp7VLelAslf6rQCGeyCYXfGzbBU/edit#gid=0)

**Comment by mojimoh** [comment]
Given that only 25% of Users mentioned this as an issue, this is does not rise to the level of a feature change. Decision also recorded in [Design Issue Tracker](https://docs.google.com/spreadsheets/d/1SWcf55uRkXV41uCMTp7VLelAslf6rQCGeyCYXfGzbBU/edit#gid=0)
