### ISSUE TITLE
Review software using test cases provided by client

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#121]
### Overview
The client has provided 8 test cases.  We are going to review the current state of our software by testing it using the test cases, and provide writeups of what is not calculating according to plan.

### Action Items
The test cases have been parsed out to the following people

- [ ] @nclairesays 
   - [x] 625 S. Barrington Avenue
   - [x] 5460 W. Fountain Avenue
- [ ] @nicholaspung 
   - [x] 22055 CLARENDON ST
   - [x] 320 N FAIRFAX AV
- [ ] @fyliu 
   - [x] 12575 W BEATRICE ST
   - [x] 12425 VICTORY BL
- [ ] @KPHowley 
   - [x] 1657 N WESTERN AV
   - [x] 1400 N CAHUENGA BL

Write up your findings in comments below and check the address off as you add in the comments.

### Resources/Instructions
[Test case spreadsheet](https://docs.google.com/spreadsheets/d/1VIvML1cKY6aNPkYjlWKDHj9jwdxARpU6/edit#gid=1355542361)
[Test case PDF](https://drive.google.com/file/d/1WL2AzDg2Gg4Qgn6fZqjC59FmurmxB20y/view) (only has 6 of the test cases on it)

**Comment by nicholaspung** [comment]
22055 CLARENDON ST

- No car sharing bonus input in TDM Strategies
- In Affordable Housing, no 8% VLI option
- When inputting Residential Land Use, no option to declare `very-low-income units`
- When inputting # of rooms, doesn't match up to test care - Closest I got was 26 <3 rooms, 309 =3 rooms, 489.5 req parking spaces, 27 target points, 23 earned points

320 N FAIRFAX AV

- Correct test case

**Comment by fyliu** [comment]
Attached screenshots of the cases

### Beatrice St - Parking # correct, TDM point requirement correct, TDM measures points correct
- Required parking display should round to nearest integer(or to the next higher one?).
### Victory Bl - Parking # incorrect, TDM point requirement incorrect, TDM measures points correct
- Required parking calculation is 24 but test case says 52.
- I propose updating the PARK_GUEST calculation rule to this logic, which is how the calculation should work from Rosemary's response to the question on how this works. It would make the required parking spaces 51, which is close enough to correct the TDM point requirement. I can't see what accounts for the 1 point discrepancy.
    
	if (<<UNITS_GUEST>> <= 30){
		return <<UNITS_GUEST>>;
	} else if (<<UNITS_GUEST>> <= 60 ) {
		return 30 + (<<UNITS_GUEST>> - 30) * 0.5;
	} else {
		return 45 + (<<UNITS_GUEST>> - 60) * 0.3;
	}
- INFO: Looks like there's an updated design of this hotel guest room calculation as well, which is not yet implemented. https://docs.google.com/spreadsheets/d/1i1yMEgWsgUKY_qCgDDtsOl5uZw-yltnp/edit#gid=40473366
	
[TDM - Beatrice.pdf](https://github.com/hackforla/tdm-calculator/files/3996357/TDM.-.Beatrice.pdf)
[TDM - Victory.pdf](https://github.com/hackforla/tdm-calculator/files/3996575/TDM.-.Victory.pdf)

**Comment by entrotech** [comment]
Thanks!

The car sharing bonus is not explicitly entered, but should show up as
points if you select the other two car sharing options, and it is not, so I
need to fix it. I think there is an issue I can re-open for it.
The 8% VLI  Option is actually one of the choices in the Affordable Housing
drop-down which is called 35% of Density, so it's implicitly there and
counted.
The Habitable rooms inputs should be 51, 134 and 150 for the <3, 3 and >3
choices.  With that, and entering the 564 spaces, they plan to build, I get
Level 3 and 25 Target points.

I'm 2 points below the 25 I should get for earned points because of the
absence of the car sharing bonus. (Note that their analysis points only add
up to 24 points because, though the total shows 25 - 25 is correct when you
add 1 point for the Residential TDM Package Bonus)

-John

**Comment by entrotech** [comment]
Great.  I think your suggestion is spot-on.  I will create an issue and fix
it.

Thanks,
John

**Comment by entrotech** [comment]
Barrington Test passes, but see issue #127 - need to come up with a plan to handle condo "exceptions".
Saved of TDM results to this folder: https://drive.google.com/drive/u/0/folders/12Fdlo6BKOoXJqp-QtHPhzY5ADnHRU_3T

**Comment by entrotech** [comment]
Fountain test case passes. PDF of result is in this folder: https://drive.google.com/drive/u/0/folders/12Fdlo6BKOoXJqp-QtHPhzY5ADnHRU_3T

**Comment by entrotech** [comment]
All test cases run and put in the above-mentioned folder. For the Cahuenga and Western test cases, there was no information on the strategies selected, so all we can do is verify the parking requirement, Project Level and Target Point calculations.

For the Cahuenga, the spreadsheet formula for calculating the number of required parking space was incorrect, the project level was entered as 2 when it should be 3, there are 7 spaces entered for Office parking (instead of Restaurant parking? Maybe Office parking is for all commercial parking?), and the spreadsheet rounded intermediate results, which IMO should not be done until the totals are calculated. If we fix these problems in the spreadsheet, then the TDM app calculation will agree.

After fixing the car sharing bonus on issue #125 and the Hotel Guest Room calculation on Issue #112 , the other test cases look good.
