### ISSUE TITLE
Research: Usability Test 3 for Tooltip Discoverability

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1219]
### Dependency
- [x] #1179  
- [x] #1223 

### Overview
We need to conduct a new user test to determine if it is clear to users that there are tooltips on page 1, as well as throughout the application so that we can know if we still need to make changes or if the changes we made solve the problem.

### Action Items
- [x] create research plan doc
- [x] Create test support materials
- [ ] add info wiki
- [x] test with users

### Resources/Instructions
- Related to #1218
- [Tooltip Discoverability User Testing Insights spreadsheet](https://docs.google.com/presentation/d/1bfF38ivqD6C_XvYoVDXlkf5nDcOdfV4KubsAiqEGuAU/edit?usp=sharing)
- [[3-18-23] Tooltip Discoverability - Presentation](https://docs.google.com/presentation/d/1frCKnFvf-q5EioQ8-8vdH1cbwpidTLf3I7jrTbeMaxU/edit#slide=id.p)
- [UI/UX Tooltip Discovery](https://docs.google.com/presentation/d/1Q1N_KHrKIXWDjbSJdqznhBJDP1IMEWOpX9X4rASbgcU/)
- https://github.com/hackforla/tdm-calculator/wiki/Tooltip-Usability-Test

**Comment by jarmitageux** [comment]
Progress: Testing completed, analysis begun
Blockers: none
Availability: meeting 2x/week and asynchronous work between
ETA: for complete report for leads review Nov 5th

**Comment by Biuwa** [comment]
@Jane4925 Is this complete?

**Comment by Noushie** [comment]
UXD team has a few propositions for dealing with this issue based on the information UXR presented us- we would love some UXR team input when possible, thanks! @Jane4925

**Comment by Biuwa** [comment]
- #975

**Comment by mojimoh** [comment]
@jarmitageux, please provide an update before wednesday's meeting
Progress:
Blockers:
Availability:
ETA:

**Comment by jarmitageux** [comment]
Progress: Presentation deck draft in progress 90% done
Blockers: Time available and lots of information to organize
Availability: 5 hrs
ETA: Draft will be ready for Sat 10am meeting for review and comment
I'm available to attend Sat meeting if desired by team.

**Comment by Biuwa** [comment]
[Tooltip Discoverability User Testing Insights spreadsheet](https://docs.google.com/presentation/d/1bfF38ivqD6C_XvYoVDXlkf5nDcOdfV4KubsAiqEGuAU/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Bonnie's notes from slide presentations
Slide numbers and notes
- 3 has too much information
- 5 say something about why we reviewed it with these technically savvy user group
  - new slide add bullets about which features we were testing
- video how to find tooltips - lets talk about it
- 11 could improve via a animated gif
- 16 should be earlier in the deck (in a summary)
- 17 walk them though the chron in date order oldest to newest (17-19) could be tighter
-  show image of icon

**Comment by jarmitageux** [comment]
Progress: Revising slide deck after receiving feedback
Blockers: None
Availability: 5 hrs
ETA: Aiming to have revisions done by end of Feb

Requesting any other feedback on the presentation and/or deck by EOD this Fri, Feb 10th

**Comment by Noushie** [comment]
[2/8 Tooltip Discoverability Presentation](https://docs.google.com/presentation/d/1QPmNTr_fb0oYGMRNNC5LYi0MDjZ1YIz3XNQheb1qs6U/edit#slide=id.p)

**Comment by mojimoh** [comment]
Moji's Comments:
1. Create an appendix and move the slides with comments to the appendix
2. Proposed Slide order for Presentation
- Executive summary
- Agenda
- Key Research questions
- Summary of Key Findings
- Recommendations
- Add in Anousha's UI/UX proposals (1 slide/proposal)
- Appendix
3. Create 1 slide with the key research questions listed.
4. Create 1 slide with all the key findings listed

**Comment by jarmitageux** [comment]
Progress: Revising slide deck after receiving feedback
Blockers: None
Availability: 5 hrs
ETA: Aiming to have revisions done by end of Feb

Requesting any other feedback on the presentation and/or deck by EOD this Fri, Feb 10th

**Comment by Noushie** [comment]
[Design System Link]( https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4041%3A12655&t=FwLhzRhcRTRdoJ99-1)

**Comment by jarmitageux** [comment]
Progress: Requested revisions implemented in presentation deck- just finalizing last slide
Blockers: Final approval by PMs and Bonnie
Availability: 5 hrs
ETA: Will be ready and available to present at March 21st stakeholder's meeting

**Comment by jarmitageux** [comment]
REMOVED: * 3 has too much information
DONE: * 5 say something about why we reviewed it with these technically savvy user group
DONE:  * new slide add bullets about which features we were testing
NARROWED TO 1 SHORTER VIDEO: * video how to find tooltips - lets talk about it
DONE: * 11 could improve via a animated gif
DONE: * 19 should be earlier in the deck (in a summary)
DONE: * 20 walk them though the chron in date order oldest to newest (17-19) could be tighter
DONE: * show image of icon (pointer finger cursor)

**Comment by ExperimentsInHonesty** [comment]
Notes about the new deck

- slide 3 you mentioned explore icons.  what are they?
- slide 7  is blurry.  Bring it back in and mind the aspect ratio when re sizing
- slide 11 mention and add text about the fact that the users are internal hack for la members and that in the past their responses have been the similar.  Not sure the third interview is necessary
- Slide 15 the second set of videos is better than the first.
- Slide 18 Please change this out for a picture of a confused man or non binary person.
- Slide 22 voice out what the differences were
- several slides: change the yellow highlighting to something more visible

### New suggestion
- 14 - Side note, do we have any designs where there is a plain chevron for each item on the right side of the words?

Also, something we never considered doing (was adding a message to the end of the word when they mouse over
Currently: hover makes it bold and underline
Proposed: Hover make it says Car Share Parking **(click to see definition)**

**Comment by ExperimentsInHonesty** [comment]
Some possible images for the slide
https://commons.wikimedia.org/wiki/File:Man_Stressed_At_Work.jpg
https://commons.wikimedia.org/wiki/File:Man_Overworked_At_Work.jpg
https://commons.wikimedia.org/wiki/File:Frustrated_man_at_a_desk_%28cropped%29.jpg
https://commons.wikimedia.org/wiki/File:Burnout_At_Work_-_Occupational_Burnout.jpg

**Comment by jarmitageux** [comment]
Thank you @ExperimentsInHonesty! Those images were super helpful. 
Could you please review slides 11 (updated video and slide text) and 29 (new slide with next steps). 

I think I made all the changes to [the deck](https://docs.google.com/presentation/d/1frCKnFvf-q5EioQ8-8vdH1cbwpidTLf3I7jrTbeMaxU/edit#slide=id.g210b3a3a613_0_209). Let me know if you see anything else that needs changing.

**Comment by Noushie** [comment]
Hello,

Truly apologise for the lateness here, I've been pretty swamped lately- I created a new slide show with the updated versions of designs + notes. I can definitely get rid of any wording or tweak it, I also mentioned the plans for some very basic user testing. 

The link can be found [here](https://docs.google.com/presentation/d/1Q1N_KHrKIXWDjbSJdqznhBJDP1IMEWOpX9X4rASbgcU/edit?usp=share_link) as well as a shortcut in the design folder of TDM calculator drive!

**Comment by ExperimentsInHonesty** [comment]
Please change the first slide to use the same format as the [template we use for presenting to stakeholders.](https://docs.google.com/presentation/d/1x7F_lQRzupKqsCpdtldayTsYvg-al8pfBK3pKMI1x_M/edit#slide=id.g1443c52839c_0_2)

**Comment by ExperimentsInHonesty** [comment]
ToolTip Discovery V1: Help Icon (Part 1 of 3)


ToolTip Discovery V1: Help Icon w/ Pop-up (Part 2 of 3): Either divide it into two different slides pop ups (the one with the video and the one with the Wording.  Or do two images side by side

ToolTip Discovery V1: Help Icon w/ Tutorial (Part 3 of 3): Is this what happens when they click the 

ToolTip Discovery V2: Hover Message:  
- The mockup didn't match what is currently on the site (both dev and prod).  I have done an alternative mock up (using a screen shot of dev and a text box.  and I put your old slide on skip, so you could see the difference.  See also screenshots here:
<details>
<summary>Mockup 1 - depreciated</summary>

![image](https://user-images.githubusercontent.com/37763229/230736103-54ea951d-318c-47eb-adcd-04066c41fb64.png)

</details>

<details>
<summary>mockup 2</summary>

![image](https://user-images.githubusercontent.com/37763229/230736136-23603930-72d1-4bdb-a4b1-212fadde3f0c.png)
</details>

- I can already tell they are going to miss the text. "click to see definition" needs to be more distinctive.  Possibly highlighted, or different color or with an icon(s) in addition to the text.   See mockups 3 & 4
   <details>
   <summary>mockup 3</summary>

![image](https://user-images.githubusercontent.com/37763229/230736285-56b71bea-9b77-41d1-b505-ee379ff7d7b8.png)
   </details>
<details>
<summary>mockup 4</summary>

![image](https://user-images.githubusercontent.com/37763229/230736391-c2d75903-8ed6-4ced-8061-0c7ded55b994.png)

</details>

<details>
<summary>mockup 5</summary>

![image](https://user-images.githubusercontent.com/37763229/230736483-af793dc9-047a-4d42-b823-c7c08635b397.png)
</details>




ToolTip Discovery V3 (TENTATIVE): Top Static Box
- Make this the first content slide
- Add to the speaker notes: "while we did try this on the strategies page in the past, we did not try placing the box on the first page.  
- Also, create another version of this mockup with the blue question mark changed to green, as it is in the side panel.  We are keeping both for the purpose of testing.

**Comment by Noushie** [comment]
**4/11 Update for [Tooltip Discoverability UI/UX Slides](https://docs.google.com/presentation/d/1Q1N_KHrKIXWDjbSJdqznhBJDP1IMEWOpX9X4rASbgcU/edit?usp=sharing) :**

- Replaced title with TDM deck cover (I named it Tooltip Discoverability (UI/UX) with the projected date of presentation - but I can change it if that's incorrect titling)

- Added question icons for mockup 5 

- Replaced all placeholders images with formal mockups 

- Added stated speaker note

- Created new green static box (I tried making the clickable terms bolded, green to match - hypothesising the colour might create an association between the presented text and terms/new contrast to the page)

**Comment by jarmitageux** [comment]
### Final report on research:
Presented at the April 4, 2023 stakeholder's meeting. The presentation deck is linked in Resources at the top of this issue page, and will be saved to the TDM Calculator Wiki in UX Research, Usability Testing #3 documentation. 

This report included findings from Round 3 testing as well as a thorough research review from the past 2 years (2021-2023) of research findings regarding the discoverability of the information (aka tooltips) that is opened by clicking on text.

Hover state (cursor change to pointer now shown):
<img width="796" alt="image" src="https://user-images.githubusercontent.com/92768513/236066883-af52357d-76f9-479d-91fb-09c12511f525.png">

Opened:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/92768513/236066739-3d82abbe-1fca-4c5b-803b-238a5f48bf05.png">

Summary of Key Findings: 
- Written instructions are not effective in helping users discover tooltips.
- Users do not find tooltips that are under text indicated by hover state changes and requiring clicking.
- When looking for information, users are more likely to seek, hover, and click icons.

See presentation deck for full report and recommendations.

**Comment by Noushie** [comment]
Update (5/27):

1. Test tooltip solution (most promising version) but do not fully push to final product 

2.  Test another version for comparable results after

**Comment by Noushie** [comment]
View in figma [here](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=9763%3A24392&mode=design&t=RlRhg7ugGmkwnPt4-1)

View usability testing results [here](https://miro.com/app/board/uXjVMM8iUww=/?share_link_id=226693440043) 

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/98d68f4c-d814-41aa-b033-c9a53fec55ba)

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/4d367fbf-6d09-42b8-b553-4b5fc7f68c27)

**Rationale for designs above:**

- Bonnie: Wanted to test w/o the clutter of multiple icons -> information icons appear on hover over terms 
- If a user clicks an input for a term w/ a definition -> question mark icon appears in the input along w/ accessible green text + underline (an expected behaviour by majority of users 14/18 or ~78%)
- Most users also clicked the input field as their first action to find a definition/more information, so this may be another way to get the attention of users 

**Large question mark** 

Verdict - it was not very effective placement (most users clicked in the top-fold of the screen and it was not recognised as a way to get help for the specific issue of not knowing a term)
- If tutorials would be added - I hypothesis that having a descriptive text button (e.g., tutorials) placed in the top right or left corner (users were typically hovering around)

**Comment by Noushie** [comment]
I think also replacing 'placeholder text' w/ actual examples might be very beneficial (as it may give users an inkling as to what things mean before a working definition is shown?)

**Comment by Jane4925** [comment]
Abby and Melissa are working the google doc version of the wiki page and plan to move it the actual wiki page when ready.

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by Parisajf** [comment]
@melissaperry09 @abbyrivard In the last steak holder prep meeting you mentioned we are still working on this, would you add the remained steps in the comment?

**Comment by Parisajf** [comment]
Issue #1492  is covering the add info to wiki

**Comment by cheesarah** [comment]
Hi,

I’m no longer on the team. Could you please remove me?

**Comment by melissaperry09** [comment]
@cheesarah This is an old issue that was closed with no one assigned to it. As we are winding down the project, we are retroactively adding former contributors so that everyone receives credit on GitHub for the work they did on the project. Please let me know if you would still like your name removed.
