### ISSUE TITLE
Greyed out text explanations

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1244]
### Overview
Users are unsure why certain strategies on pg 4 of the application are greyed out.

### Action Items
- [x] Get copy of all the strategies from LADOT
- [x] Copy strategies to spreadsheet
- [x] Add the name of the tooltip to spreadsheet (column B `tooltip title`)
- [x] Hide all strategies that have `---` in the `Non-Applicable Land Use`  Column
- [x] Copy the reduced list (only the strategies that can be unselectable) to the Google doc
- [ ] Ask John if the tooltips can be different if they are selectable vs grayed out, and how big a lift if is.
   - [ ] If John says that the lift is small, then provide guidance to the stakeholders that they can make two versions
   - [ ] if John says the lift is big or the current library does not support it, then ask them to incorporate the explanations into the current text.
- [x] Have stakeholders review the tooltips 
- [ ] Ask John for any documentation that he is using to store the strategy applicability in, it would be good to add that into the Resources section of this issue

#### Stakeholder
- [x] Determine what language to add, which will help users understand what conditions allow the strategies to be selected.

### Resources/Instructions
- [Copy of Appendix C for HfLA: Summary of TDM Strategies](https://docs.google.com/document/d/1JPBUCZJjRq_4pWqMDuh4Qr3ffkIFMbB0/edit) - Word doc provided by Stakeholder
- [Spreadsheet version of stakeholder doc with space for Tooltips](https://docs.google.com/spreadsheets/d/1AdqWXs0mbrM_SpCA0oFsl1OAlwMxFJ93Wmr508I0YnQ/edit#gid=0)
- [TDM Tooltip Edits for greyed out text](https://docs.google.com/document/d/1ctMRX48Q5PHh-5B5WtO3AoLHwNjxwmVOP3W2_ymQYi4/edit#) - document for stakeholder to add their edits to

**Comment by ExperimentsInHonesty** [comment]
@awikstrom-ladot will provide a document with the Appendix C table in it so that HfLA team can create a document for tooltip text.

**Comment by awikstrom-ladot** [comment]
Link to the Appendix C table doc: https://docs.google.com/document/d/1JPBUCZJjRq_4pWqMDuh4Qr3ffkIFMbB0/edit

**Comment by entrotech** [comment]
@ExperimentsInHonesty @SMR9220 @awikstrom-ladot

[StrategyAppllicabilityRules.csv](https://github.com/hackforla/tdm-calculator/files/9791073/StrategyAppllicabilityRules.csv)

The displayFunctionBody column of this csv file gives a Javascript expression that is evaluated to determine if the strategy is applicable (i.e. not greyed out in tht UI).  The tokens in double angle brackets represent the value of other rules. In most cases, whether a strategy is applicable is a function of the project land uses, though in several cases, the function implements strategies that are mutually exclusive with other rules. Strategies that are always applicable have a displayFunctionBody of 'return true'.

The land use applicability should agree with the document @awikstrom-ladot referenced above, but the custom applicability rules are documented piecemeal on individual issues and I don't think LADOT/City Planning has a document describing these situations. Some of the tooltips (e.g. Mandatory Trip Reduction) already include language in the tooltip describing how various strategies are mutually exclusive.

To make this issue actionable for developers, we would need to specify how the rules should be worded in the tooltips.

**Comment by entrotech** [comment]
It is possible to have different tooltips depending on whether a strategy is applicable or not, but IMO, it would be more helpful if the same tooltip applied in either case and the applicability was added to the description of the strategy in the tooltip.

**Comment by Biuwa** [comment]
During today's meeting Xander agreed that it will be okay if add atext to the top tooltip that explaining why the strategy is grey out

**Comment by Biuwa** [comment]
[TDM Tooltip Edits for Greyed out text](https://docs.google.com/document/d/1ctMRX48Q5PHh-5B5WtO3AoLHwNjxwmVOP3W2_ymQYi4/edit) has been updated with the appropriate text that explains why the strategy is greyed out.

**Comment by Biuwa** [comment]
Emily also left this comment :

'Unexpected issue I encountered when testing the greyed out strategies with different project uses:
If I input a project with multiple uses (say 60 apartments, 50,000 sf office) and I start selecting TDM strategies (e.g. one of the affordable housing strategies), and then I go back to page 2 and delete the apartments from my project, we run into a problem. Now on page 4, Affordable Housing is greyed out (because my project doesn't have housing), but the strategy is still selected, I'm getting points for it, and I can't edit it because it's greyed out.

Please think about possible solutions for this issue. Two I can think of are (1) forcibly removing any strategies that are no longer valid when a project's uses change, or (2) putting up a big error message that flags for someone that they should reset their project or at least the page if this scenario occurs.

Thanks!'

**Comment by Biuwa** [comment]
Issue #1265 addresses the concerns in Emily's comments above

**Comment by ExperimentsInHonesty** [comment]
All the new changes to the tooltips are in [this document](https://docs.google.com/document/d/1ctMRX48Q5PHh-5B5WtO3AoLHwNjxwmVOP3W2_ymQYi4/edit), go ahead and make the changes in the db

For reading the changes in the document Stakeholder Emily pointed out that if content is removed it's got a strike-through, otherwise it's an addition.

**Comment by ExperimentsInHonesty** [comment]
### Notes from 2023-01-10 meeting with stakeholder
- John will review and if any additional questions arise he will email Emily.  Once the changes are all made the document will close with a notice no it that the changes are complete.
