### ISSUE TITLE
Introduction to the LADOT Setting data standards team 

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1263]
### Overview
During the stakeholder meeting on 10-18-22, Emily confirmed introducing the LADOT (PDF) setting data standards submission team to Bonnie. 

### Action Items

- [ ] Remind Emily in every stakeholders' meeting till it is provided.
- [ ] Create the Team's Milestone/Road Map

### Resources/Instructions
https://docs.google.com/presentation/d/1l8qEhuv759MAvrXB1am_4jsUuzLyfRA7NDRSPuwB0FY/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
Sent email to stakeholder after meeting 2022-11-15 
LADOT Setting data standards team
https://github.com/hackforla/tdm-calculator/issues/1263
We need to know the Data Type that the information from the calculator should be exported into so that it can be used by applicable departments: 

Follow Up Item: Ask who is in charge of Specifying Data Types: (e.g., Json, XML, CSV) and Schema.  John and Bonnie from Hack for LA are available to review the standards established and meet with appropriate counterparts.  LADOT and LACP TDM have it on their agenda tomorrow 2022-11-16 LADOT Setting data standards team.

**Comment by ExperimentsInHonesty** [comment]
### Notes from 2023-01-10 meeting with stakeholder
- Alexander will followup up with Zack Bouz to move the conversation forward. preferably city wide standards vs just ladot

**Comment by Biuwa** [comment]
**2023-02-07 STAKEHOLDER MEETING NOTES:** 
There has been no progress in finding the contact for the data standards team.

Bonnie - '_we had a conversation with David and his boss about 8 months ago about this_'.
Xander will find out who that boss was and who we can have a conversation with in regards to offloading the app

**Comment by Biuwa** [comment]
No longer required, we will create a CSV with true value for every strategy checked.
