### ISSUE TITLE
Strategies remain selected after changes to project specifications make them inapplicable.

### ISSUE THREAD

**Issue by SMR9220** [hackforla/tdm-calculator#1265]
### Overview
We need to define what the process for unchecking strategies if the user makes changes to their project that make the project ineligible to use the strategy, so that users understand what is happening.

### Details about replicating error - note from Stakeholder
Upon reviewing the TDM FAQ Draft google doc (not linked because it is irrelevant
to this issue), Emily left this comment:

"Unexpected issue I encountered when testing the greyed out strategies with different project uses:
If I input a project with multiple uses (say 60 apartments, 50,000 sf office) and I start selecting TDM strategies (e.g. one of the affordable housing strategies), and then I go back to page 2 and delete the apartments from my project, we run into a problem. Now on page 4, Affordable Housing is greyed out (because my project doesn't have housing), but the strategy is still selected, I'm getting points for it, and I can't edit it because it's greyed out.

Please think about possible solutions for this issue. Two I can think of are (1) forcibly removing any strategies that are no longer valid when a project's uses change, or (2) putting up a big error message that flags for someone that they should reset their project or at least the page if this scenario occurs.

Thanks!"

### Action Items
- [x] Discuss with development what the options are for letting the user know what is about to happen.

### Resources/Instructions
https://tdm.ladot.lacity.org/login

**Comment by ExperimentsInHonesty** [comment]
Discussion:
Emily has suggested two options.  I believe there is a third and want @entrotech to let us know feasibility of the following:

Is it possible for the app to pop up a warning message when a user tries to change their project details on P2 (Determine Project Level), that would warn them that if they proceed it will change their project level and X (where is X is the name of the strategies) strategies they have selected will no longer be available.

**Comment by ExperimentsInHonesty** [comment]
Compromise solution (lower lift):   they have selected level (p2) and strategies (p4).  Then they go back to level (p2) and try to change it, it will warn them that strategies they have chosen are subject to being deselected if they are not applicable to the revised project specifications.

**Comment by ExperimentsInHonesty** [comment]
Emily and Alexander want the following wording for the warning message: 

> If you change your project specifications, any TDM Strategies that you have selected will be removed if they are no longer applicable.

**Comment by ExperimentsInHonesty** [comment]
The design team will create an issue and put a comment on this issue with guidance on warning boxes design.

**Comment by entrotech** [comment]
@Biuwa @bonniewolfe   I created two development issues,  #1284 can be implemented immediately, and will instantly de-select inapplicable strategies as soon as they become inapplicable due to changes on pages 2 and 3.
Issue #1285 is to notify the user.  Bonnie indicated when to notify the user , which I interpret to mean when the user clicks into or places focus on an editable control on page 2 or page 3, The stakeholders gave us the wording to use, but we still need a design for what the notification will look like (modal dialog, toast, drawer, etc.) and maybe a wireframe.

**Comment by entrotech** [comment]
@Biuwa @bonniewolfe   @awikstrom-ladot  I implemented development issue #1284, so that the calculation automatically de-selects any inapplicable strategies as soon as an input is modified that makes a strategy inapplicable.   This is currently available on the [dev environment](https://tdmdev.azurewebsites.net)

**Note that if you make subsequent edits that make a de-selected strategy applicable again, it is not automatically re-selected, since we do not keep a history of what was previously selected.**
