### ISSUE TITLE
Update links on govcalc.org 

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1298]
### Overview
It was observed during the meeting held on 2023-01-10 that some of the links on the govcalc.org website are outdated and need to be reviewed

### Action Items
- [x] provide an up-to-date review of the website to ascertain which links should be removed or replaced.
- [ ] update the website with currents links 

### Resources/Instructions
https://govcalc.org/

**Comment by mojimoh** [comment]
@ExperimentsInHonesty 
Reviewed all links against available source. The only links requiring updates are the information fact sheets. However, these links need to be updated on the about page of the TDM site as well.  Links provided below. 

Proposed actions
- reopen issue #325 and add this to the list of items and assign to ui/ux design lead

[Fact Sheet - English (June 2022)](https://planning.lacity.org/odocument/ee9c120e-5181-4c0d-8bc0-c0cb07a765b9/TDM_Fact_Sheet_updated_6.2022.pdf)
[Hoja Informativa - Español (Junio 2022)](https://planning.lacity.org/odocument/7b1b8da2-5268-4bba-b3c1-7f092b6649c6/TDM_Fact_Sheet_SPANISH_updated_6.2022.pdff)

[Source](https://planning.lacity.org/plans-policies/initiatives-policies/mobility)

**Comment by ExperimentsInHonesty** [comment]
```
 <a href="https://planning.lacity.org/odocument/ee9c120e-5181-4c0d-8bc0-c0cb07a765b9/TDM_Fact_Sheet_updated_6.2022.pdf">Fact Sheet - English (June 2022)</a> |
                        <a href="https://planning.lacity.org/odocument/7b1b8da2-5268-4bba-b3c1-7f092b6649c6/TDM_Fact_Sheet_SPANISH_updated_6.2022.pdf">Hoja Informativa - Español (Junio 2022)</a>
```

**Comment by ExperimentsInHonesty** [comment]
Create an issue to update wiki with details about how to edit the govcalc.org page and link the issue here

Things to include
- URL of repo where index.html lives (what appears on govcalc.org)
  - how to edit this
    - if you are on the tdm write team in github it already has permissions to edit this repo
- accounts that you have to log into in order to see/make the pages for the ux researcher (tdm-ux@hackforla.org) using during testing
- any cleanup that needs to be done 
  - moving files from one email account to another if they are not owned by the project (e.g., vivek owns some)
