### ISSUE TITLE
100% Affordable Housing Strategy Edge case 

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1354]
### Overview
We need to address the 100% Affordable Housing strategy edge case of less than 50 units.

### Action Items
- [x] Design a new pop-up message ('100% affordable housing of less than 50 units are exempt from the TDM Ordinance. Did you intend to change to 100% Affordable Housing? YES  NO') on page 4  that will ask users if they intend to change this project from 100% Affordable housing after choosing the 100% affordable housing option from the drop-down
- [x] If the answer is yes, the calculator will take them back to page 3, where they will see the 'the project is not ...' pop-up message
- [x] If the answer is no, they will stay on page 4, and the drop-down option will remain at it's previous value.

**Comment by Biuwa** [comment]
@Noushie please remember to attach a picture of the mockups here. thanks

**Comment by Noushie** [comment]
**Link to figma:** https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=8937%3A21549&t=kHyqTSmSNA5jzz6d-1




### Mockup V1: Orange exclamation icon (supported by design team)

- Orange exclamation is supposed to denote important information or verify with users about something in relation to their project (as decided on pages 3 and 5) -> design team thought that there could be two types of pop-ups as a result

![image](https://user-images.githubusercontent.com/115515867/232663015-789a8838-7c4a-4a19-b68a-407b4276db9e.png)
 
### Mockup V2: Red warning icon 

- This is more with other pop-ups we've been updating,  but since there's no destructive actions in this particular case, design team thinks this may not be the most appropriate option

### Context from our design system

![image](https://user-images.githubusercontent.com/115515867/232664003-29ba44b7-0d4d-4808-b59c-bf282fd094c1.png)

**Comment by entrotech** [comment]
- Created development Issue #1368 
and closed this Issue.
