### ISSUE TITLE
Allow users to make/retract a link that shares a snapshot of their project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#1369]
### Dependency
- This issue is part of the grouped redesign issues for my project page https://github.com/hackforla/tdm-calculator/issues/1386

### Overview
We need users to have a way to share project snapshots with other people

### Details
- users/project authors would be able to create a link which when viewed allows other users to see a snapshot of their project, which they can then save locally.
- once a snapshot is created, the author/owner cannot edit the project.  But they can make a copy of the project and iterate that copy.
- project authors would be able to retract the link, so that if anyone clicks on it, after retraction it will deliver an error message (e.g., this link is no longer active, see original provider for new link).
- ~author can create a note for themselves when they create the link?~ (Make another/ new issue for post-MVP Evaluation)

### Action Items
- [ ] Ask ebi or bonnie for any clarifications
- [ ] mock up changes to my projects page

### Resources/Instructions
- [Video Guide](https://drive.google.com/file/d/1K2RpMlsr6GkoqtYGj5dmoIcxYUNilY-E/view?usp=drive_link)
- [Audio Guide](https://drive.google.com/file/d/1wvjgR-j5zZltMKxA64FUy2tuDcyOswlo/view?usp=drive_link)

**Comment by IMHieuVo** [comment]
@Biuwa 
This flow is a bit tricky since the share function has to do (2) things. 1 - Duplicate the project and the lock original project. 2 - It has to have a sharing option that can be toggled on/off as well as a place for the user to input notes. Both of these steps require modifying the design system so I would like to talk to the group/design team this Wednesday to further refine this problem.

Here is my thought process so far:

A-01
The current view with the share button.
![HV - Snap Shot A-01 (Current view + Share button)](https://github.com/hackforla/tdm-calculator/assets/117132709/8844e5e8-17e5-4cc9-9d01-6de8c37c78f2)

A-02
After the user clicks on the share button, the dialogue box prompts the user to duplicate the project first.
![HV - Snap Shot A-02 (Duplicate Option)](https://github.com/hackforla/tdm-calculator/assets/117132709/96adf8dc-48d4-4111-84d9-37c00cc51660)

A-03
If the user clicks proceed, the product is duplicated in the background and an additional dialogue box pops up.
![HV - Snap Shot A-03 (Shared option with check)](https://github.com/hackforla/tdm-calculator/assets/117132709/c03a22f5-6c8f-47ec-ad30-382b39a92678)

A-04
If the user unchecks “Anyone with the link can view”, the link will block access to everyone with the link. 
![HV - Snap Shot A-04 (Shared option  uncheck)](https://github.com/hackforla/tdm-calculator/assets/117132709/9c5eb837-5819-4530-9cbc-0a50ce61fe62)

A-05
The original project is now uneditable and the share button is indicated in red. If the user clicks the red share button, the dialogue box with the URL Link will pop back up.
![HV - Snap Shot A-05 (Un-editable project in red)](https://github.com/hackforla/tdm-calculator/assets/117132709/35fad180-8975-4271-904c-9d65b41819a8)

**Comment by ExperimentsInHonesty** [comment]
I removed the dependency label from this issue because it does not have one listed at the top.  This issue is currently in the icebox but there is a person assigned to it.  Please either add a dependency to the top and re-add the dependency label, or move to the appropriate column.

**Comment by IMHieuVo** [comment]
I would like to show some progress on this project. Since this feature is dependent on the main My Project issue/ticket, it is subject to change.

_Note that I'm still in the middle of traveling so I will be slow to update/respond_.

Figma Link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=9997%3A27251&mode=design&t=XEaM25kkepeBqfrK-1

**Snap Shot C - 03 Menu**:
1. User clicks on “share a snapshot” icon
2. System automatically creates a duplicate copy with a date stamp in the background.
3. A dialogue box (similar to google drive sharing features) will prompt the user to add people or groups for access.
4. Access can be removed by hovering over Name & Email and an X icon will appear.
![Snap Shot C - 03 (Menu)](https://github.com/hackforla/tdm-calculator/assets/117132709/a101484c-4b39-4dbb-9fa0-0695c26fb9c7)


**Snap Shot C - 04 with Link**
1. Alternatively, the dialogue box could also include a URL Link that is Shareable. 
2. Note that the Link is not public, users would still need an email to access the file. 
![Snap Shot C - 04 (with Link)](https://github.com/hackforla/tdm-calculator/assets/117132709/f2bbb744-faa1-436f-90e0-df828ed5bd3b)


**Snap Shot C -  05 (Snapshot Copy)**
1. Once the dialogue box is closed, the user can see that a new snapshot was created. 
2. The details on how to show/differentiate this is still being worked out. Currently, it is the original file name with the “Snapshot” label and a date stamp. We’re looking into how to badge this as well.
![Snap Shot C - 05 (Snapshot Copy)](https://github.com/hackforla/tdm-calculator/assets/117132709/dd05d47f-56df-4c9b-8a89-939e6b3334b7)

**Comment by Parisajf** [comment]
Dev issue created #1700 by John
