### ISSUE TITLE
Design Mock ups for my project page

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1386]
### Dependency 
- [x] #1591 
- [x] #1579 
- [x] #1578 
- [x] #1580 
- [x] #1369 
- [x] #1371 
- [x] #1383 
- [x] #1384 
- [x] #1385 
- [x] #1388

### Overview
This issue will track the mocks up and designs changes to my project page.

### Resources/Instructions
- [ Options availability Chart ](https://docs.google.com/spreadsheets/d/1BTwm1VCEiQ8H7HsbFCKSom2tbXNoOzwEnBUcXLsPfu8/edit?usp=sharing)
- Meeting notes and recommendations are detailed in #1357 
- [Delete/Hide feature Video Guide](https://drive.google.com/drive/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)
- [Filter feature Guide](https://drive.google.com/drive/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)
- [Snapshot filter Guide](https://drive.google.com/drive/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)
-  [DROs Map](https://lahub.maps.arcgis.com/apps/instant/nearby/index.html?appid=3f1ffa8b2949449e9038ee54aede3458)

**Comment by Biuwa** [comment]
Order of Priority:
1. Create Snapshot
2. Share snapshot
3. Navigation to the snapshot page from my projects page
4. The appearance of the snapshot vs the project on my projects page
5. Filter
6. Delete/hide

**Comment by ExperimentsInHonesty** [comment]
0.57 having the grayed out snapshot icon with the tooltip is a great idea.

1:30 I understand the hesitation, the google series was cited.  I will give an example where the hide being on a separate page is a totally PTA.  I hide almost every drive all the time.  But sometimes, I want to find the shared drive for a specific project.  I don't know if I have hidden it or not, and the fact that there is not one place where I can see them all, is a PTA that has frustrated me at least 20 times in the past year.  Most of the examples that you are siting are really for a small number of results.  There needs to be a way to manage a large set of results that's the most flexible.  I can give another example of a function that GitHub has made for their discussion tab that is equally frustrating.

3:44 The new search/date design seems like a good solution.  TBD if users are clear enough how to use it.

the wording of "send a snapshot" is possibly going to be confusing.  Because it also freezes that version.  So I look forward to seeing the screens that follow if you click on the snapshot link

**Comment by Biuwa** [comment]
**2023-08-08 STAKEHOLDERS" MEETING FEEDBACK:**

<img width="725" alt="Screenshot 2023-08-09 at 12 03 31 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/bc2375d6-225f-42d7-a35d-7dcfb55aecd4">

- [ ] Change `Download` to `Download PDF`
- [ ] Change `Print a Copy` to `Print Summary` 

This change should also be done on every page where the same words appear

-----------------------------------------------------

<img width="719" alt="Screenshot 2023-08-09 at 12 12 30 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/54a1b54e-332e-4f3d-9cdf-03dcb5c84dd9">

- [ ] Change `Entered by` to `Created on`
- [ ] Change `Modified by` to `Last Modified`
- [ ] On the Admin screen or view, change `Entered by` to `Created by`

-----------------------------------------------------

- [ ] A snapshot project should not disappear automatically from the user flow.

**Bonnie:**  '_We will figure out what to do about it, it should change to this automatically (page 4 on the 'user creates snapshots' user flow) if you have done that (created a snapshot of a project), and then you can hide it if you want to, it should not hide it automatically'_
------------------------------------------------------
<img width="720" alt="Screenshot 2023-08-09 at 12 41 51 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/efb306ef-4d43-4011-84e4-9ae0e75bf5c0">

- [ ] Move 'Hidden' to the bottom of the status options
-----------------------------------------------------------
<img width="723" alt="Screenshot 2023-08-09 at 12 50 45 AM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/402de290-f5aa-4253-b5a7-7173dea02429">

- [ ] Make the name of the project the snapshot link instead of the word 'snapshot' as it currently shows.

Both Emily and Xander preferred Option 1 which has the titling for each text box

--------------------------------------------

**Comment by Noushie** [comment]
Hi Ebi, thanks- made the following corrections. Will be waiting for the recordings/further clarifications, already have some ideas to combat some of misunderstandings/issues shown here.

**Comment by Biuwa** [comment]
@Noushie I uploaded the[ Voice recordings](https://drive.google.com/file/d/15I5873phPOWJLyH4ugoyRZBJvph8UVUa/view?usp=drive_link), please ignore the background noise

**Comment by Noushie** [comment]
Thanks Ebi- so I completely understand the hidden projects issue, I do think it would greatly benefit users to utilise icons for 'hidden' status, however, I'm a little concerned about space. I know we also need the submission column as well- I'm wondering if we can modify the current categories to improve spacing for this to work?

**Comment by Noushie** [comment]
[8/8 or 1st Version of Figma Files](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=10633%3A25503&mode=design&t=wJL14Y4dpz6pkdeA-1)

- Adheres strictly to the provided screenshots and checklist

[8/20 or Latest Version Figma Files](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=10633%3A25504&mode=design&t=wJL14Y4dpz6pkdeA-1)

- Adheres to checklist/screenshots and voice recordings

[Prototype Handoff to UXR](https://app.maze.co/join?code=2957c3d645dc07f17849fbeb447008719c5963196287)

**All files are side-by-side and colour coordinated for easier readability.**

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/ffe51f89-faaf-4fd6-8ab2-7ea55058c594)

I can make any necessary edits or fixes. Joyce will also be the attending 8/31 and 9/5 meetings, to address any issues as well.

**Comment by Noushie** [comment]
[8/28 or the third iteration of 'My Projects'](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=10665%3A10120&mode=design&t=dCX04vaaBu5spiLU-1) addresses the following:

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/ba83643f-490b-42f6-b689-d3b1c5906adb)

Question(s):

- Can the table headers be adjusted, as shown here (i.e., 'Deleted On' in place of 'Last Modified' alongside the warning banner):

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/e70e2d80-a38c-41f6-b74d-5921e2f4bf96)

- Are we able to get user insights to get a better gauge on 'my projects' current usability?

**Comment by Noushie** [comment]
I had a concern about the following edit:

**Below shows 'snapshot conversion box' changes that was mentioned in the last stakeholder meeting.**

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/a5ecbf6f-2334-463f-9922-de98297b0d26)

**What it was before:** 

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/a4633f65-81ff-46a6-b431-037baca50d21)


Firstly - this doesn't follow best practices for modals, users should be able to read what their action entails before they select one.

I'm also concerned about **visual consistency, as we had confirmed as a team two styles of modals (referenced from the new design system):**

![image](https://github.com/hackforla/tdm-calculator/assets/115515867/97c891b2-7279-42ff-b389-b3418e6b8d61)

If placing the warning icon back in-line with the text, I would also push that we standardise this across the site, otherwise the UI will begin to look disjointed again.

**Comment by Noushie** [comment]
Newest version of the 'My Projects' pages are found [here](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=10910%3A30189&mode=design&t=tlbTYPqccgWiMSlr-1)

**Comment by Parisajf** [comment]
[10/03 or the third iteration of 'My Projects'] addresses the following:

![Screen Shot 2023-10-04 at 2 37 00 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/57df72f0-1a49-4702-9c31-ed4959a17ce5)

**Comment by Noushie** [comment]
@Parisajf -

I can also discuss this with y'all on Wednesday - but I'm assuming the tooltip specifications are for the following:

- Active Projects: If both hidden and visible are displayed together - hidden option is disabled on mass actions
- All Projects: both hidden/deleted options are disabled (if the user has hidden and/or deleted projects) on mass actions

Does that mean the shared actions for All projects (deleted/hidden/etc.) are:

1. Download summary
2. Print summary
3. Export as csv. 

If that's the case, then the Deleted Projects should have these actions as well (as of right now, deleted projects are only recoverable).

**Comment by Parisajf** [comment]
@Noushie New updates after the call :

- The whole three dot menu could be removed since it's adding and extra layer 

- The print and Hide options will be added to the top (next to the recycle bin ) with just an icon of eye and printer

For the case they have wrong selections the tool tip is shown on grayed item while hovering on it 
 Make sure 
- In the tooltip change the word "disabled" to hidden 
- Have the same gray saturation for the tooltip and the grayed out option
Export as CSV already exists (with a download icon) so no need to bring the CSV icon to the top
![Screen Shot 2023-10-12 at 5 34 45 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/a6c0e5de-5404-4e25-8c1b-c55e8244f7ba)


We also need to add a DRO to the filters , suggestion is:
- Under status we need submitted option too. 
- Move the Visibility to the white space next to the project type
- Use the new space for DOR with two options : Assigned, Not Assigned
_Still do your research for the best design_ 

![Screen Shot 2023-10-12 at 6 03 58 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/9fb01373-bb17-4891-a0f3-8d5eb9666d1c)

Not a priority at this point
- We also need to add a new column to the page called DRO  with the option to sort (a small arrow)
- We need to be creative to make room for the new column a suggestion is to change "Alternative No." to "Alt #"

**Comment by Noushie** [comment]
Hi @Parisajf and @Biuwa 

So the gridlines are not left by designers- that is a weird thing that Figma does out of our control (that has been an issue for awhile and none of us can figure why that happens since we almost never have our grids on). 

Here's the shortcut to remove that: MacOS: Control G. Windows: Ctrl Shift 4.

**Shortcut Icons:**

To be sure, is this what was being proposed:

- All icons are now displayed at the top (if this is the case, then for best practice/consistency, all selection types should have all icons displayed like this)

- Users are only allowed to mass delete or hide (if applicable) - all other actions must be done individually?

<img width="539" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/d4088614-7964-430b-a39e-6251916a7a7d">

<img width="551" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/0a9aa71e-195b-4ca1-bdcb-ff33cae5a75c">

**Filter Adjustment:**

The space is getting quite limited on the filter modal - so I'm suggesting we do the following formatting change:

- Have the top filters as dropdown selection (it will display the default option then provide the rest of the other options when clicked)

- DRO will be disabled until applicable- the default being assigned?

- Add submitted date, with the other date pickers

- Have a scroll bar in-order to allow users to view all options (to combat what feels to be relatively tight/cramped)

<img width="441" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/47a993c3-dbb3-4353-93c5-d8221bd06ee0">

Please let me know asap if this works - **I did not adjust ALL wireframes to reflect this as I am waiting for feedback.**

**Comment by Biuwa** [comment]
@Anuosha, Thanks for the feedback, this seems to capture all of the changes and for the filter, I think it might be best to show stakeholders both options and then get back to your team with their selection.

**Comment by Parisajf** [comment]
@Noushie The tool tip for hidden and deleted options would be different:

For delete: "Your selection includes deleted items"

For hidden "Your selection includes hidden items"

instead of  "Your selection includes deleted/hidden items"

**Comment by Biuwa** [comment]
Adding this here for reference: 

https://github.com/hackforla/tdm-calculator/issues/1440#issuecomment-1747875967

**Comment by Noushie** [comment]
@Biuwa @Parisajf 



### Questions of 11/2 Meeting:

**1. What is the confirmed distinction between 'Print Summary' and 'Download PDF'**

- Does 'Download PDF' need to become 'Download as .csv,' if there's no difference?

- Do we need to bring back the option to 'Export as .csv'?

<img width="509" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/20746d25-a29c-47ef-8a49-4550066e0964">


**2. Are these 'Active Project' tooltip selection variations correct?**


Single Selection Active Projects: 

- All options are only enabled here, correct?

<img width="773" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/a3415470-fc49-426e-9847-bf6a8cfeb8a0">





Multiple Selection Active Projects:

- Same status + different visibility

<img width="440" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/f753b2cb-cf47-4ef7-b453-8d317d698363">

<img width="958" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/2e045954-f3a4-497d-8526-5d831098d686">

<img width="542" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/8e1147a3-a36f-49b9-9c8f-ffd6e360896f">




- What about different statuses? What are the options for multi-selection/single selection?

<img width="575" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/a1093c9d-67c3-4931-abac-29adce806c8d">


- What about the sharing option? 

<img width="583" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/2f4d743e-7dc0-4f2b-bd82-0e566da3e45f">





**3. Are these 'All Project' tooltip selections variations correct? Note: Possible word change in 'Your selection includes -- items" -> item(s)?**

- Multi-selection:

<img width="812" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/f31f5a7d-ceff-43ce-a0a4-b6e23201c299">

- Single-selection (deleted):

- What about recovery option? Is that just not included in selection mode?

<img width="730" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/53e6906b-dd5b-4fe9-ac00-5b6a4370de6f">

- Single-selection (visible + draft or snapshot):

<img width="617" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/ebaee6b4-7fb3-44f5-a7e5-a03359f7d112">

- Single-selection (hidden + draft or snapshot)

<img width="558" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/115515867/b10d9769-9230-4650-bae0-213834e62319">

**Comment by Parisajf** [comment]
@Noushie I created a chart; it's actually six different scenarios. @bonniewolfe please check the [chart ](https://docs.google.com/spreadsheets/d/1BTwm1VCEiQ8H7HsbFCKSom2tbXNoOzwEnBUcXLsPfu8/edit#gid=0)and let me know if it needs any change

**Comment by Biuwa** [comment]
**2023-01-09 STAKEHOLDERS' MEETING NOTES:**

**For the dev Team:**
- [ ] Users should be allowed to search by all text (from every column) and then allow the search to be narrowed down.
- [ ] Move the slide-in filter to the right so it's near the filter button,
- [ ] Current search by date format is in MM/DD/YYYY and needs to be changed to ISO YYYY-MM-DD and should be implemented to search as it is not currently functioning
- [ ] The N/A columns should be removed from the CSV 

**For the design team:**
- [ ] Move the Project name, Address, and alternative no below the created on, modified on the filter slide-in in with the header search specific fields

**Comment by Biuwa** [comment]
**Please provide an update:**

1. **Progress**_(What is the current status of your project? What have you completed, and what is left to do)_:
2. **Blockers**_(Difficulties or errors encountered)_:
3. **Availability**_(How much time will you have this week to work on this issue)_:
4. **ETA**_(When do you expect this issue to be completed)_:
5. **Pictures** _(if necessary)(Add any pictures that will help illustrate what you are working on)_:

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/tdm-calculator/assets/37763229/baefab86-6d69-49d1-a2b4-7ff8604f8416)

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/25098653-dea8-4d9f-883e-20faf735ecc8)

**Comment by Biuwa** [comment]
@limjoyce 

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by Parisajf** [comment]
- Remaining item from this issue moved to https://github.com/hackforla/tdm-calculator/issues/1683
