### ISSUE TITLE
Design: Create a tooltip for editing or adding links on the Admin FAQ Pages

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1479]
### Overview
we need to create a tooltip that instructs the admin on how to add or edit links in the FAQ admin page

### Action Items

- [ ] Add a tooltip (For Internal: add page; For External: add https://) while in edit mode that instructs admin on how to enter or edit links

 

### Resources/Instructions
- https://tdm-dev.azurewebsites.net/faqs
- #1305

**Comment by jamiedesignedit** [comment]
Hi team,

I do not have the login to see the admin view when editing an FAQ, so I just created a rough mockup of what I think it basically looks like.  We have a few options here, but I wanted to propose the ideas early on because I'm not sure what is technically feasible.

**Option 1:** Paste external URL's / Use the dropdown for internal pages.  My question with this is- how many possible internal pages do we have?  Is the dropdown going to be very long?  Is it possible to make this?  I think this is a good option because otherwise the admin are going to have a hard time typing in the page names.

<img width="1023" alt="Screenshot 2023-10-27 at 1 24 34 PM" src="https://github.com/hackforla/tdm-calculator/assets/114036754/05e2291c-c4be-40b0-a9e1-6b8ca5946dc8">



**Option 2:**  Paste an external URL / Type an internal page name and it will autofill as you type

<img width="504" alt="Screenshot 2023-10-27 at 1 24 40 PM" src="https://github.com/hackforla/tdm-calculator/assets/114036754/e8e2e2a4-c21c-4d99-b20b-9172445f4dea">



**Option 3:** Have two separate icons, one for external URL linking and one for internal page linking

<img width="510" alt="Screenshot 2023-10-27 at 1 24 51 PM" src="https://github.com/hackforla/tdm-calculator/assets/114036754/86ea0a48-3704-4407-b0b6-2e6d90f405e2">


**Option 4:**  Paste the full page url, regardless of if it is an internal or external page.  Keep the procedure the same for both.

Thanks

**Comment by Biuwa** [comment]
The dev team will research the capability of the Quill library before we can proceed with this

**Comment by Parisajf** [comment]
We will move forward with option 1 if it is not feasible with option 2 after we figure out the capabilities of the Quill Library. Also, @Noushie if we want to have the "OR" in the middle of two options, in the current design, it looks like it's closer to the bottom option.

**Comment by Biuwa** [comment]
> We will move forward with option 1 if it is not feasible with option 2 after we figure out the capabilities of the Quill Library. Also, @Noushie if we want to have the "OR" in the middle of two options, in the current design, it looks like it's closer to the bottom option.

@jamiedesignedit please review above comment

**Comment by Biuwa** [comment]
**2023-11-14 STAKEHOLDER FEEDBACK:**
Option 1 with the dropdown for internal pages was selected by the stakeholders
