### ISSUE TITLE
Fix formatting of the Summary Print Out

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1568]
### Overview
we need to correct the summary printout page to the approved mock-up design.

### Action Items
- [x] Correct the current summary page to the design approved by the stakeholders:
- [ ] Section headings should have light grey background
- [x] Project Name is aligned next to the Project Name section caption, instead of on the right.
- [x] Below Project Level line, the Project Specifications should have a minor heading with light grey background for each section of the project specification that is used (e.g., Residential) at the same indent level as the "Project Level" caption, and the individual entries in each section should be indented on leve from that.
- [x] There is no sub-heading that delineates the project specifications from the info that begins on the Target Points page (starting with Parking Provided) - this is strange.
- [x] Under the Results section the Target and Earned Points should be indented at the same place as the word "Results" in the caption.
- [x] There is no indication on the print-out whether the project is draft or snapshot, visible or hidden, active or deleted, or submitted.
- [ ] When this issue is complete please move the #1662 to the New issue approval column.

### Resources/Instructions
- #1314 
- [Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=4586-16931&mode=design&t=2bZMBMHimyFivH0i-0)
__________________________________
The current Print out page 
<img width="590" alt="Screenshot 2024-01-09 at 1 15 37 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/df55504d-5e3d-48e7-a7df-8ca6d730a9c4">
__________________________________
Approved Print out page 
<img width="718" alt="Screenshot 2024-01-09 at 1 30 56 PM" src="https://github.com/hackforla/tdm-calculator/assets/98936028/08832ac0-7b1e-41bc-a331-c390c8ab0cd4">

**Comment by WomB0ComB0** [comment]
The only thing I was not able to accomplish was the background image on the headers.

![image](https://github.com/hackforla/tdm-calculator/assets/95197809/8d194e70-a561-4e6e-a6af-3e290ce445ec)

**Comment by ExperimentsInHonesty** [comment]
### Things that are still being worked on by the developer for which there are clear designs) 
- [ ] Section headings should have light grey background
- [ ] Below Project Level line, the Project Specifications should have a minor heading with light grey background for each section of the project specification that is used (e.g., Residential) at the same indent level as the "Project Level" caption, and the individual entries in each section should be indented on level from that.
- [ ]  Under the Results section, the Target and Earned Points should be indented at the same place as the word "Results" in the caption.

### Things that seem to already resolved in the dev environment
- Project Name is aligned next to the Project Name section caption, instead of on the right.

### Things that cannot get worked on by the developer because designs are unclear about how to resolve
- There is no sub-heading that delineates the project specifications from the info that begins on the Target Points page (starting with Parking Provided) - this is strange.
- There is no indication on the print-out whether the project is draft or snapshot, visible or hidden, active or deleted, or submitted. (this will be addressed by design on issue #1653

**Comment by WomB0ComB0** [comment]
@ExperimentsInHonesty will post updates soon!

**Comment by WomB0ComB0** [comment]
@heejung-hong Yes, could not find a way to add the light grey backgrounds for the sections specified. Pushing now.

**Comment by WomB0ComB0** [comment]
This is about as close as I could get.
![image](https://github.com/hackforla/tdm-calculator/assets/95197809/d90da05b-ad9a-4f67-ab30-f16328641214)

**Comment by WomB0ComB0** [comment]
For future reference
![image](https://github.com/hackforla/tdm-calculator/assets/95197809/2512cc9c-baa4-4ebb-92c1-e55755684b90)

**Comment by entrotech** [comment]
I'm taking this issue back, so I can sort out what the requirements really are with stakeholders, et. al.,
