### ISSUE TITLE
Updating all the Icons based on the Style Guide

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1681]
### Dependency
- #1682

### Overview
We need to update all the icons all over the website to be consistent also based on the style Guid
### Action Items
 
Check all the icons and make sure they are consistent with the [Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?usp=sharing)
and getting the icons from [Material Icons](https://mui.com/material-ui/material-icons/?query=download)
### Resources/Instructions

[Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?usp=sharing)
[Material Icons](https://mui.com/material-ui/material-icons/?query=download)

**Comment by ExperimentsInHonesty** [comment]
It looks like the dependency is satisfied.  
- Please review and determine if this is ready for prioritization.  If it is, add the `ready for prioritization` label.  
- If you are still drafting this issue, add a `draft` label.  
- If you have a question, for another lead, add the appropriate `ready for` label (ready for product, ready for dev lead, ready for research lead, ready for design lead).

**Comment by maulieshah** [comment]
revise the issue @NilakshiS

**Comment by ExperimentsInHonesty** [comment]
[The images on the site from font awesome](https://github.com/search?q=repo%3Ahackforla%2Ftdm-calculator+react-icons%2Ffa&type=code)

**Comment by NilakshiS** [comment]
Here is a list of pages where replacements are required:

1. Use [Warning icon](https://mui.com/material-ui/material-icons/?query=warning&selected=Warning) in Material Design instead of warning-icon.png
   - client/src/components/Faq/DeleteFaqModal.jsx
   - client/src/components/Layout/NavBarToolTip.js
   - client/src/components/ProjectWizard/WizardPages/Level0Page.jsx
   - client/src/components/ProjectWizard/NavConfirmDialog.js
   - client/src/components/Projects/DeleteProjectModal.js
   - client/src/components/Faq/SaveConfirmationModal.jsx
2. Use [Search icon](https://mui.com/material-ui/material-icons/?query=s&selected=Search) in Material Design instead of search.png
   - client/src/components/Projects/ColumnHeaderPopups/MultiSelectText.js
   - client/src/components/Projects/ProjectsPage.js
   - client/src/components/Projects/ColumnHeaderPopups/TextPopup.js
3. Use [Close icon](https://mui.com/material-ui/material-icons/?query=close&selected=Close) in Material Design instead of Font Awesome close icon
   - client/src/components/Checklist/ChecklistModal.js
   - client/src/components/UI/AriaModal/ModalDialog.js

**Comment by entrotech** [comment]
- Created development issue #1880

**Comment by entrotech** [comment]
- Created development Issue #1880
