### ISSUE TITLE
Determine feasibility of switching from Font Awesome to Material UI icons

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1682]
### Overview
We want to find a larger collections of relevant free icons to use in the app than offered by the current collection of Free Font Awesome icons.  One option is the Material UI icons, but that involves importing some large NPM modules as well, which might cause excessive bloat in the code base. Determine if using the Material UI icons actually causes an unacceptable increase in the size of the JavaScript downloaded to the browser.

### Action Items
We need to research to see if the Material Icon libraries are useable with the app .(Tree shaking) If feasible, we will have the designers change out all the icons currently in the application designs with Material UI icons, and pass the changes to dev. [Issue #1681](https://github.com/hackforla/tdm-calculator/issues/1681)

### Resources/Instructions
[Style Guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit?usp=sharing)
[Material Icons](https://mui.com/material-ui/material-icons/?query=download)

**Comment by entrotech** [comment]
The bottom line is that Material UI icons do not bloat the bundle size significantly (using the webpack bundle analyzer (https://blog.jakoblind.no/webpack-bundle-analyzer/):

Without Material UI icons:

![Image](https://github.com/hackforla/tdm-calculator/assets/9939032/98fc734a-b91a-4d37-9612-6c0c343eb0fb)

Static bundle size: 5.32 MB Parsed Bundle Size: 1.69 MB Gzipped size: 482 kB

With Material UI Icons (using instructions from here: https://mui.com/material-ui/material-icons/)


![Image](https://github.com/hackforla/tdm-calculator/assets/9939032/211276ef-023d-498d-9638-6881be8d0c14)

Static bundle size: 5.47 MB Parsed Bundle Size: 1.75 MB Gzipped size: 500 kB

With Material Design Icons imported via react-icons NPM package (https://react-icons.github.io/react-icons/icons/md/, the bundle size is identical to "Without Material UI Icons" above. This appears to be the same icon set as the Material UI icons mentioned above. This method also allows mix-and-matching any of the icons from the set listed here: https://react-icons.github.io/react-icons/

I would recommend 

- installing the react-icons pacakge
- migrating the existing FontAwesome icons to use the react-icons package, rather than the current imports
- getting UI design to choose one of the libraries available to react-icons and map existing icons in the app to their replacement in the new icon set.
- migrating each existing icon to its replacement.
