### ISSUE TITLE
Create a consistent style for modals across the website

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1743]
### Overview

The modals that we use across the TDM calculator website are not consistent. Consolidate the different modal designs to create a consistent style that is aligned with our design system.

### Details
The website uses a lot of modals in different contexts and the style guide currently lists three different type of modals:
- Warning Modal
- Action Modal
- Important Information Modal

However the modals across the website have too many variations in style and do not necessarily follow the style guide. We need to organize the modals into categories and decide on a consistent style for each category with limited possible variations. 

You can suggest a new category if needed or combine categories. 

When creating designs, here are some things to consider:
   - Typography of title text in modals
   - Use of subtitle or description in modals
   - Use of periods at the end of sentences in modals
   - Number and type of buttons used in modals and their alignment in the modal window
   - Type of icons to use, their size and placement.
   - How the area behind the modal will behave. Will it be blurred or have a grey overlay? 

### Action Items
- [ ] Create mockups on Figma for suggested modal design.
- [ ] Review with Product and Dev update the design if needed based on feedback.
- [ ] Update style guide presentation if needed.
   - [ ] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
- [Link to Figma file for this issue](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1739-3531)
- [Link to document with the list of all the modals on the website](https://docs.google.com/document/d/1W388jJPKFK0TXGZcmbx_LeI1Umn9Zy1PWBQY-pKNXwc/edit?usp=sharing)
- [Link to style guide for typography, colors and buttons in the design system](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)
   - [Link to Modals (or Dialog Boxes) in the style guide](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g1443c52839c_0_143)

**Comment by lbeatonn** [comment]
<img width="636" alt="Screenshot 2024-08-21 at 6 55 45 PM" src="https://github.com/user-attachments/assets/e1d0ffef-dadb-45a3-898a-ec3ce3b9cfe2">
<img width="674" alt="Screenshot 2024-08-21 at 6 56 05 PM" src="https://github.com/user-attachments/assets/20b2fae9-accd-4fb5-ba0e-26e022f96f90">
<img width="686" alt="Screenshot 2024-08-21 at 6 56 15 PM" src="https://github.com/user-attachments/assets/6d10ecb8-9dd5-4c20-bd97-bd1e20f829ce">

Update: Added any modals I thought needed to be addressed. Meeting with the team and evaluating further to pass to fev.

**Comment by lbeatonn** [comment]
Establishing guidelines on our various modal types in the Figma file
<img width="231" alt="Screenshot 2024-09-04 at 2 55 59 PM" src="https://github.com/user-attachments/assets/de9eec65-bfdf-4d29-b0d4-673b1c875d66">

**Comment by lbeatonn** [comment]
Should these smaller modals be included in this scope? 
<img width="723" alt="Screenshot 2024-09-04 at 3 12 10 PM" src="https://github.com/user-attachments/assets/91ae9251-8930-446f-ab1e-75266e4381ee">

**Comment by lbeatonn** [comment]
![Screenshot 2024-09-18 at 4 32 34 PM](https://github.com/user-attachments/assets/6f4614d3-bb9f-4375-a046-1b6937e9bf3b)

NOT PRIORITIZING THIS ISSUE (Please set the status to 'prioritize backlog')

Update: We are working on 2 components in DESIGN to encompass the various modal styles

**Comment by lbeatonn** [comment]
UPDATED NOTES (Sept 25th) 
The Problem: 

We have collected all the Modals on the production dev site on this [page](https://docs.google.com/document/d/1W388jJPKFK0TXGZcmbx_LeI1Umn9Zy1PWBQY-pKNXwc/edit?usp=sharing) Request access from Nilakshi to view. Here we have the path, URL, and screenshot of the modal. The developed modals are inconsistent with the design system slides and do not have the best alignment and spacing. 

Update on Solution:

We have gathered the different modal types from the designs to look at
![Screenshot 2024-09-25 at 5 31 31 PM](https://github.com/user-attachments/assets/414a7888-32eb-4f69-82b7-eebdb8f834d0)

From these variations, I think we should consolidate the modal types into 2 components which can be developed and then reused throughout the site. 

Modal Type 1 - [Information Modal]: (https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14166-36802&t=S9hXi8QWhE7S1bAV-1): 




https://github.com/user-attachments/assets/1d6e5cc2-66ea-4dc2-9b60-a7cc85b541df


View the video and as you can see, we can change the icon, text type, and button configuration to match the needs of the design scenario.

Modal Type 2 - [Action box with Choices]: (https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14178-300&t=S9hXi8QWhE7S1bAV-1)] : IN PROGRESS - still working on showing the variations on this 

The Plan: After making the right components in figma, we can outline the different ways the modal changes in the design system slides, replace the component into the designs, and then finally, have the developers create the components in code and then we can assist them in replacing the modals on the production site. Having components is the best way to maintain consistency on these modals and it will help the developers save time because they won't have to code each individual one.

**Comment by greenishviolet** [comment]
### 10/08 Progress Update

**Progress**
- I have been looking through the TDM Modals List document, Style Guide Presentation, and the work Logan has been doing

**Blockers**
I have some questions about this issue:
1. Am I expected to continue with what Logan has been working on?
2. It seems that Logan has consolidated the warning modal and important information modal. Would changing/adjusting the style guide be feasible?

**Availability**
I can dedicate about 8 hours this week

**ETA**
I think I can have this issue completed by the next meeting.

**Pictures**
none at the moment

**Comment by namigoeku** [comment]
I just realized another thing to consider is how the area behind the modal will look. Will it be blurred or have a grey overlay? Updated the issue to include how the background will look. 

![4)](https://github.com/user-attachments/assets/f4f4e8e2-23e9-4c4b-86ec-5d44785d3573)

**Comment by greenishviolet** [comment]
### 10/28 Progress Update

#### Progress
- I decided to keep the 3 modal types shown in the Style Guide Presentation (Action, Warning, Important Information)
- I categorized the modals in the TDM Modals list into the three categories
     - I categorized the Checklist & Terms and Conditions Modals as Important Information Modals since they both presented information the user must read
- I used components from the updated design system (#1365)
- @namigoeku The modals will have a grey overlay behind them

#### Blockers
**I have some questions about styling**
1. Am I using the right button style for the secondary button?
2. How do we feel about the alignment of text & radio buttons in the Action Modal?
3. The icon for the information modal looks similar to the warning modal. Is it necessary to introduce a new icon?

#### Availability
I can dedicate about 10 hours this week

#### ETA
Other than small tweaks, I think I am done with this issue.

#### Pictures
<details>
<summary> <strong>Action Modal</strong> </summary>

<h4>Component</h4>

> ![Action Modal Component](https://github.com/user-attachments/assets/f9141a88-bd3c-4b1e-94ce-7c32817e598f)

<h4>Example Use Cases</h4>
- Duplicate Project
     
> ![Duplicate Project Modal](https://github.com/user-attachments/assets/9bce2c3f-4c28-4aae-9747-cff902df46e8)

- CSV Modal - 2
     
> ![CSV Modal - 2](https://github.com/user-attachments/assets/6027fc4c-ac18-4858-a79f-162116f5abf8)

</details>


<details>
<summary> <strong>Warning Modal</strong> </summary>

<h4>Component</h4>

> ![Warning Modal Component](https://github.com/user-attachments/assets/f5fdde33-8af2-4cc8-9148-553a1cafa9f4)

<h4>Example Use Cases</h4>
- Delete Project Modal

> ![Delete Project Modal](https://github.com/user-attachments/assets/047182fd-7457-4f92-99ba-2bbb96e3569f)

- Save FAQ Edits Modal
> ![Save FAQ Edits Modal](https://github.com/user-attachments/assets/5070cac7-efdd-44e4-8735-99a18cea0891)

</details>


<details>
<summary> <strong>Important Information Modal</strong> </summary>

<h4>Component</h4>
- Small Modal

> ![Small Information Modal](https://github.com/user-attachments/assets/b9f4723c-e3d8-425d-b2da-50e268336546)


- Large Modal
> ![Large Information Modal](https://github.com/user-attachments/assets/c9580877-d3aa-475a-9f54-15913846aeff)

<h4>Example Use Cases</h4>
- Inapplicable Strategies Modal

> ![Inapplicable Strategies Modal](https://github.com/user-attachments/assets/dcf9a1f9-bc30-4703-ba1f-c3625a6cc7d3)

- Checklist Modal
> ![Checklist Modal](https://github.com/user-attachments/assets/340bc072-1ca7-4fd6-8330-8a0df1a5b431)

- Terms & Conditions Modal
> ![Terms   Conditions Modal](https://github.com/user-attachments/assets/01ce9d06-58d6-40c1-bcb3-37e0ab743285)

</details>

**Comment by marlenamellody** [comment]
New [button styles](https://github.com/hackforla/tdm-calculator/issues/1768#issuecomment-2445658755) have been approved by stakeholders and can also be found in our [updated design system](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=16119-11634&t=cQmoj09SIKr2PtoJ-1). The cancel button should be in the secondary style (black outline) and the warning button will now use white text instead of black. I would also suggest switching the positions of the buttons to have the cancel button on the left and the primary/warning button on the right to match what's on dev. We can discuss alignment and icons during our meeting.

**Comment by greenishviolet** [comment]
### 11/05 Progress Update

#### Progress
- Based on last week's feedback, I changed the text style of the modal heading so there is more typographic hierarchy
- I worked on drop shadow styles with @namigoeku. We decided it would be better to establish 3 drop shadow styles that can be used consistently on other components in the design system. Drop shadow styles were referenced from Material 3 Design.

<details>
<summary>Drop shadow styles</summary>

![Image](https://github.com/user-attachments/assets/6e9600df-a1a6-474f-8ffc-09df57da7c76)

</details>

#### Blockers
None at the moment

#### Availability
I can dedicate about 10 hours this week

#### ETA
I think I am done with this issue, unless there are additional tweaks I have to make.

#### Pictures

<details>
<summary>Action Modal</summary>

![Image](https://github.com/user-attachments/assets/5ffcaa13-d3a2-4ce3-9ec2-2299f57207fe)

</details>

<details>
<summary>Warning Modal</summary>

![Image](https://github.com/user-attachments/assets/8e55f093-f7f2-441b-9d52-51d0020b9ea6)

</details>

<details>
<summary>Important Information Modal</summary>

![Image](https://github.com/user-attachments/assets/cc43d0e0-1f90-4218-a198-90c5c27a15b8)

</details>

**Comment by greenishviolet** [comment]
### 11/13 Update

I updated the components to match the designs on the slides.

![Image](https://github.com/user-attachments/assets/18af6e02-9543-4471-8d1e-fb01273685e1)

**Comment by NilakshiS** [comment]
@greenishviolet the important information should have only one green CTA button for "I understand" or "I accept" is that not correct? Here's a link to the design on the slide deck that were approved: [link to slide](https://docs.google.com/presentation/d/1Urb8pV-P-05586u2c59nEjmUeWa_3s4kJUETi8lllOw/edit#slide=id.g3112a01eb45_0_0).

**Comment by NilakshiS** [comment]
Thanks for the update! @greenishviolet , closing the issue now with an image of all the modals in this comment for reference.
![Image](https://github.com/user-attachments/assets/3e3e2c0d-27a9-47f1-89f8-f91c29c32189)

**Comment by greenishviolet** [comment]
### 2/12 Update

Top and bottom padding of the modals have been updated to spacing is more even.

<details>
<summary>Updated components</summary>

![Image](https://github.com/user-attachments/assets/4b8122a7-c97d-45a4-a43b-7b37574cf4b7)

</details>

<details>
<summary>New modals with updated designs</summary>

![Image](https://github.com/user-attachments/assets/e65f1f01-5e71-442a-a01b-97a575c3726c)

</details>
