### ISSUE TITLE
Design an easy option to reset the filters and sort back to default

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1833]
### Overview
As a user I want to be able to clear all the filters and sort sections at once, so I can get back to the default view. Design a way to reset the sort and filters to default.

### Details
Currently the only way to clear filters, is to open each column header.  Additionally you cannot reset the sort back to default unless you know which of the sort options is the default. 

### Action Items
- [x] Compare the current designs (in figma), to see if there was something that did not get developed and needs to be sent again to dev.
- [x] If there is no design already, create a prototype.
- [x] Review with Product, Dev and Research and iterate if needed based on feedback.
- [ ] Once finalized, get Stakeholder sign-off via the stakeholder meeting slide deck.

#### Resources
- On Page load the following filters and sort order is selected by default:
  - Filter by "Visible" projects
  - Sort by oldest "Created On" date first
- My Project's page https://tdm-dev.azurewebsites.net/projects
- Design Issue for filters #1578
  - [Link to Issue 1578 Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=T72RYUQU9k6TOA9W-1)
  - [Link to Issue 1578 protype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)
- [Link to current Figma file, Issue 1816](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=3331-11990&t=hfZyqX5uESvG4vA3-1)

**Comment by NilakshiS** [comment]
@thetanmancan 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
remember to add links to the top of the issue if they are going to be needed again.

**Comment by thetanmancan** [comment]
September 18th, 2024
Progress: I'm experimenting with different possible UI solutions for this problem. I haven't landed on one yet.
Blockers: There are no blockers as of yet.
Availability: I have fifteen hours to work on this issue this week.
ETA: I'm hoping to have this issue resolved by September 25th.

**Comment by thetanmancan** [comment]
@NilakshiS @marlenamellody @namigoeku I'm moving this issue to the Questions/Clarifications section of the project board for your feedback and applying the "ready for design lead" tag to discuss the below questions.

**Progress**: There are currently two competing design when it comes to listing out each selected filter:
1. Pills located above the table.
![Pills above table](https://github.com/user-attachments/assets/91481f2d-da3a-47bf-829e-9840a7525b1a)
2. Pills located inside of a drawer.
![Pills in drawer](https://github.com/user-attachments/assets/f2eaecb7-a4a0-4ed5-934e-98a59b340440)

In both cases, the main two problems being stated in this issue have been addressed:
1. An altered filter icon in the column header lets users know that a filter is active in addition to the aforementioned pills. Returning any column to its default state is as simple as clicking into the filter overlay's "Reset" button.
2. Users can use a "Clear All" button to remove all applied filters in one fell swoop.

**Blockers**: In last week's meeting, it was decided to have an icon to the left of the filter icon in the column headers that indicated that sorting is active. However, that design decision brings up more questions.

1. Which symbol should be used to represent that sorting is active in a column? I have a few ideas that I grabbed from the Material Design library, but I don't know that any of them are necessarily right for our use case. I'd like some feedback.
![Icon options](https://github.com/user-attachments/assets/93eee1c0-abb2-42ee-975a-5c9af6242b0e)

2. Should the space required for the symbol be built into the column header, or is it better to have the column width expand to accommodate the symbol when it's implemented?
![Column header without space for icon](https://github.com/user-attachments/assets/4b945d3c-9186-41a4-bb5d-654ac215729b)
![Column header with space for icon](https://github.com/user-attachments/assets/2e80df97-06c2-41e2-ba41-3e7d02df1501)

3. How should the sort order be reset back to its default? Currently, the only way to reset sort order back to default is to the Reset button within a filter overlay, but the Reset button resets both the sort order and all the selected filters within that column. Assuming that the sort icon can't be a toggle, then the next best option is to place a "Clear sort" button within the sort section of the overlay.
![Sort overlay](https://github.com/user-attachments/assets/10084ff5-3b1d-4372-9937-c46b02dc634c)

**Availability**: Ideally, I'll be able to commit fifteen hours this week.

**ETA**: This issue requires UX team decision-making and feedback. I can only finish work on this once those decisions have been made. I'm sure it will only take a few more hours of work after that.

**Comment by thetanmancan** [comment]
@NilakshiS I'm moving this issue back to Questions/Clarifications section. Please see below.

On the "-My Project > Filtering (#1816-Open)" Figma page, at the bottom of the "#1833" section, there are six different prototypes for what the "Clear All" button could look like if we don't use the drawer or pill design. Please take a look at them and decide which of them you'd like to use for the stakeholder presentation on October 15th.
![Image](https://github.com/user-attachments/assets/89d446b6-b899-42c5-b639-d360ca14eaa1)

Also, in the same section, just above the "2024/10/14" section, there is a mockup below the label "3. How should sorting be cleared?" That question was not answered last week.
![Image](https://github.com/user-attachments/assets/4f8009fa-010c-4654-b7e8-ca4f4e5dc8a1)

If the stakeholders decide to go with the current dev site design for filters, i.e. not pills and not a drawer, then there is no way to clear sorting back to its default setting without also clearing all the filters in the same overlay.
![Image](https://github.com/user-attachments/assets/04fc8917-0b87-42fa-bdf4-37ab85c30305)

**Comment by NilakshiS** [comment]
Need feedback from product: Currently "Reset" button clears both filters and sort and there's no way to reset just the sort. Is that the desired function? Or should we create a separate button to clear sort?

<details><summary>An example of a filter overlay with different buttons to clear sort and filters</summary>

![Image](https://github.com/user-attachments/assets/4a46cd3f-ecc7-4150-a328-64d018848bb1)
</details>

**Comment by ExperimentsInHonesty** [comment]
What kind of sort do the stakeholders want 

1. Stable sort (the way that google sheets works) 
You can sort by one column, and then by another column, and it remembers the first sort, so if the second column has values that are the same, the results within that value will be sorted by the prior sort.  See image where its sorted by time first, and then sorted by day, so it shows all the Friday meetings in order of time.
![image](https://github.com/user-attachments/assets/1585aa72-3f0a-44b2-958d-c07b40c0ae08)


2. Column sort (the way it's working now)
When you sort the column, no other columns remain sorted, the results of sort items that have the same name/title will be random.  see image

![image](https://github.com/user-attachments/assets/55fa4dfa-7a98-43c6-a42d-722986af7447)

**Comment by NilakshiS** [comment]
Feedback from stakholder meeting on 10/15/24: 
- For "Clear All filters" function, text buttons next to search bar are selected. 
- A button next to search bar is usually the search button so we should keep a search button even if it's not needed so that the users do not accidentally clear all filters. 
- The button should stay on page even if no filters are selected and should be "Clear All Filters (0)".

<details><summary>Screenshots of button designs approved by stakeholders</summary>

![image](https://github.com/user-attachments/assets/d90796f3-5121-4467-95a7-7c5d17929222)
</details>

**Comment by thetanmancan** [comment]
Status update for @NilakshiS:

Progress: Prototypes of the possible "Clear All Filters" button were presented to stakeholders. I created three more possible variations based on what was selected during yesterday's meeting. 
<details><summary>Three prototypes in the "My Project > Filtering (#1816-Open)" Figma page, at the bottom-right portion of the "1833" section.</summary>
![Screenshot 2024-10-15 211641](https://github.com/user-attachments/assets/02baa831-7b8a-4da8-b7b2-bf99ae911c97)
<details>

Blockers: We need stakeholder, developer, and product feedback about whether sort is expected to have only primary or both primary and secondary sorting functionality. See Bonnie's comment from yesterday above. This decision will impact whether or not a "Clear Sort" functionality needs to be implemented into filter overlays, as shown in the mockup below.
<details><summary>"clear sort order" mockup</summary>
![376792768-4a46cd3f-ecc7-4150-a328-64d018848bb1](https://github.com/user-attachments/assets/837eb56f-d14d-4dbe-9851-546f97420d9e)

Availability: I have 15 hours this week that I can spend on TDM Calculator, whether it be for this issue or another one.

ETA: Completion time depends on feedback. If we only have primary sorting, it would only take half the week to design and implement "clear sort order" links. If we have primary and secondary sort order, we will have to come up with designs for that functionality, which will likely take the entire week and possibly also next week as we think through the implications of that decision.

**Comment by NilakshiS** [comment]
Final Design: 
- search bar moved to left
- clear all filters button on the right, with number of selected filters in parentheses.

<details><summary>Design with no filter selected</summary>

![Search moved to the left, no filters selected](https://github.com/user-attachments/assets/69102b82-a0b4-45cc-93c5-d0adf682e9ea)
</details> 

<details><summary>Design with some filters selected</summary>

![Search moved to the left, filters selected](https://github.com/user-attachments/assets/bdc4cd74-5fc9-4a4c-b3d7-4974bbfefd6c)
</details> 

- "Sort to default" designs not planned for now, deferred till decision is made on #1907

**Comment by ExperimentsInHonesty** [comment]
change the name of the button to Reset Filters/Sort

**Comment by thetanmancan** [comment]
@NilakshiS

For this redesign, I removed the number after the button label because I figured it would be confusing for the user as to whether the number was a combination of sorting and filtering or was just filtering. However, we can add the number back in. Just let me know what is preferred. Thanks.

<details><summary>Reset Filters/Sort</summary>

![Reset Filters Sort](https://github.com/user-attachments/assets/0d9933a6-88a8-4327-8d30-da983db66055)
</details>

**Comment by thetanmancan** [comment]
@NilakshiS 

Based on Bonnie's feedback, I tried experimenting with different designs for the Reset Filters/Sort button. While doing so, it occurred to me that if a user has the My Projects table open on a 720p screen at full screen, their resolution could cause all the elements on the toolbar row to collide if the Reset Filters/Sort button gets too wide.

With that in mind, if you look on the ["-(#1816-Open) My Project > Filtering" Figma page](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=3331-11990&t=Bt2OGYoH5DXCx8ic-1), at the bottom of the 1833 section, there are a bunch of permutations I created.

Understandably, we wanted to show how many filters were active in the Reset button, as well as which sort was active. However, trying to include all that information in one button created some spacing issues, as you can see here:
<details><summary>Reset Filters/Sort with number and label</summary>

![Image](https://github.com/user-attachments/assets/a87d1fb6-7f6f-4570-854b-a105d17a14a7)
</details> 
And here:
<details><summary>Reset Filters and Reset Sort with label and number</summary>

![Image](https://github.com/user-attachments/assets/0f5f2a57-0b02-4d60-8b79-93b567e491a5)
</details>

One way to reduce the space taken up is to change the name of the sorted column to just the number of sorted columns.
<details><summary>Reset Filters and Reset Sort with numbers</summary>

![Image](https://github.com/user-attachments/assets/6ec756e9-c976-4845-862e-c74b3d79cb27)
</details>
However, I personally think that having just a 1 value for the Sort without the ability for it to ever be a different value is a bit awkward.

I tried designing other options. One is that when either filters or sort are active, the "Reset Filters/Sort" button is active.
<details><summary>Reset Filters/Sort without numbers</summary>

![Image](https://github.com/user-attachments/assets/c902b2cf-1554-4c82-b36a-3242a8887cea)
</details>
And once the button is clicked, its label changes to "No Filters or Sort Selected" and is grayed out.
<details><summary>No Filters/Sort Selected</summary>

![Image](https://github.com/user-attachments/assets/c771d0be-06ed-4a06-83aa-dbf42027377b)
</details>

Another option is to make it so that the toolbar is divided into two rows. That way, we can make the labels for the Reset buttons as long as we want. It's not particularly aesthetically pleasing, but it does solve our spacing problem, and might even make way for screens of even smaller width than 1280 pixels.
<details><summary>Reset Filters and Reset Sort with two toolbar rows</summary>

![Image](https://github.com/user-attachments/assets/d1126483-3c74-4eea-9a2c-a01ba8c67985)
</details>

Let me know what you think about these designs. I'm happy to discuss them with you over Slack before our meeting. Thanks.

**Comment by thetanmancan** [comment]
@NilakshiS

Thank you for your feedback. I've made some mockups of your suggestions that I'll place below. That way, if you'd like to present them to the Design team for feedback or to the general production team, they'll be ready for that.

<details><summary>Reset Filters/Reset Sort with number and label truncated</summary>

![Reset Filters Reset Sort with number and label truncated](https://github.com/user-attachments/assets/90580e23-fc38-442b-9622-e0dc840033f4)
</details> 
<details><summary>Reset Filters/Reset Sort with number and no label</summary>

![Reset Filters Reset Sort with number but no label](https://github.com/user-attachments/assets/11bde3d5-5d0c-4fb9-a4e9-e473a34a84d7)
</details>

**Comment by NilakshiS** [comment]
From the stakeholder meeting on 11-12-2024: "Reset Filters/Sort" is selected as the text for the button since there are some default filters (for eg: no deleted projects shown) and a default sort (last modified column, descending) so the numbers might be confusing (do we set it to 0 if no additional filters are selected or not?) . Final design: https://github.com/hackforla/tdm-calculator/issues/1833#issuecomment-2448789576
