### ISSUE TITLE
Implement finding the filters have been chosen

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1860]
### Dependency
- #1829 

### Overview
As a user, I want to be able to see what filters and sorting I have chosen and what filters / sorting are selected by default so I understand my results better.

### Resources/Instructions
An example of how Google Sheets indicates selected filters
[Link to "My Projects" page](https://tdm-dev.azurewebsites.net/projects)
Design Issue https://github.com/hackforla/tdm-calculator/issues/1578
[Link to Figma file](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=11866-11910&t=T72RYUQU9k6TOA9W-1)
[Link to the Figma Prototype for filtering UI](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=12173-2052&t=wQuxLI1JbOw0OzLn-1&scaling=scale-down&page-id=2499%3A11472&starting-point-node-id=11997%3A885)

**Comment by amiteshsrivastava11** [comment]
@NilakshiS @ExperimentsInHonesty It seems like we are addressing this by having the ![image](https://github.com/user-attachments/assets/5390ff3e-8800-433a-a013-762924febd2d) be highlighted when someone is using the sort. If they choose multiple sorts, will all the icons be highlighted?

**Comment by NilakshiS** [comment]
@amiteshsrivastava11 This issue was made to implement a design issue in the future, but the design issue was later closed as unplanned. The sorting icon is from a different design issue #1919 but I'm not sure if there's already an "implement" issue created for it. You can either edit the title and description of this issue to make it for #1919 or create a new one, if one does not exist. 

Regarding multiple sorts: Multiple sorts (stable sort) are not possible currently and unplanned for now. We'll create a new design issue in the future if needed to find the best way to show multiple sort.

**Comment by NilakshiS** [comment]
@amiteshsrivastava11 @ExperimentsInHonesty My bad, I thought stable sort was unplanned because of this stakeholder [meeting slide](https://docs.google.com/presentation/d/1b7Gy6XtTb5Lb0BgMDY98tnVQrQ0SxKW_NQULmR4jm_I/edit#slide=id.g2fc7b7f73cc_0_128) where it says it's planned for post-launch but it seems John has already implemented it in issue #1981? Then should I create another issue to get designs for the multiple sorting?

**Comment by NilakshiS** [comment]
Closing this issue as related issues are already open:
- #1996 
- #1999
