### ISSUE TITLE
Update the design and prototype for My Projects Filters on Figma

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1885]
### Overview
The prototype for My Projects Filters on Figma is outdated. We need to update the design and prototype to match the current design deployed on dev.

### Action Items
- [x] Make changes to the new prototype (linked in resources) 
   - [x] Update the table headers
   - [x] Update the filter icons
   - [x] Update the sort buttons
   - [x] Update the primary button style and text
   - [x] Update the date picker UI
   - [x] Update the pagination UI
   - [x] Update the connections and components
- [x] Review the dev site to ensure all changes are incorporated
- [x] Add any new changes from issue #1816

### Resources/Instructions
- [Link to "My Projects Page" on dev site](https://tdm-dev.azurewebsites.net/projects)
- [Link to old prototype on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=12173-2052&t=asZQfnZ5cldg15st-1)
- [Link to new prototype on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=14857-36047&t=asZQfnZ5cldg15st-1)
  - [Link to interactive prototype](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11990&node-id=14857-37246&node-type=frame&viewport=6839%2C-4000%2C0.25&t=6BZzZiFUkD2agnPC-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14857%3A37246&show-proto-sidebar=1)

**Comment by NilakshiS** [comment]
- Updated the designs and prototype. 
- New prototype linked in resources. 
- Screenshots of designs below.
<details><summary>Projects Table</summary>

![Image](https://github.com/user-attachments/assets/ddd479e0-147e-45d0-8db9-258f4de0a348)
</details> 

<details><summary>Filter Mockups 1</summary>

![Image](https://github.com/user-attachments/assets/b187ef6b-7857-471a-bf8f-dcab32a1ba40)
</details> 

<details><summary>Filter Mockups 2</summary>

![Image](https://github.com/user-attachments/assets/152f71db-20f2-41f0-9fed-e66cf509ef6b)
</details> 

<details><summary>Filter Mockups 3</summary>

![Image](https://github.com/user-attachments/assets/7c5bc0e2-5a4b-4928-900f-d7cb72239c2d)
</details> 

<details><summary>Filter Mockups 4</summary>

![Image](https://github.com/user-attachments/assets/a7a29cb8-f86d-4512-8b04-13ffd2fa28ce)
</details>

**Comment by hnoriega27** [comment]
![Image](https://github.com/user-attachments/assets/d31ce101-89d2-4653-80fb-f836533526e2)

- Updated HEX Background
- Updated HEX Text

![Image](https://github.com/user-attachments/assets/fc7f7473-34ff-4a6a-8d11-ac04bf85ac0d)

Popular Design Systems that was researched
Material Design (Google), Atlassian Design System, IBM Carbon, Microsoft Fluent Design, Adobe Spectrum, and Shopify Polaris. 

Material Design - 
https://m3.material.io/styles/icons/applying-icons

Atlassian Design System
https://atlassian.design/components/icon/icon-explorer

IBM Carbon Design System
https://carbondesignsystem.com/elements/icons/library/

Microsoft Fluent Design
https://fluent2.microsoft.design/iconography
This design system is interesting because Microsoft separates their OS icons (Windows/Mac) from their online icons, termed "web icons". However, all browser icons are the same for uniformed consistency. 

-

@thetanmancan **Overall, the popular design systems have one set of UI iconography that are cohesive to all browsers**

Links:
Presentation https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g1443c52839c_0_2

**Comment by hnoriega27** [comment]
![Image](https://github.com/user-attachments/assets/bcd43248-8fd7-4607-b6a2-a698450ef186)

Slide 03 | Table of Context:
Updated the table of contexts to match the new slides. 

@marlenamellody cc// @thetanmancan

**Comment by hnoriega27** [comment]
![Image](https://github.com/user-attachments/assets/6f89cae9-9c04-42fe-a548-c9bea0d26a7a)

Slide 07 | Color Palette:
Updated the color box to properly reflect #1967D2 and #1450A4. Good catch! I agree, the drop-down menu and radio buttons are fine as navy blue. No need to change it to another color, especially as it falls under secondary color to highlight contrast. Unless it's grayscale? Either way, I think it's fine as navy blue.

**Comment by hnoriega27** [comment]
![Image](https://github.com/user-attachments/assets/d3bb4a2f-00fc-49ce-87d4-4e0cb18342f5)
![Image](https://github.com/user-attachments/assets/3bae02ff-c882-4699-abaa-542c2f5fa433)

Slide 08 | Color Palette:
Agree with elaborating more on the definitions with primary, secondary, grayscale and semantic colors to help provide proper terms and guidelines as its informative for stakeholders 

Agree—expanding on the definitions of primary, secondary, grayscale, and semantic colors is valuable, as it helps establish clarity on the proper terms and usage. Definitions can help provide a better understanding of the design system to other people (stakeholders, teams) besides designers. I took some time to create the following slides. These slides are not published but would like confirmation and feedback in order to move forward.

**Comment by thetanmancan** [comment]
@hnoriega27 Please stop posting your updates for #1998 to this issue.
