### ISSUE TITLE
Design: Create a mockup for a warning modal when resetting project

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1900]
### Overview
A warning modal or message should appear when a user selects the reset project button to ensure a project is not accidentally lost. Create a mockup for the warning modal.

### Action Items
- [ ] Create a mockup on Figma
- [ ] Review with Product and Dev. Update the design if needed based on feedback.

### Resources/Instructions
   <details><summary>Warning modal from create projects page for reference</summary>
   
   ![Image](https://github.com/user-attachments/assets/8c70f6e3-33c8-472c-a48c-7e835396620d)
   </details> 

- [UX Research recommendation on Warning Modal](https://docs.google.com/presentation/d/15T05DYjmiuiztDpU8iGzn2zHb7i2ANn9XjpJCqUKdvo/edit#slide=id.g2894ee3ff01_0_0)
- #1743 
   - [Link to document with the list of all the modals on the website](https://docs.google.com/document/d/1W388jJPKFK0TXGZcmbx_LeI1Umn9Zy1PWBQY-pKNXwc/edit?usp=sharing)

**Comment by thetanmancan** [comment]
(https://github.com/user-attachments/assets/8b0f85d4-7a1f-4349-b280-76fa3d1847e8)
![Important Info Box 2](https://github.com/user-attachments/assets/85500afc-b1bf-4ce9-b3b2-d076266403c0)
![Warning Box](https://github.com/user-attachments/assets/b2e818de-7524-4030-863e-e9f8b1babf1b)

**Comment by thetanmancan** [comment]
@NilakshiS, based on tonight's discussion with the team, I'm advocating for the following design:
<details><summary>My ideal design</summary>

![Image](https://github.com/user-attachments/assets/c519ebac-2f79-4216-b04b-cf6cfbceac93)
</details>

Here's the reasoning:
- Compared to the other two modal options, it's the most visually pleasing to me.
- It puts the warning symbol front and center. Putting the warning symbol next to the text does not give it the level of importance I think it needs to visually carry the message across that the user is about to lose all their entered data.
- I decided to put a question mark in the title so that it serves as a question that the user must answer using the buttons presented, as opposed to simply repeating the text of the button that the user just clicked.
- In the style guide, all buttons are given a horizontal padding of 32 pixels around the word in the button that is wrapped. But because the words "Cancel" and "Proceed" have different lengths, the buttons had different lengths, so I shrunk the width of the Cancel button to match that of the Proceed button so that they would be symmetrical. If we want to change that, that's fine with me.
- In the style guide revamp that was presented tonight, the secondary button has a black stroke around the button. However, when placed next to the warning button in this modal, the Cancel button looks a bit too highlighted, almost looking like a call to action and drawing too much visual attention away from the Proceed button, as shown below. Therefore, I changed the color of the stroke to a medium grey. We can change this back if you feel strongly about it.
<details><summary>Cancel with black stroke</summary>

![Image](https://github.com/user-attachments/assets/96e3823f-7daf-43c6-bbac-b0c90dd92c37)
</details>

Let me know if you have any questions or want me to make any more changes.

**Comment by ExperimentsInHonesty** [comment]
@thetanmancan 

change wording to 

### Saved projects
All unsaved data from this project will be lost.
Project Last Saved: XXXX

### Unsaved projects
All unsaved data from this project will be lost.
Project Last Saved: unsaved project

**Comment by thetanmancan** [comment]
@NilakshiS 

I changed the date information to "MM/DD/YYYY hh:mm [timezone]" format, but it brings up the question of whether to display it in the user's timezone or default it to Pacific time.

I also changed the coloring of the icon to match the warning color of the button, but if you don't like it we can change it back.

I also changed the "PROCEED" button's text color to white to match the style guide.

<details><summary>Design update</summary>

![Saved projects](https://github.com/user-attachments/assets/834bfb7f-76c6-4e1b-a3b6-9482cb81a422)
</details>

Let me know what you think. Thanks.

**Comment by thetanmancan** [comment]
@NilakshiS @marlenamellody 

I've updated the designs to match Grace's suggestions from [Issue 1743](https://github.com/hackforla/tdm-calculator/issues/1743).

For saved projects, I used the date-time format that is used at the bottom of Page 5 when a project is submitted and saved. Thank you for that suggestion/lesson in how the system works, Marlena.
<details><summary>Saved Project modal</summary>

![Image](https://github.com/user-attachments/assets/95645810-0b2b-4e36-996f-face1f52befc)
</details>

For unsaved projects, I have a version that is a direct translation of Bonnie and the stakeholders' requested text.
<details><summary>Unsaved Project modal according to explicit request</summary>

![Image](https://github.com/user-attachments/assets/61af7253-7861-4ba1-a7d8-759d662c9f09)
</details>

However, it occurred to me that the language is somewhat redundant. Instead of introducing the term "unsaved," which doesn't specify anything in the context of the modal because all of the data is unsaved, I figured I'd leave out the term altogether.

Instead of:
"All unsaved data from this project will be lost.
Project Last Saved: unsaved project"

I suggest:
"All data from this project will be lost."

It says the same thing, but in much simpler terms.
<details><summary>Unsaved Project modal according to my suggestion</summary>

![Image](https://github.com/user-attachments/assets/a559cba9-1e98-49ec-bffd-3ceefaebf354)
</details>

**Comment by thetanmancan** [comment]
@NilakshiS

I've further updated the designs.

For unsaved projects, I got approval from Bonnie to use the simplified language I recommended last week. We're still waiting for stakeholder approval on the colors to be used for warning modals (from [Issue 1743](https://github.com/hackforla/tdm-calculator/issues/1743)), but for now I've updated it so that the red is redder.

<details><summary>Unsaved Project warning modal</summary>

![Unsaved Project 2](https://github.com/user-attachments/assets/3c0cfd84-31c6-49b8-ae32-af16f770ebc9)
</details>

For saved projects, I made the same temporary color changes as we await stakeholder approval. I also changed "Project Last Saved" to "Date Last Saved" and made it bold so that its terminology and formatting is consistent with how it appears on Page 5/TDM Calculation Summary page after the Save Project button is selected.

<details><summary>TDM Calculation Summary's Date Last Saved field</summary>

![TDM Calculation Summary, Date Last Saved](https://github.com/user-attachments/assets/7b92cc53-4e22-440b-9ba7-45b9b18b9b82)
</details>

<details><summary>Saved Project warning modal</summary>

![Saved Project](https://github.com/user-attachments/assets/0bda08af-ae46-4441-8ebd-c09e4e38773c)
</details>

**Comment by NilakshiS** [comment]
From Stakeholder meeting on 11-12-2024: Designs Approved, determined behavior to be:
- Saved project keeps you on the same page
- Reset project takes you to page 1 of calculator

**Comment by thetanmancan** [comment]
@NilakshiS I'm updating this issue with versions of the modals that have the question marks in the titles removed so that they are in line with the updates to our style guide.


<details><summary>Warning modal for saved project</summary>

![Saved project](https://github.com/user-attachments/assets/e13bb7c7-cbff-414e-b75e-0ce4708028fc)
</details>

<details><summary>Warning modal for unsaved project</summary>

![Unsaved project](https://github.com/user-attachments/assets/612f4df8-ad05-41dc-85dd-cd30a17b3574)
</details>

**Comment by NilakshiS** [comment]
@thetanmancan Changes accepted, updated the screenshots on relevant dev issue on #1942
