### ISSUE TITLE
Design: Create mockups for page 1 and 3 with reset buttons

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1902]
### Overview
Currently, page 1 and 3 of the calculator do not have "Reset Page" and "Reset Project" buttons like page 2 and 4. UXR recommends adding them for consistency and so that users don’t have to move forward or backward to reset a project.

### Action Items
- [x] Create a mockup of calculator pages with reset buttons:
   - [x] mockup of page 1
   - [ ] mockup of page 3
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add  before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g310c0321c6c_0_0)
- [ ] get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
- [Link to create project on TDM Calculator dev site](https://tdm-dev.azurewebsites.net/calculation/1/0)
- [UX Research recommendation on consistent reset buttons](https://docs.google.com/presentation/d/15T05DYjmiuiztDpU8iGzn2zHb7i2ANn9XjpJCqUKdvo/edit#slide=id.g20534e932cc_0_89)

**Comment by mjldesign** [comment]
Created two options:

* Option 1 retains the existing position of the Reset buttons from P2 and P4, and simply places them on P1 and P3. With this option, however, the buttons can look out of place on P1 and P3:

![Image](https://github.com/user-attachments/assets/cd039c61-b29f-4667-a95f-70828ef84dee)

* Option 2 relocates the position of the Reset buttons on all P1-4, placing them with the page navigation buttons at the bottom of the screen. There are the options to have the Reset buttons above or below the navigation arrows, each with their inherent pros/cons:

![Image](https://github.com/user-attachments/assets/bfd1b4d2-06a7-45b5-82ba-d8ee430ba85d)

Additionally, I recommend updating the verbiage of the "Reset Page" button to "Clear Page". This helps distinguish the difference between losing all progress on the project, and simply clearing the page. It also reduces cognitive load for the user about what it means to "reset" versus "clear".

**Comment by ExperimentsInHonesty** [comment]
Try to find other places for the button.  For instance they could be vertical on the right side.

**Comment by marlenamellody** [comment]
Team feedback from 11/6/24: The second option is preferred. Suggestion: Explore updating the text buttons to a tertiary [button](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=16061-4518&t=8TdgfbYMWrMRpB4L-4) style and consider alternative placements.

**Comment by mjldesign** [comment]
**Based on team feedback, explored using the tertiary style for reset buttons**

---

**First Option: Change button style to Tertiary. Retain position.**

![Image](https://github.com/user-attachments/assets/ca546955-7c98-429b-9d8f-14352f857da7)
![Image](https://github.com/user-attachments/assets/057cb150-5270-40ec-9386-701bff1c3bda)
![Image](https://github.com/user-attachments/assets/58ee9bb2-f17d-486b-b796-91af89f086a7)
![Image](https://github.com/user-attachments/assets/0dee69cf-fe25-4da4-81e6-ae2d241df0ff)
![Image](https://github.com/user-attachments/assets/b2c33fc2-359c-4dbc-95c0-b5c2c7445172)

**Benefits:**
+ Buttons are easier to click, with a wider click target

**Drawbacks:**
- May break visual hierarchy
- Buttons now look too similar to each other and on some pages appear as the CTA, which shouldn’t be the case.

**Notes/discussion points:**
Is the tertiary button style appropriate for these buttons? Or, do they need to be relocated?

---

**Second Option: Change button style to Tertiary. Change position to bottom of page**

![Image](https://github.com/user-attachments/assets/6ebc0a1b-6d2a-4b60-b215-4ad6328bc173)
![Image](https://github.com/user-attachments/assets/ff18b043-984e-4e8c-a7fd-75a741c5e61f)
![Image](https://github.com/user-attachments/assets/63bd37a0-c17c-429d-9150-de0bda3f22cf)
![Image](https://github.com/user-attachments/assets/9038b2c5-6549-4c9a-8f8e-055b1e4207ec)
![Image](https://github.com/user-attachments/assets/680015ef-76da-4dbc-8604-cc7ecc6874f9)

**Benefits:**
+ Buttons are easier to click, with a wider click target
+ Buttons are located after main CTA, reducing accidental clicks

**Drawbacks:**
- Buttons still look too similar to each other and on some pages may still appear as the CTA, which shouldn’t be the case.

**Notes/discussion points:**
In order to have the buttons retain the tertiary style, my recommendation is that the CTA (next/back) buttons need to be more prominent, perhaps with text instead of navigational arrows.

**Comment by NilakshiS** [comment]
From team meeting 2024-11-13:
- The buttons in the tertiary style look too prominent on the page compared to the text style buttons. Especially when it's centered on the page, and if the buttons are centered then they might clash with the infobox for bonus package.
  <details><summary>Bonus package infobox on the page</summary>
  
  ![image](https://github.com/user-attachments/assets/fbc8951f-73b3-4c99-a69a-bd61fb4e96ec)
  </details> 
- Bonnie suggested creating a vertical button mockup on the side as it is a space that is not utilized, the buttons can be sticky (stay in their place even when the user scrolls) for longer pages but be careful about placing them too close to the scrollbar to avoid accidental clicks.
  <details><summary>Image for Bonnie's suggestion</summary>
  
  ![image](https://github.com/user-attachments/assets/c1f0cb33-6834-4f42-9739-48a3a9aebcb2)
  </details>

**Comment by mjldesign** [comment]
Update: Change buttons position to the right edge, vertically stacked and sticky as page scrolls

Benefits:
+ Buttons are easy to click, with a wider click target
+ Utilizes empty space on page and does not affect the format or flow of the fields

Drawbacks:
- Appears too prominent on the right side of the page
- If browser window is very narrow, the page may break and buttons may overlap main content.
- Because the button text is rotated 90 degrees, reading the function of each button is more difficult and can lead to accidental clicks and increased cognitive load.
- Scroll bar may be affected on MacOS 

Notes/discussion points:
Does not seem like an intuitive or natural place that a user expects to find a reset button

![Image](https://github.com/user-attachments/assets/c777f037-3598-44e6-95b9-eb8ffe1fc0db)

**Comment by NilakshiS** [comment]
Team meeting 2024-11-20:
Need to discuss the two options: 
1. Text buttons aligned on the right, like how they are on the page currently.
2. The sticky vertical tertiary buttons, in the previous comment.

with the stakeholders in the next stakeholder meeting.

**Comment by NilakshiS** [comment]
From the stakeholder meeting on 2024-12-03:
- Option 1, with Text buttons on top and aligned on the right is selected.
- However, move the parking provided and the rest of the content on page 3 lower so it is not on the same line as the buttons.

Make changes to the design and update this issue with new images.

**Comment by mjldesign** [comment]
Updated designs with stakeholder feedback:

<details><summary>Page 1</summary>

![Image](https://github.com/user-attachments/assets/6df88d1a-084d-4718-ad55-c15b631c7743)

</details>
<details><summary>Page 2</summary>

![Image](https://github.com/user-attachments/assets/be8ac72e-6d30-4a0a-af96-98f0725099fe)

</details>
<details><summary>Page 3</summary>

![Image](https://github.com/user-attachments/assets/0612342b-a46f-4c0b-9c4f-d51ee1a19560)

</details>
<details><summary>Page 3 Error</summary>

![Image](https://github.com/user-attachments/assets/c8b37f12-07b6-46ef-a53f-c40e0e6a20e7)

</details>
<details><summary>Page 4</summary>

![Image](https://github.com/user-attachments/assets/6f606c49-413e-4c32-84b5-42332a91cead)

</details>
