### ISSUE TITLE
Indicate which column the board is sorted by

### ISSUE THREAD

**Issue by marlenamellody** [hackforla/tdm-calculator#1919]
### Overview
Design a way to indicate when a column has an active sort order. So that users can see which column the board is sorted by.

### Details
Filter states are currently indicated by icons. Based on stakeholder feedback, the reset button on the My projects page will reset both filters and the sort order. Therefore, we need a clear indicator to show which column currently has an active sort order. 
<details><summary>The current columns only have the filter icon</summary>

![image](https://github.com/user-attachments/assets/399ebb40-c634-4050-863c-4213eaa1f162)
</details> 

### Action Items
- [x] Capture the As Is State (i.e., the current view) 
- [x] Design an indicator of some sort (could be an icon, label or other)
- [x] Review with product and design. Update if needed based on feedback
- [x] Get Stakeholder sign-off via the stakeholder meeting slide deck.
- [x] Give Dev the design and has them use this [slide ](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g3192ed00331_0_6)

### Resources/Instructions
[My projects page](https://tdm-dev.azurewebsites.net/projects)
[Figma: My projects](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=3331-11990&t=GD1cnggZZVLHKhOy-1)

#### Other issues about the sort function (with images)
- [x] https://github.com/hackforla/tdm-calculator/issues/1907
- [x] #1833

**Comment by thetanmancan** [comment]
@NilakshiS Progress update 2024-11-13

**1. Progress:** I'm in early days on this issue. I'm organizing it by a series of eight questions I want to answer with designs, and I've only prototyped one of those designs, and I don't think that prototype is going to get approved because it would take too much development time to undo the sorting functionality in the filter overlays we have.

If you want to check out what I'm trying to do, go to [this Figma prototype](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=16582-4077&t=hfQAWYcMTzOffIma-1) and click the up/down icon in the Visibility column header. See the screenshot below for where to click specifically.

<details><summary>Click the sort icon to make it sort</summary>

![Sort icon sorts](https://github.com/user-attachments/assets/b404364f-69ad-4f24-8868-c8a035feedae)
</details>

**2. Blockers:** No blockers. I just haven't had the time I would have liked to work on this issue.

**3. Availability:** I'm hoping to have 15 hours worth of time this week. 

**4. ETA:** I'm hoping to have this issue ready for review by next Wednesday.

**Comment by thetanmancan** [comment]
@NilakshiS Progress update 2024-11-19

I just need feedback on my design questions, which you will find on [this Figma page](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4472-16923&t=MODjnVu2y1QJM4ZZ-1).

More specifically, you will find the designs and their respective prototypes in the Design section shown below.

<details><summary>Design section with prototype flows</summary>

![Screenshot 2024-11-19 171556](https://github.com/user-attachments/assets/82e258ea-7c49-4376-bf1c-4ecd3f39994d)
</details>

**Question 1:** Can the sort icon toggle sorting?

To make the prototype work, click on the double chevron icon in the Visibility column header.

<details><summary>Click the sort icon to make it sort</summary>

![Sort icon sorts](https://github.com/user-attachments/assets/b404364f-69ad-4f24-8868-c8a035feedae)
</details>

I believe from previous meetings, it was established that we don't have the development resources to separate the sort menu from the filter menu and create a new sort toggle. Therefore, I believe the answer to this question is a simple "no", but I still wanted to create a prototype in case for some reason we wanted a point of reference for how it could work if we decide the other designs I've come up with won't work.

**Question 2:** Should the sort icon be built into the column header's width?

To make either of the prototypes work, click on anywhere other than the checkboxes in the first column or any of the column headers.

<details><summary>Click anywhere</summary>

![Screenshot 2024-11-19 215748](https://github.com/user-attachments/assets/f93cd634-bf1c-4b28-b8ca-ae379d1c7bb7)
</details>

You'll notice that for the prototype on the left, the column width doesn't change when the sort icon moves from the Visibility column header to the Alternative Number column header. However, for the prototype on the right, the column width does change. It only changes slightly because I chose a sort icon that only takes up 9 pixels in width, but the amount of change in column width would be more dramatic if we chose a different sort icon.

**Question 3:** Which icon should we use for sorting?

To make the prototype work here, click any of the filter icons. They can be click multiple times to change the appearance and direction of their sort icon.

<details><summary>Click the filter icons</summary>

![Sort Icon tests](https://github.com/user-attachments/assets/6b1477a1-52e4-47a4-bb30-303bce4058ab)
</details>

When looking through the Material Design library, these were the only icons I could find that I thought would make any sense as sort icons. I personally prefer the arrow all the way on the left because
1. It has the least effect on the column header width, and
2. Because of its small width, it's easier to understand that it's meant to be additive with the filter icon and be seen as one interactive button rather than be seen as a separate button and therefore have different functionality.
That being said, I wanted to give other options in case other people had differing opinions.

**Question 4:** Can we add a hover state for active filters?

As with the above prototype, this prototype works by clicking the filter icons multiple times.

<details><summary>Click the filter icons</summary>

![Filter Hover Tests](https://github.com/user-attachments/assets/476948f9-9851-46ce-8f9c-6a7bc74c52f6)
</details>

I noticed that the filter icon that we're currently using has a hover state for when the filter is inactive, but not when it's active. That seemed oddly inconsistent and asymmetrical, so the purpose of this question is just to ask whether we're OK with adding a hover state when the filter is already active.

**Comment by NilakshiS** [comment]
From team meeting on 11/20/2024: 
1. Same as before, using sort icon to toggle sorting is not planned for now. Using the filter menus to change sorting is preferred.
2. Sort icon built into the header width is preferred.
3. Icon to use for sorting to be decided by stakeholders, options are presented in the stakeholder meeting slide for next week.
4. Adding a hover state is fine.

**Comment by NilakshiS** [comment]
From stakeholder meeting on 12/03/2024:
- Following icon for sorting is selected from the choices:
![image](https://github.com/user-attachments/assets/5390ff3e-8800-433a-a013-762924febd2d)

**Comment by thetanmancan** [comment]
@NilakshiS I created a final design to try and make handoff to the developers a little easier. It's in the Final Design section of the [#1919 page in Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4472-16923).

<details><summary>Final design with handoffnotes</summary>

![Final design with handoff notes](https://github.com/user-attachments/assets/f3ef178f-f5f0-4365-84a9-0ad2657e1d09)
</details>

Is there anything I need to do? Shall I move this from "In Progess" to some other status on the project board, such as "Visual Review"?

**Comment by NilakshiS** [comment]
@thetanmancan This looks good! I made some changes and left a comment on Figma, just update the Figma and edit your comment here with the new image. We can close this issue and hand-it off to dev then, I'll check if there's a dev issue.

**Comment by thetanmancan** [comment]
Thank you, @NilakshiS ! I've updated the image. Please confirm with dev that there is a dev issue for this before I close this.
