### ISSUE TITLE
Bug: When browser window is not extra wide, cannot see the left-most columns on My Projects Page

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1927]
#### Describe the bug 

When the browser window is not extra wide, there is a horizontal scroll bar, but the user cannot scroll far enough to the left to reveal the left-most columns.

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

REPLACE THE FOLLOWNG TEXT:
- 1. Go to the My Projects Page
- 2. Narrow your browser window
- 3. There is a horizontal scroll bar, which is scrollled to the left, but the left-most columns are off-screen to the left.

#### What's the expected result?
You should be able to scroll to see any of the columns.

#### What's the actual result?
Cannot scroll horizontally to see left-most columns.

![image](https://github.com/user-attachments/assets/8f66c038-7d67-4176-be73-31ce62eb15e9)

#### Device configuration

At least on this hardware/software:
- Device: laptop
- OS version: Windows 11
- Browser: Chrome and Firefox

#### Closing
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g3163b6ed272_0_0) 
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have identified the issue causing the horizontal scrolling problem in the Projects page. The main cause was the fixed minimum width set on the table. I've made the following changes to address this:

1. Removed the fixed minimum width from the table.
2. Added a responsive container for the table with horizontal scrolling.
3. Updated the table layout to use percentage-based widths for better responsiveness.
4. Adjusted the pagination component to be more compact on smaller screens.

These changes should allow users to scroll and view all columns, even on narrower screens.

I also created pull request: https://github.com/hackforla/tdm-calculator/pull/1928


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
Appeared in the [2024-12-03 Stakeholder deck](https://docs.google.com/presentation/d/1vc_LUPreHrToHBRGUekbXfLflOi3omt2Bo8M7uxMovI/edit#slide=id.g31a1cbf228f_0_0) and was approved.
