### ISSUE TITLE
New Project link doesn't work within a project

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#201]
### Overview
New Project link doesn't create a new project when there's already one open.

Currently, with the deep-linking (#141 ) of wizard pages, clicking the link goes to the 1st page. It wasn't working before that either. It would just not do anything.

### Action Items
- [ ] Create a new project when New Project link is clicked within an open project, and go to page 1.

**Comment by ExperimentsInHonesty** [comment]
Decision by Bonnie, Bradley and Kevin to 
conditionally render the new project link, based on if they are on a project.
if on project - don't show the new project link
if not on project - show the new project link

**Comment by nclairesays** [comment]
@ExperimentsInHonesty @bfojas @KPHowley  what is the flow then If they are on a project but want to scrap their project and create a new project?

**Comment by KPHowley** [comment]
Currently the way would be to leave the wizard  by going to a page such as "projects" and then going back. Ultimately we would most likely want a "start over" or some sort of abandon and create a new project button

I think some confusion is caused by the entire wizard view being called "new project" in the menu, and this should be a topic for further  discussion.

**Comment by nclairesays** [comment]
Ok, for now, i'll conditionally render the new project link for now
