### ISSUE TITLE
Architectural Decision: Testing frameworks

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#231]
### Overview
Research various testing frameworks (Cypress, Selenium, and React) to determine the best testing practices and procedures to implement. 

### Action Items
- [x]  @bradley prepare research on React Testing Library
- [x]  @nclairesays  prepare research on Cypress
- [x]  @fyliu prepare  research on Selenium
- [x] Group meeting on 2/11 to decide
- [x] Follow up meeting on 2/11 to review

### Resources/Instructions
Template:
 https://docs.google.com/document/d/1qvTyjaS0CnmT3umqWg9LJmAcZzHL6tpi5eCQWeh6ovQ/edit?usp=sharing

**Comment by KPHowley** [comment]
follows up #207

**Comment by fyliu** [comment]
I added what I have in the page following the template.
I also changed the file name to match this issue.

**Comment by fyliu** [comment]
We discussed cypress and selenium and I felt that both are very similar in usage. The tangible difference is that selenium requires installation of webdriver binaries for target browsers, which John had issues with setting up for the Jobs-for-Hope project. Cypress likes to show the replay feature, which is potentially good in regression testing as a debugging tool. It feels less useful for acceptance testing. We've decided to implement a test case in both to compare next week.

@nclairesays will create cypress test for Barrington
@fyliu will create selenium test for Barrington

**Comment by fyliu** [comment]
Continuing the discussion with what I found while working toward Selenium testing.

https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2019-264e19514d0a

A couple disadvantages of cypress, side-effects of its running as a layer **inside** the browser rather than along side it:
- no headless testing (slower since it needs to render the browser to get its results)
- no drag-and-drop
Mainly Chrome support with beta support of firefox.

Selenium itself is built for browser automation and not specifically for testing although it can be used that way. The webdriver it provides is used by other tools that are made for testing, the most used one seems to be WebDriverIO.

https://www.cypress.io/how-it-works

This one diagram is a good summary of the difference that developers would see. Cypress is the Angular of the testing world while Selenium is more like React. By this, I mean that Cypress is an all-in-one framework that provides as much as it can and the developer need not look outside the walls. Selenium does one thing which is the WebDriver which controls web browsers. It doesn't provide a testing framework, assertion module, convenience wrapper, or mocks. A developer is free to, or actually, must, choose those things, which can be very positive for projects that already have something in place, or negative, for projects that are short on resources and need something simple to set up.

**Comment by joelparkerhenderson** [comment]
You may want to take a look at ING Lion for emerging ideas about JavaScript testing. Lion is a compelling new JavaScript project (in my opinion) and has a significant emphasis on testing because the tools are for finance and government. https://github.com/ing-bank/lion

**Comment by ExperimentsInHonesty** [comment]
continuing testing phase.  Next discussion 2/14.

**Comment by nclairesays** [comment]
Here's information on how Cypress works (and how it's different from Selenium):
https://www.cypress.io/how-it-works

**Comment by nclairesays** [comment]
Here's some basic tests for the barrington condos test case using cypress.  For anyone who wants to check it out, here's the branch I'm working on. Made 3 commits. Make sure to do yarn install for server and client and run both. Then, to run the tests, cd into '/cypress' and run `yarn cypress`or `npm run cypress` and that's it. Easy peezy :) 
https://github.com/hackforla/tdm-calculator/tree/claire-acceptance-tests

**Comment by fyliu** [comment]
I made a branch using selenium(WebDriverIO) to create the test case for Barrington. The test data comes from a json file.
1. Install everything from the project root. No change to the client.

        npm install

2. Run the test case

        npm run tests:e2e
https://github.com/hackforla/tdm-calculator/tree/selenium_testing

**Comment by fyliu** [comment]
I think we're going with cypress for end to end for ease of use. For unit testing, we have storybook that we've been using. We've also been using Jest. I'm not sure if we're still looking at the tools from @testing-library.

**Comment by ExperimentsInHonesty** [comment]
@nclairesays  - john says you were going to do a pull request.  Let us know where you on that.
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@entrotech says after we settle on the testing library, we will need to figure out how we structure the tests.  @bfojas says there is information for stubbing requests, that he will review after Claire's changes.

**Comment by nclairesays** [comment]
Sorry guys, didn't see this thread. I just made a pull request with the Barrington condos test case using cypress. @bfojas @entrotech

**Comment by ExperimentsInHonesty** [comment]
Fang posted in slack:
Fang Liu  10:11 AM
Another thing with testing libraries. I heard that jest/enzyme can't test react hooks by shallow rendering and react testing library can. I think someone mentioned this at a meeting, maybe Bradley Fojas
