### ISSUE TITLE
Change default Project Level to 0 and disable target points and entered points on Level 0

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#281]
### Overview
Change default Project Level to 0 and disable target points and entered points on the sidebar at level 0

### Action Items
- Change default project level
- make target points and earned points disappear on sidebar when level is 0

**Comment by entrotech** [comment]
The default project level was already 0, Issue #282 set the default points to 0 for a Level 0 project.  Bradley will implement change to show "blank" instead of 0 on the sidebar - though I think the Summary page and Target Point calculation pages of the Wizard should still explicitly show the Level as 0 instead of blank, so the user is confident that the project level calculation was actually performed.

**Comment by ExperimentsInHonesty** [comment]
hi @bfojas Can you give us an update on this.  Hope you are ok!
1. Progress
2. Blocks
3. Availability
4. ETA
