### ISSUE TITLE
Bug: Level 0 is not displaying correctly on the TDM target point page 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#284]
Was this when Bonnie entered something like 5 residential units and the level didn't change to 1?

**Comment by entrotech** [comment]
The way it seems to be working now is that if the project is Level 0, the Level and Target Points on the Target Point Calculation page are blank. I fnd this jarring, and would prefer that they both show 0, but UX folks need to decide.

Likewise, the required parking and parking percentages are  blank instead of zero if the user hasn't entered any input on the previous page, and the parking percentage is blank if the user hasn't entered the required parking in the input box.  Again, I find this a jarring experience for the user with stuff disappearing for reasons that may not be obvious to the user.

I welcome other thoughts on this...
