### ISSUE TITLE
Modify Target Point Calculation Page to Show Message if Project Level is 0

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#321]
### Overview
Improve experience for Developers entering projects that don't need to use the tool (Level 0)

### Detail
By the time the user has filled in the Project Specifications, the Project Level can be determined. If the project level is 0, then when they navigate to the Target Point Calculation page, instead of seeing the usual calculation, they should see a message informing them that their project is not large enough to be subject to TDM requirements.

### Action Items
- [x] LADOT to provide language to use on message/stop page.
- [x] Design mockups for message/stop page.
- [x] Get signoff from LADOT on design.
- [ ] Create alternate route to deliver projects to message/stop page.

**Comment by ExperimentsInHonesty** [comment]
@Dsomers74 @ramccarr test of email notifications.

**Comment by KPHowley** [comment]
To clarify for UI/UX:
The way it is supposed to function is this:
If the user's project is a level 0, when they get to the page where they are asked to enter the parking spaces they intend to provide, the get a message that says they do not need to select any measures, and they don't need to go any further in the wizard. LADOT will let us know about exact wording on the message, but we should be able to do something even without the exact message copy.

**Comment by ExperimentsInHonesty** [comment]
@ramccarr is going write the text and this can be assigned to UI/U for a mock up in meantime.

**Comment by dazainus** [comment]
@KPHowley @ExperimentsInHonesty, below are the 2 design mockups for Project Level 0 announcement page.


### DESIGN FOCUS
- This page is designed to show up when the Project Level is calculated to be 0.
- In the dashboard on the left, 'Project Level' should be located on the top while 'TDM point values' are located on the bottom. (See details [here](https://github.com/hackforla/tdm-calculator/issues/321#issuecomment-607605863))
- 'Return to home' button is inserted to guide the user back to the homepage. But, it can simply be replaced to provide guidance to other landing pages, such as 'Read more about Project Level,' 'Learn about LADOT's Initiative' & 'Learn about resources.'
- Exact wording to be provided by the client.


### DESIGN MOCKUPS
#### OPTION 1
- Simple announcement. No images, just wording.

![OPTION 1  A7 Target Point Calculation - Project Level _ 0](https://user-images.githubusercontent.com/55513459/78519037-e7fa2c80-7776-11ea-9f5a-de2fa438e845.png)

#### OPTION 2
- Same written content as OPTION 1. Icon image is inserted.

![OPTION 2  A7 Target Point Calculation - Project Level _ 0](https://user-images.githubusercontent.com/55513459/78519073-02340a80-7777-11ea-8913-50ef1d53f80e.png)


### RESOURCES

- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1054%3A209
- Simple User Journey Map for completing TDM calculation:
![USER JOURNEY](https://user-images.githubusercontent.com/55513459/78518819-60acb900-7776-11ea-8f7e-5ff62211b4c0.png)

**Comment by ramccarr** [comment]
Please change the text below Your Project is Level 0 to "Based on the information you provided, the Transportation Demand Management (TDM) Ordinance may not apply to your project. Final determination of the TDM Ordinance applicability will be made by the Department of City Planning upon review of your project application."

**Comment by dazainus** [comment]
Here are 3 color variants based off of the most up-to-date design of 'Project Level 0.' Since the message is quite important, I implemented red into the design. 

@KPHowley-Please decide which color variant would be the best option.
@mmorgs-Attaching Mindy for the deployment after the decision is made.

### Design Options
#### 1. NAVY ON GRAY
![OPTION 3  A7 Target Point Calculation - Project Level _ 0-navy-gray](https://user-images.githubusercontent.com/55513459/79412170-ab3dea80-7f59-11ea-8e6c-44346a376061.png)

#### 2. RED ON GRAY
![OPTION 3  A7 Target Point Calculation - Project Level _  0-red-gray](https://user-images.githubusercontent.com/55513459/79412173-aed17180-7f59-11ea-8ef8-2fb305f979f9.png)

#### 1. RED ON RED
![OPTION 3  A7 Target Point Calculation - Project Level _  0-red-red](https://user-images.githubusercontent.com/55513459/79412180-b264f880-7f59-11ea-8aca-b12535ff6aa6.png)


### Resources
- Figma: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1071%3A421
- Zeplin (Web): https://zpl.io/290OW9p
- Zeplin (App): zpl://screen?pid=5e9780bb86212b7c6238c412&sid=5e97d14aea76127e862193c1

**Comment by KPHowley** [comment]
@ramccarr and @Dsomers74 - would you like to weigh in on the color for this? I personally like option 2.

**Comment by Dsomers74** [comment]
I concur, option 2.

**Comment by dazainus** [comment]
It's great to hear your feedback @Dsomers74.

Our design team wants to introduce a new method of design decision and implementation: Preference Tests (also known as A/B testing). We believe it would be a great way to reflect user's preference and experience into our designs and to continuously inspect that our visions align with the users. Also, it would be great to have you and your team to participate!

Link to the Preference Test: https://app.usabilityhub.com/do/541366ed56a6/4050

**Comment by Dsomers74** [comment]
Thanks Diane for initiating a preference-based design process. I'll
forward the link to others using the tool so you might get a few more
responses.

**Comment by dazainus** [comment]
@KPHowley - Sharing the preference test results. Please help with Action Statements below.

@Dsomers74 - Thank you for help deploying the preference test amongst your team. We've collected 11 participants in total, and you can see the **interactive results here**: https://app.usabilityhub.com/tests/541366ed56a6/results/2b9c1e0766ba
Kindly let us know what you think after reading my observations below.

### Preference Test Observations
Based on the preference test, we were able to find out:

- **64%** of the participants preferred **'Red letter on red background'** design.
  - **36%** preferred **'Red letter on gray background'** design.
- They picked above answers because **'it is clear which piece of information is important (91%)'** and **'Texts are legible(9%)'**.
- **73%** thought that **'the warning icon & descriptions'** was the most important piece of information, which aligns with our initial goal to make sure users read the instructions. 

### Design Decision
Overall, we observe that the design is successful in **making sure the instruction is read**. Though we internally liked the 'red letter on gray background' design, the test says that users find 'red letter on red background' design preferable (image attached below as a reference). My speculation is that later design is more direct and instant in terms of which information to look at, which we definitely want to achieve throughout the TDM calculation process.

With that being said, I'd suggest **to go with 'Red letter on red background' design** while making sure to obtain visual uniformity throughout various pages.

![OPTION 3  A7 Target Point Calculation - Project Level _  0-red-red](https://user-images.githubusercontent.com/55513459/80056935-4135c000-84da-11ea-90bf-b0be045ef180.png)

### Action Statements

- [ ] Finalize which design to move forward with. @KPHowley @Dsomers74 
- [ ] Deploy the final design to @mmorgs 
- [ ] Deploy similar research / test method for future design decision making process

**Comment by KPHowley** [comment]
After our meeting with LADOT, we do want to move ahead with this color design with two changes. 

1.  The only bold in the copy should be on the word may - "the Transportation Demand Management (TDM) Ordinance **may** not apply to your project" 
2. The words on the button at the bottom of the page should be  "Begin a new project" and it should redirect to a new blank project page

**Comment by dazainus** [comment]
@KPHowley sharing the revised design here. Please let me know if everything looks good.

![OPTION 3  A7 Target Point Calculation - Project Level _ 0-red-red](https://user-images.githubusercontent.com/55513459/80647171-e5f85600-8a22-11ea-8bc3-8b96b006c77b.png)

**Comment by ExperimentsInHonesty** [comment]
Doesn't look like Diane's design
![Screen Shot 2020-05-02 at 10 26 16 AM](https://user-images.githubusercontent.com/37763229/80871068-6a371d00-8c5f-11ea-9dc2-ae01b2fd6ad4.png)

**Comment by KPHowley** [comment]
Eta to push this: 5/8

**Comment by KPHowley** [comment]
Pushed to staging: Ready for final review from Stakeholders
![Screen Shot 2020-05-09 at 9 59 57 AM](https://user-images.githubusercontent.com/49739276/81480369-366b7280-91de-11ea-8165-eecb3179f701.png)

**Comment by Dsomers74** [comment]
This reflects our feedback. Approved.
