### ISSUE TITLE
Warn users before starting a project if they are not logged in

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#349]
### Overview
Develop warning system if users try to save without being logged in.

### Action Items

UI/UX:
- [x] Design a mock up of a warning for users
  - [x] Add a warning box under the login button on the Navbar
  - "You must log in first to save your project."
- [x] Review
- [x] Move to front end Development

FRONT END:
- [x] Add message to first page of the wizard consistent with the design version 1: Red 
- [ ]  The message should only come up if a user is not logged in. 
- [ ] Make the button persistent in the wizard until the user closes the "x"
- [ ]  the button should disappear when the user leaves the wizard or goes to the login page

**Comment by dazainus** [comment]
The message should say: "You must log in first to save your project."

**Comment by dazainus** [comment]
@KPHowley - I tried locating the waring bar under the log in and realized that it covers texts on certain pages. So, it is placed on the navigation bar as reflected in the design shared below.

### Design Mockup
**Version 1 : Red Solid**
- Draws more attention with vivid color
![warning-log in](https://user-images.githubusercontent.com/55513459/84868583-c8626880-b031-11ea-92df-68218bb70e03.png)

**Version 2 : Light Red**
- Overall more blended into the top nav bar
![warning-log in-light](https://user-images.githubusercontent.com/55513459/84868843-242cf180-b032-11ea-9e1a-cab774315af4.png)

I personally think version 1 would be more appropriate as the warning is pretty crucial and the vivid red color draws much more attention to this important message. Please let me know your thoughts!

### Resources
- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1838%3A518

**Comment by dazainus** [comment]
@KPHowley @nclairesays 
Unfortunately, the range of color options(yellow, orange, variations of reds) we liked for the warning message's solid background fails the [WebAIM](https://webaim.org/resources/contrastchecker/) contrast guidelines, failing to make our site fully accessible. With that said, I have selected **color combinations that both meet the accessibility guideline**.

### Design Mockup
#### Version 1: White Text + Solid Red Background (Darker)
- [ ] White text + solid red background color
- [ ] Changed the solid background color to a darker, more vibrant red (HEX #B63920)
- [ ] Applied drop shadow to the white text in order to separate itself from the background, thus make it more legible
- [ ] Meets WebAIM's accessibility guideline
![VER 3  warning-log in-solid-red](https://user-images.githubusercontent.com/55513459/85917994-cc517000-b813-11ea-8681-6fc2fed91b6e.png)

#### Version 2: White Text + Solid Red Background (Darker)
- [ ] Black text + solid yellow background color
- [ ] Meets WebAIM's accessibility guideline
![VER 4  warning-log in-solid-yellow](https://user-images.githubusercontent.com/55513459/85918341-d1fc8500-b816-11ea-9f8d-34ad032da23a.png)


### Resources
- Figma File: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1838%3A517
- For history, refer to the [conversation in our Slack channel](https://hackforla.slack.com/archives/CKY65G266/p1592379650430200).

**Comment by dazainus** [comment]
@KPHowley 
Here are the revised designs reflecting the recent feedback as below.

- [ ] Change the text to 'Only projects created after logging in can be saved'
- [ ] Background is the first page of 'Create Project'
- [ ] Preference on color variation to be tested

### Design Mockup
#### Version 1: Red
_* Compatible with web color contrast guidelines_ 
![VER 5  warning-log in-red](https://user-images.githubusercontent.com/55513459/86851710-454c9500-c068-11ea-8ae2-da660f246ec4.png)

#### Version 1: Yellow
_* Compatible with web color contrast guidelines_ 
![VER 5  warning-log in-yellow](https://user-images.githubusercontent.com/55513459/86851717-47aeef00-c068-11ea-8e4b-d2264a91d8ce.png)

### Resources
- Figma File: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1739%3A4214

**Comment by Jonathanko52** [comment]
Progress: Box set up. Working on positioning and closing functionality
Blockers:None
ETA: 10/3

**Comment by KPHowley** [comment]
@Jonathanko52 - Please provide an update on ETA

**Comment by Jonathanko52** [comment]
Progress: Tooltip now utilizing React Tooltips.  Familiarizing myself with positioning and functionality implementation.
Blockers: Certain features in React Tooltips seem to be conflicting with other elements of the page. 'arrow position' for the tooltip seems to refuse to budge.
Availability: Saturday afternoon. Weekdays after 1pm.
ETA: 10/14

**Comment by KPHowley** [comment]
Update this to only display, when on /calculations

**Comment by Jonathanko52** [comment]
Progess: Basic tooltip working. Implementing 'only display on /calculations' function.
Blockers: None.
Availability: Saturday afternoon. Weekdays after 1pm.
ETA: 10/16
