### ISSUE TITLE
Redirect to Login Screen if user tries to access projects page they are not logged in

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#350]
### Overview

Redirect to New Projects Screen if user tries to access projects page they are not logged in

### Action Items

- [ ] Change the redirect for blocked project routes

**Comment by dazainus** [comment]
The message should say: "You must log in first to save your project."

**Comment by entrotech** [comment]
Closing Issue #351 might also resolve this.

**Comment by lemazza** [comment]
Wasn't there also talk in the meeting of redirecting to the Log In page instead? Which should it be?

**Comment by KPHowley** [comment]
@lemazza - we did discuss that, and I think that;s the best way to handle it, We'll verify tonight.

**Comment by lemazza** [comment]
The redirects for both this and issue #313 are working.

**Attempting an unauthorized project while Logged In => Projects Screen**
![redirects-logged-in](https://user-images.githubusercontent.com/32402365/82740482-02c03a80-9cfe-11ea-9a33-54c64ad891bb.gif)

**Attempting an unauthorized project while Logged Out => Login Screen**
![redirects-logged-out](https://user-images.githubusercontent.com/32402365/82740483-03f16780-9cfe-11ea-9006-15fa5bde38dd.gif)

### Issues

- In Wednesday's meeting we discussed the possibility of making the Toast pop ups looking like the Level 0 Warning Message. Since the toast pop ups appear in a few other places, this might be best done as a separate issue.

- I currently just put the error message from the server as the status code text, but let me know if something more descriptive should be there. Or if it should be there at all.

- The status code coming back from the server is 404 - Page Not Found, and really should be 401 - Unauthorized, this touches issue #332 for more specific status codes.
