### ISSUE TITLE
Investigate best way to use migration files to update the database

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#352]
### Overview
Investigate best way to use migrating files to update the database

### Action Items
investigate Flyway
investigate Liquidbase

**Comment by nclairesays** [comment]
I investigated into two migration library options: Flyway and LiquiBase and have chosen Flyway to move forward with.

Both have the ability to version control databases. In our use case, we mainly just need the ability to write sql database schemas and update database records, which both can do. However, Flyway emphasizes its simplicity and I can confirm from my workplace that it's fairly simple. I also received feedback from someone who has used both and he agrees that Flyway is much simpler than LiquiBase. For our purposes, I am choosing simplicity over any extra bells and whistles, until we need them otherwise.

**Comment by nclairesays** [comment]
Here's also a good description on WHY we need database migrations:
https://flywaydb.org/getstarted/why

and HOW Flyway works:
https://flywaydb.org/getstarted/how

**Comment by KPHowley** [comment]
Decision: Flyway 

Closed this per the creation of issue #374, which is for imlementation
