### ISSUE TITLE
 Add deleting and duplicate capability to project screen

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#380]
### Overview
We need to add the ability to to duplicate and delete projects on the projects page, as well as do a slight design overhaul. 

### Action Items

- [x] Redesign the look of the projects page to match figma 
- [x] Add Duplication functionality to front end
- [x] Add Delete functionality to front  end 
- [x] Link Delete functionality to database (api/db already set up in other previous issues)
- [x] Link Duplication functionality to backend

### Resources/Instructions

- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1444%3A467

![image](https://user-images.githubusercontent.com/49739276/81887066-37d8ca00-9553-11ea-88ff-839bca536d96.png)

![image](https://user-images.githubusercontent.com/49739276/81887052-30b1bc00-9553-11ea-8373-a1eaa12a22f5.png)

- Refer to issue #338 for Design Mockup

**Comment by dazainus** [comment]
On extension to 'duplicate' and 'delete' functions in the 'projects view' addressed above, following screens are designed.

### Duplicate Window
![Projects-Duplicate-window](https://user-images.githubusercontent.com/55513459/82515872-3a48a000-9ace-11ea-9d7a-415a99f90e90.png)

### Delete Window
![Projects-delete-window](https://user-images.githubusercontent.com/55513459/82515879-3d439080-9ace-11ea-8b74-5c9bc9227586.png)

### Resource
- Figma file: https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1444%3A467
- Prototype: https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1444%3A467&viewport=881%2C-223%2C0.5&scaling=min-zoom

**Comment by KPHowley** [comment]
@mmorgs - per meeting with LADOT on 5/26 we are looking at a new design to have 2 buttons for duplicate and delete in line for each project, rather than behind the "..." button. A new mock up for this will be coming shortly.

**Comment by KPHowley** [comment]
### Main Project page
- "..." button is removed
- 'Duplicate' and 'Delete' icons are inserted 
![Up to date](https://user-images.githubusercontent.com/55513459/83091743-c0c22c00-a050-11ea-92d8-2587dfa52c65.png)

### Duplicate Window
![Projects-Duplicate-window](https://user-images.githubusercontent.com/55513459/83091825-eea77080-a050-11ea-8d26-141d8d8e0fba.png)
![Projects-Duplicate-window-copycreated](https://user-images.githubusercontent.com/55513459/83091831-f49d5180-a050-11ea-8d3d-fc85f4f73571.png)

### Delete Window
![Projects-delete-window](https://user-images.githubusercontent.com/55513459/83091836-f8c96f00-a050-11ea-86c5-4e37834b0db1.png)

### Resource
Figma: https://www.figma.com/proto/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=1444%3A467&viewport=572%2C-1013%2C0.5&scaling=min-zoom

**Comment by nclairesays** [comment]
Added more to this issue via commit 1b2c2af 
- Hooked up the frontend delete functionality to the backend delete endpoint
- Commented out the duplicate icon until we hook it up the backend
- Changed the text/copy on the Modal to "Are you sure you want to permanently delete the selected project (PROJECT NAME)?"
- Added a conditional logic to display the trash icon only if the project belongs to the user (so that admins can't delete other users' projects)

**Comment by nclairesays** [comment]
FYI I've reopened design issue #338 due to some questions/suggestions I have about the design.

**Comment by nclairesays** [comment]
During last Wednesday's meeting, we discussed having the project name included as part of the delete and duplicate modals so that the users know which project they are acting on. 

We also talked about automatically filling out duplicate project name with the words "(COPY)" appended to the selected project name, which would look like this:
- 1) ![image](https://user-images.githubusercontent.com/45305029/85371346-ec67f300-b4e4-11ea-83b0-e41068f43f80.png)



However, after a lot of thought, I don't think the above design is obvious that you can choose to use that automatically filled out title OR delete it and fill out a new title of your own. 



I tried a couple of different designs and and I think the following designs have clearest instructions; the empty form field makes it clear that you have to fill it out. Users can also just choose to copy the project name as it's displayed right above. 

- 2) ![image](https://user-images.githubusercontent.com/45305029/85371028-80858a80-b4e4-11ea-814a-d2d7ed0a86cb.png)

- 3) ![image](https://user-images.githubusercontent.com/45305029/85371080-91ce9700-b4e4-11ea-8ee7-8c468a57d84d.png)

Note: issue #445 will add minimum character validations

If we still want to go with the previous decision (i.) then it's just a matter of uncommenting one line of code in the Projects.js file  ```// setDuplicateProjectName(`${project.name} (COPY)`);```
