### ISSUE TITLE
Make notification of email  verification more noticable on login page 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#407]
### Overview

The Notification that an email has been verified is small and goes away very quickly, it should be more prominent on the page 

From feedback - "message is at the bottom of the page, and reviewer said that it should be centered above the login content in the body section"

### Action Items
**Design:**
- [x] Discuss best implementation & warning notices
- [x] Mockup or design, only  if necessary 

**Front end:**

- [ ] Move toast to the top of the page
- [ ] Make color consistent with tool tip in #349 
- [ ] Make toast display for 8 seconds before disappearing
- [ ] Make toast reponsive in accordance with the comment by lemazza below

**Comment by lemazza** [comment]
In order for the Toasts to be centered in the Main area they need to be responsive. They do cover up text behind them on the Z-index at some screen widths. 

### Examples

**Screen Size > 1024**
![toast-xl](https://user-images.githubusercontent.com/32402365/83983509-f59d7100-a8e3-11ea-8852-e876b8fd0454.png)

**Screen Size > 1024**
![toast-lg](https://user-images.githubusercontent.com/32402365/83983507-f59d7100-a8e3-11ea-870b-dcf160d08537.png)

**Screen Size > 768**
![toast-md](https://user-images.githubusercontent.com/32402365/83983506-f504da80-a8e3-11ea-81c1-1f66fad52c72.png)

**Screen Size < 768**
![toast-sm](https://user-images.githubusercontent.com/32402365/83983510-f6360780-a8e3-11ea-9bba-c8b3c62d4d27.png)

### Issues

Making the Toast responsive involves some CSS calculations that account for sidebar width. This will make adjusting either the toasts or the sidebar in the future more difficult. It might be better to import toasts on each page that uses them rather than at the top level, but I could see problems with this approach as well. If we are reevaluating how to use these popup messages, It's probably worth considering importing a toast library such as [react-toastify](https://github.com/fkhadra/react-toastify).

1. Would you like this alignment to be the default for all toast popups, or just the login notification one? Making it the default for all is easier than having different alignments for each.

2. The current length of time Toast messages are displayed is 5 seconds. Is this still ok or do we want longer?

3. I remember some discussion in the meeting of the question mark popup box from page 4 of the wizard. I can't remember if that discussion applied to this and if so what elements from that to apply towards this.

**Comment by KPHowley** [comment]
@lemazza I think we should discuss 1 and 2 with the group, but I do have some thoughts! 

As for 3, we wanted to see if we had any way for making it look as similar as possible to the notification on page 4 with the "!" and the colors, so we can keep a consistent style for warning messages.

**Comment by KPHowley** [comment]
@Jonathanko52 - Please provide an update with:
1) Progress
2) Blockers
3) Availability
4) ETA

**Comment by KPHowley** [comment]
Hey @Jonathanko52  - I'm going to take you off this if you're going to work on the other "save button" issue first!

**Comment by Jonathanko52** [comment]
Progress: None. Beginning work today.
Blockers: None
Availability: Weekdays after 1pm
ETA:11/7
