### ISSUE TITLE
Change email for registration to come from LADOT.TDM@lacity.org

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#440]
### Overview
When a user signs up for an account, the registration should come from: LADOT.TDM@lacity.org 

### Action Items

- [x] Update email 

### Reference
Emails currently coming from: tdm+sendgrid@hackforla.org via sendgrid.net

**Comment by entrotech** [comment]
@Dsomers74 @ExperimentsInHonesty @KPHowley 
To do this, we need to perform a "Sender Identity Verification" as described here: https://docs.sendgrid.com/for-developers/sending-email/sender-identity
We could do the Single-Sender verfication by having someone at the city with access to the email account for LADOT.TDM@lacity.org.
I don't know that we would be able to (or should) do the Domain Verification,  since that would allow our Sendgrid account to send emails with any lacity.org email address.

The better option would be for someone with the city to set up their own Sendgrid account, and perform the verification for that email address, so they can bring management of their email account in-house.

**Comment by entrotech** [comment]
Met with Lon Soh, Alex Molina, Donald Parungao and Eric Rodriguez of ITA on Tuesday Jan 18, 2022 for an hour.
They do not really have an Azure expert on staff (or apparently even any developers), so this involved a lot of fumbling around.
We tried to create a SendGrid account indirectly from within Azure, but did not know who could access the LADOT.TDM@lacity.org email account, so about half the meeting was spent resetting the password for that email. We tried to set up a single sender, but the email Lon Provided when setting up the account was a dummy Azure account email and cannot receive the verification email message.

We decided that it might be better for Lon to create the SendGrid account through the SendGrid site (instead of indirectly through Azure), but ran out of time before we could get going on this.

Lon promised to set up another meeting to continue.

**Comment by Dsomers74** [comment]
Thanks for the update John. Xander is the owner of the
***@***.*** email
account. ITA recently revised the program accounts access protocols to bind
them to a single person in order for us to manage two factor verification.

Did it seem like having access to the ***@***.*** email account
would address barriers in establishing a SendGrid account within Azure? It
looks like the other solution would involve us setting up a new
subscription, which may take a week or so to authorize the expenditure for.

David

**Comment by entrotech** [comment]
Possible meeting with Lon and me tomorrow (2/9/2022) to set up and configure a SendMail account under Lon's name. Apparently, David Somers sent Lon the memo authorizing the expense.

**Comment by entrotech** [comment]
Met with Lon Soh and Alex Molina today. The funding authorization is pending, but Lon created the Sendgrid account for ladot.tdm@lacity.org, verified the email with sendgrid and modified the production App Service configuration settings such that emails from the production environment will show a from address of ladot.tdm@lacity.org. For example, a Public Comment email sent to the web team looks like this:

![image](https://user-images.githubusercontent.com/9939032/153318701-571c9072-c74a-4e3b-ba77-c96eaf9b1351.png)

Note that the from address is determined by SendGrid, and the public comments are sent to planning.mobility@lacity.org and (if the notify the web team checkbox is checked on the Public Comment form) to tdm+prdpubliccomment@hackforla.org as well.
