### ISSUE TITLE
Update inputs in project specifacton pages, add input for Hospitals and for High Schools

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#452]
### Overview
We need to add New land use categories to the Project specifications page, and need a little more information on this first

### Action Items

- [x] Get the parking values formulas associated with each new input (spots per unit)
- [x] Finalize units, titles, and max values or any other details on inputs. 
- [x] Review  [Level Document ](https://docs.google.com/document/d/185LUz5VI0VoBp4kDx0KSZ_pI1zzXfgdB0PlsIgJvxx8/edit) to reflect these as well (if needed)

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=353819215

**Comment by KPHowley** [comment]
@Dsomers74 - We just need a little more information on these new inputs, before we add them. 

Basically we need to know the formula for determining parking on each as well as the units for each. I also want to just make sure we know the new inputs and designations apply for the breakdown of levels, for instance I don't see it noted how the beds break down noted on the sheet and I want to make sure this hasn't changed. 

I noted this things in the check boxes in the issue description as well.

**Comment by Dsomers74** [comment]
@KPHowley it may be easier to discuss the approach to defining entry of hospitals and high schools in context of this page's redesign in Issue #443, where the uses are reconstituted in new categories in [Column B](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=353819215). 

Medical office, hospitals, and convalescent care facilities would be regrouped under a new category of 'Medical Care'. We need to bifurcate the decision point of parking baseline and Program Level in the entry for hospitals, and convalescent care facilities since program level is defined by square footage (same as medical office), while the parking baseline is defined by the number of beds. Though medical office can be defined only by square footage in deciding program level and baseline parking requirements. 

Can we set up sequential entry for hospitals, and convalescent care facilities? For UX consistency, it would help to enter square feet first and have the no. of bed prompt as second entry, maybe as a dropdown option. 

This is similar multi-decision point for High Schools, where program level is defined by the number of students, and parking is defined by either the total square foot or number of fixed seats in an auditorium (1 space required for ever 35 square feet in an auditorium, or 1 space for every 5 fixed seats in an auditorium (See [Section 12.21 A.4(e) of the LAMC](https://codelibrary.amlegal.com/codes/los_angeles/latest/lamc/0-0-0-113040))

**Comment by entrotech** [comment]
I implemented a first pass at the Middle / High School inputs, but for the Hospital / Convalescent inputs, we do not have an input defined for Square Footage, Should there be a new input for Hospital / Convalescent Square Footage on the Project Specifications Redesign tab of [this document](https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=1209152938)?

**Comment by Dsomers74** [comment]
Good catch. The square footage defines Program Level as the same for all
Medical Uses, while there needs to be an additional entry for hospitals and
convalescent Institutions based on the number of beds, which informs the
baseline parking. So it is a two-part entry. I revised the Project
Specification Redisgn
<https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=1209152938>
Tab to hopefully be more clear.

<https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=1209152938>

**Comment by entrotech** [comment]
@Dsomers74 @KPHowley @Bishoy-Tawfik  
I don't think that would work the way you want , since it conflates the square footage for Hospitals and Convalescent Facitlities with the square footage for "other medical" into a single input.  You need to have separate inputs for Hospitals/Convalescent sq ft vs Other Medical sq ft.

This is because Other Medical sq ft contributes to the level calculation AND to the parking baseline at a rate of 5 spaces / 1000 sf, but for Hospitals and Convalescent, the sq ft only contributes to the level calculation and not to the parking baseline, since you want the parking baseline to be based on number of beds. So the system needs to have two different inputs for Medical, one for Hospitals/Convalesceent where the parking baseline is determined by beds and one for "Other Medical" where the sq ft contriibutes to the parking baseline.

**Comment by Dsomers74** [comment]
Thant makes sense John. I just wanted to at least imply they all have same
level per square feet.

**Comment by KPHowley** [comment]
@Dsomers74 , I'm making new issues for everything else we discussed around this issue -  but can you just verify the change we need to make to the two inputs - "Middle and High School students" and "Elementary School - Students."

I believe we simply suggested changing the first input to "Elementary and Middle School - Students" and the second input to "High School students," but can you just verify that this is the case, and if there is any parking calculations needed.

**Comment by KPHowley** [comment]
per Alexander:
SUMMARY OF PARKING REGULATIONS_04-15-2020 (FINAL).pdf
@Dsomers74
Hello @entrotech and @KPHowley!

I'd like to add the method that schools calculate baseline parking requirements to the calculator. Elementary and middle schools (K-8) use the metric of 1 space per classroom. High schools (9-12) use either the auditorium ratios previously discussed (1 space per 5 seats or 1 space per 35 sf if no fixed seats) or 1 space per 500 sf of building area, whichever ends up being greater. I've attached the bulletin from City Planning explaining these ratios. Please let me know if I need to specify this any further.

Have a good weekend,
Xander Wikstrom

this is mentioned in another issue, #512, and i can close this if updates will be made on this.

**Comment by Dsomers74** [comment]
👍 you captured school parking baseline accurately.

**Comment by entrotech** [comment]
Need to modify labels for Elementary /MS to be Elementary / Middle School instead.
