### ISSUE TITLE
Add Initial Analytics to the website 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#584]
### Overview
Add Google Analytics to the website

### Action Items

- [x] Review what Google Analytics does

- [x] Add Google Analytics to each page of the website.

**Comment by KPHowley** [comment]
Please provide an update with: 

    1) Progress
    2) Blockers
    3) Availability
    4) ETA

**Comment by KPHowley** [comment]
@VJ1285  - Just give us an update with:
    1. Progress
    2. Blockers
    3. Availability
    4. ETA

And add any other information you have .

**Comment by ExperimentsInHonesty** [comment]
@VJ1285  - @entrotech will setup GA account through the tdm@hackforla.org and then provide an update here.

**Comment by KPHowley** [comment]
Please provide an update with:
1) Progress
2) Blockers
3) Availability
4) ETA

**Comment by VJ1285** [comment]
> Please provide an update with:
> 
> 1. Progress - Created google account (login: TDMcalc@gmail.com; Password: tdmcalc123); created google analytics & firebase account
> 2. Blockers - none
> 3. Availability - 
> 4. ETA

**Comment by entrotech** [comment]
Created a Google Tag Manager account and a Google Analytics4 accoutn for tdm under the google login tdm@hackforla.org.

Sent invitations to  @VJ1285 @KPHowley @nclairesays to access from their provided email accounts.

Implemented some triggers in the app to detect:

- page changes
- successful and unsuccessful logins, and
- project save operations

This probably needs refinement as PMs and developers get more experience with the reports, but here is an example of some basic real-time reporting in action against the deployed sites at tdmdev.azurewebsites.net and tdmuat.azurewebsites.net:

![image](https://user-images.githubusercontent.com/9939032/101399748-c496fc80-3884-11eb-9dea-a41d95863180.png)

I am leaving the issue open for now, pending review by @KPHowley  and @VJ1285

**Comment by KPHowley** [comment]
@VJ1285 - I copied this from slack:

1. Source of incoming traffic - This will be LADOT but its good to track if users are using some search engine to come to the website.
2.     Return visitor
3.     Bounce Rate - this is track user who come to the site and leave immediately.
4.     Exit Pages - Which pages are users leaving the webpage
5.     Page Views  - This metric is based on when user reviews all the content on the page
6.     Average Session duration - Total time spent per session by a user. We can eventually use this and the below to update the website so that a user gets to the final page in the least amount of time.
7.     Average page Duration - Time spent per page by a user. Again this will provide us insight on how much time each user is spending per page.
8.     Goal Completions - This defined as the number of times a user completes a specific goal. We can have multiple goals like saving project, filling all the info, etc.
