### ISSUE TITLE
Assign correct minimum and maximum values to strategies

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#585]
Some specific changes to the maximum and minimum point values as listed in the program description and spreadsheet. https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=0

Action Items

- [x] Under Transit Access: Neighborhood Shuttle/Microtransit Service, change Possible points to 8 (currently 4 points)
- [x] Under Mobility Investment: Access Improvement, make it so users cannot implement fewer than 5 points.
- [x] Under Telecommute: Telecommute, change Possible Points to 6 (currently 0 points)
- [x] Under Telecommute: Televisits, checking the box changes the Telecommute line to 3 points as well, but does not seem to alter overall point value. Make it so that if Televisits in checked, and the Telecommute strategy is set at 0 days, no points are gained in the Telecommute row.
- [x] Under User-defined Strategy, the minimum should be set to 4.

https://docs.google.com/spreadsheets/d/1LBGlYyj3kiRb9p0UNCWRo9DZVRFAFNEeccCjkCT5jek/edit#gid=0
Column D has maximum points listed for each strategy correctly.

**Comment by entrotech** [comment]
@awikstrom-ladot  Good work on finding these details!  The changes have been deployed to tdmdev.azurewebistes.net (the development environment), so you can try them out there and let me know if I missed anything.

**Comment by KPHowley** [comment]
@awikstrom-ladot  - Checking to see if you made a decision regarding the interaction of televisits and telecommute

"
-Under Telecommute: Televisits, checking the box changes the Telecommute line to 3 points as well, but does not seem to alter overall point value. Make it so that if Televisits in checked, and the Telecommute strategy is set at 0 days, no points are gained in the Telecommute row.
"
