### ISSUE TITLE
Dialog Box notifying user that all their data will be deleted when the user clicks away from /calculation

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#595]
### Overview
Add a Dialog box that informs the user that all the data they have inputted will be lost when they click on "Start Over"

### Action Items
The below dialog box should open up when the user clicks away from `/calculation` and provide the user the option of "Yes" and "No". If the user selects "Yes" then all their data will be deleted. If the user selects "No" then all the data they have inputted stays as it is. 

"Leave page and delete unsaved data? This will permanently delete any unsaved changes or changes to project."

**Comment by nclairesays** [comment]
Starting this issue.

Per wednesday meeting: try to implement notification if user leaves page for any link/button, not just start over. If it's too time consuming, then i will focus on just start over and a separate issue can be created for the other links.

**Comment by ExperimentsInHonesty** [comment]
@nclairesays - as per the conversation on Saturday with @KPHowley and John the wording is going to change.

**Comment by KPHowley** [comment]
@nclairesays  Here's a proposal for a mockup of this with new wording:

![Delete window Start Overpng](https://user-images.githubusercontent.com/49739276/97342824-f22f6580-1843-11eb-9d07-8ce9b226635f.png)

**Comment by nclairesays** [comment]
@KPHowley Can you write one for navigating away from /calculations? because I have that behavior already for navigating away (e.g. clicking on /about). If it's possible to use the same copy for both clicking on Start Over and navigating away, that'd be best.

**Comment by KPHowley** [comment]
@nclairesays - Gotcha I think i can do that....

**Comment by KPHowley** [comment]
@nclairesays Please provide an update with:
1) Progress
2) Blockers
3) Availability
4) ETA

**Comment by nclairesays** [comment]
1.  As mentioned in my PR: "A NavConfirmationModal shows up when attempting to navigate away from /calculation (e.g. /about, /login, etc.) when form is filled out and new updates have not been saved; Added react-router Prompt component"; still working on Start Over button getting modal
2. need text for when user navigates away from /calculation as well as when they click start over
3. Not sure, usually work about 1-3 days a week
4. hopefully next week

**Comment by KPHowley** [comment]
@nclairesays - updated mock up with proposed wording covering all cases:

![Delete window 001](https://user-images.githubusercontent.com/49739276/98188140-521eaf80-1ec7-11eb-90d8-a3eb1c2c434b.png)

**Comment by nclairesays** [comment]
Status: I'm mostly done with the logic for when a user navigates away from /calculation, confirmation dialogue will appear. I've fixed the use case for when a user navigates to /logout. Last thing couple things I'm doing is fix warning messages that are currently appearing in console, and the actual UI part of it (text change/color). 

Should be done by the end of the weekend 


I'd also like to request that we delete the Start Over button completely from all the pages. 

Initially this button was a "Create Project" on just the Level0 page and had changed over time because honestly, it didn't quite make sense there. I don't see this button bringing much user value (whether it's on just the level 0 page or across all pages) because if a user wants to start over, they can just click on the "Create Project" in the nav bar. 

I've also already fixed the above logic so that the form properly clears when you click on that "create project" nav link now (on my local machine. Also available on the remote branch if someone wants to pull down my branch and run the app)

**Comment by KPHowley** [comment]
@nclairesays  - We just discussed this and are all on the same page that **we don't need the start over button and it can be deleted.**  The only thing we wanted to make sure of was that "create project" clears data and starts a new project, but it sounds like you're on that.

**Comment by nclairesays** [comment]
@KPHowley roger that. Yes, I already fixed it on my end. Will remove it for the next PR.
