### ISSUE TITLE
Equity Adjustments

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#656]
Change maximum amounts of points for certain strategies if the project fulfills equity obligations. Most changes are to grant additional TDM points on top of existing maximum point values if developer allows the general public to use the amenity instead of just the people living/working at the finished project site.

Adjust the following strategies' point values as indicated:

Bicycle Facilities 5: Changing and Shower Facilities  - **5 Max Points** 
N/A - 0 points
Private = 2 points
Publicly Accessible = 4 points
Publicly Accessible AND in a disadvantaged area = 5 points

Car Sharing 1: Car Share Parking - **4 Max Points**
N/A - 0 points
Private = 3 points
Publicly Accessible =  4 points 

Information 1: Transit Displays - **3 Max Points**
N/A - 0 points
Internally visible = 2 points
Publically visible = 3 points

Transit Access 1: Neighborhood Shuttles/Microtransit Service - **9 Max Points** 
N/A - 0 points
Does not connect to HQTA = 3 
Does not connect and if publicly available = 6 (+3)
Does not connect and if publicly available and in disadvantaged area = 7 (+4)
Connects to HQTA = 5
Connects to HQTA and if publicly available = 8 (+3)
Connects to HQTA and if publicly available and in disadvantaged area = 9 (+4)

@KPHowley @Dsomers74

**Comment by Dsomers74** [comment]
@KPHowley I updated the issue based on your questions.

**Comment by entrotech** [comment]
![image](https://user-images.githubusercontent.com/9939032/101413023-6d028c00-3898-11eb-805f-b7db1c4079af.png)

**Comment by Dsomers74** [comment]
@entrotech Overall, it works, though the **Transit Access 1** points need further adjustment. I realize I didn't articulate the points well in my instructions. I put the delta point differential from the base in the parenthesis in order to provide if the option if there were a check box for either 'publicly available' or 'publicly available and in disadvantaged area' (e.g. 8 (5 + 3))

Revise the following strategies' point values as indicated:

**Transit Access 1**: Neighborhood Shuttles/Microtransit Service - **3-9 Possible Points**
N/A - 0 points
Does not connect to HQTA = 3
Does not connect and if publicly available = 6 (3+3)
Does not connect and if publicly available and in disadvantaged area = 7 (3+4)
Connects to HQTA = 5
Connects to HQTA and if publicly available = 8 (5+3)
Connects to HQTA and if publicly available and in disadvantaged area = 9 (5+4)

**Comment by Dsomers74** [comment]
Looks great John. Though the Transit Access 1 points need further
adjustment. I realize I didn't articulate the points well in my
instructions. I put the delta point differential from the base in the
parenthesis in order to provide if the option if there were a check box for
either 'publicly available' or 'publicly available and in disadvantaged
area'

For example, publicly available would be 3 additional points for a total 6
points (3 + 3) if the service does not connect to HQTA and 8 points if it
does (5 + 3). The parentheses were only internal references. Sorry for the
confusion.

I provided revised in the issue comment as follows:

Transit Access 1: Neighborhood Shuttles/Microtransit Service - 3-9 Possible
Points
N/A - 0 points
Does not connect to HQTA = 3
Does not connect and if publicly available = 6
Does not connect and if publicly available and in disadvantaged area = 7
Connects to HQTA = 5
Connects to HQTA and if publicly available = 8
Connects to HQTA and if publicly available and in disadvantaged area = 9

**Comment by entrotech** [comment]
@Dsomers74 Got it. I re-deployed to the tdmdev site. Can you verify that it is correct now?

**Comment by Dsomers74** [comment]
Yep! Thanks.
