### ISSUE TITLE
Fix Feedback Page jest tests

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#670]
Fix breaking Public Comment jest tests so that tests can run in CI pipeline

- [x] Rename all code and db objects from Public Comment to Feedback, including the client-side routing path to /feedback
- [x] rename and move postPublicComment.js to /src/services/feedback-service.js
- [x] rename PublicCommentPage.js to FeeddbackPage.js
- [x] remove postPublicComment.test.js - I don't think the test has value.
- [x] rename PublicCommentPage.test.js to FeedbackPage.test.js 
- [x] debug FeedbackPage.test.js to get tests working.

**Comment by nclairesays** [comment]
Working to hopefully have this done by next meeting

**Comment by nclairesays** [comment]
Spent some time trying to fix the frontend tests but am unable to get it to pass properly even though I am using patterns I know "should" work. I think that the errors are due to library version compatibility but have not validated this. 

Next person who picks up this issue, look into versions for the following libraries: jest, react, react-dom, react-testing-library, and maybe nock if we want to use nock.  There are ways to test api calls without using nock.

**Comment by fyliu** [comment]
I wasn't able to spend much time on this. I will do more this week.

I'm able to run the simplest nock+axios test https://www.npmjs.com/package/nock#axios
I'm thinking of using the nock recorder feature to figure out if our expected request is correct.

**Comment by fyliu** [comment]
@nclairesays I only fixed the existing tests in the file.
It can be possibly expanded to record the real responses to the requests and then testing against them.

I also read that msw mocks works for both the server and client at the same time, so that might be worth looking into just to save developer time. https://github.com/mswjs/msw

**Comment by fyliu** [comment]
@nclairesays I might just leave this alone for now. I tried a while ago to test something with that toast provider context and wasn't able get it working.

**Comment by mojimoh** [comment]
Have a discussion with John and Bonnie about the value of continuing this work so that we can prioritize this issue.

**Comment by mojimoh** [comment]
Need to have a discussion with the stakeholder about the website intent post launch

**Comment by jahpe777** [comment]
I fixed the tests having to do with updating to React 18 (RuleInput.test.js) but the tests for tdm-engine.test.js need to be updated. I'm switching to issue #780 for now.

**Comment by jahpe777** [comment]
Created a PR for @entrotech so that he can carry out the tests regarding the TDM engine and keep the updates I made regarding the tests having to do with updating to React 18.

**Comment by Biuwa** [comment]
Please provide an update:

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on.

**Comment by ExperimentsInHonesty** [comment]
- Closed pr #1361 with this note " This issue is being closed.  This pr was a way for John to see the branch, which has been done."

**Comment by entrotech** [comment]
@ZekeAranyLucas @agosmou Since you guys seem to be getting into jest testing, I thought I'd have  go at trying to fix this long-standing issue.  Everything that used to be called Public Comment is changed to Feedback - since the Public Comment period was last year, and we are re-purposing the page for general feedback on the site.

I got the first test in FeedbackPage.test.js working, and spent a bit of time trying to get the second test working, but didn't get very far.  It seems to be a problem with mocking all the dependencies of <FeeebackPage> for the test properly and/or possibly implementing some sort of wait for the async post to be completed to verfiy that the post is called.

It's not clear to me if the feedback.service.test.js test have any value, so I didn't try very hard to get them working.  I'd be interested in your opinions.

I thought this might be an issue that one of you could figure out.  I'm merging the issue to the develop branch, since it is a step forward, and doesn't break anything that was previously working.

**Comment by entrotech** [comment]
Per @ZekeAranyLucas , the Feedback page tests were unreliable, and preventing us from developing a suite of reliable unit tests.
