### ISSUE TITLE
Refactor: Tool tips

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#671]
### Overview

Some of the tool tips are different on the page, we should refactor them to be consistent.

**Comment by Jonathanko52** [comment]
Covered in #407, with pull request https://github.com/hackforla/tdm-calculator/pull/681

**Comment by Jonathanko52** [comment]
-Standardize sidebar and calculator strategies tooltips.
-Both move with mouse.
-Both have arrows.
-Darker blue test (same as current sidebar.)
-Border(same as strategies)
-Background white(same as strategies)

**Comment by Jonathanko52** [comment]
Narrowed down that the sidebar uses tooltip.js(from the sidebar field) while the wizard uses react tooltips npm package. Should be a simple fix from here. Eta 1/7

**Comment by Jonathanko52** [comment]
Pull request submitted

**Comment by Jonathanko52** [comment]
Pull request submitted. Awaiting review.

**Comment by nclairesays** [comment]
I approving JK's PR but this issue isn't closed yet. I'll work to continue refactoring this. 

There are some files that could be deleted, some styling that's passed into a component when the component should already be responsible for its own styling. There's a lot of repetitive code in these tool tips so I will work to refactor and clean them up.

**Comment by nclairesays** [comment]
Still need to fix the tool tip that explains the packages when you're on level 1. The ProjectsPackages.js uses the old tool t ip
![image](https://user-images.githubusercontent.com/45305029/105144329-ec979380-5ab1-11eb-859a-7a2a3f2184a2.png)

**Comment by nclairesays** [comment]
I did some additional refactoring on top of what JK already did (which has already been approved and merged in)

Mostly reorganizing files/components so that they are DRY
- Created a Tooltip directory with ToolTipIcon.js and ToolTip.js. (This ToolTip.js is _different_ from our previous versions of ToolTip.js) 
- These are the components we should be importing throughout the app, rather than importing directly from the library. 
- These two components are responsible for their own styling. Styling does _not_ get passed into the component anymore.
- Made all ToolTipIcons the same, with the option of making it a "medium" size via a prop

Bug FIx: Fixed the rendering of tooltip icon for Parking Provided / Baseline and City wide Parking baseline since the icon accidentally got added in
