### ISSUE TITLE
Phase 2: Develop login front-end component

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#71]
Backend login routes have been created via issue #48 . 

Login form to be created. send email/password to backend which will receive jwt token and be stored into local storage.
-------------
This will be a fairly typical SPA user registration and login.  Adding roles, etc. will be a separate issue.

- [x] Back-End Web API implementation
- [x] Front-End functionality
- [x] Front-End User Notifications to replace console.log
- [x] Cosmetic clean-up

**Comment by entrotech** [comment]
I expect to implement Login/Logout and Forgot Password features similar to what we have in Food Oasis and demonstrated in this video:

https://www.loom.com/share/3de25f3c92e84d2b927a1e87cc76f6a7

**Comment by entrotech** [comment]
Also added a GitHub markdown page describing in detail how the registration/login features are intended to work: https://github.com/hackforla/tdm-calculator/blob/master/register.md

**Comment by entrotech** [comment]
I believe this is working, though it needs to be thoroughly tested per the register.md process description, including all the "unhappy paths". In the Login.js component and ConfirmEmail.js component, I put a TODO comment where we need to add user notifications (see Issue #123), to let the user know what happened and/or what to do next. I'll let somebody else pick up this issue and complete it :)

Of course, the appearance and styling also needs work!

**Comment by ExperimentsInHonesty** [comment]
@nclairesays currently the live registration page doesn't look like the figma registration page

![Screen Shot 2020-01-02 at 2 09 36 PM](https://user-images.githubusercontent.com/37763229/71696325-8edebf00-2d69-11ea-9236-f8d05be7261a.png)

![Screen Shot 2020-01-02 at 2 08 39 PM](https://user-images.githubusercontent.com/37763229/71696268-6bb40f80-2d69-11ea-8c0f-73fd732fb760.png)

Can you change the live version to match?

**Comment by ExperimentsInHonesty** [comment]
@nclairesays currently the live login  page doesn't look like the figma registration login page

![Screen Shot 2020-01-02 at 2 13 48 PM](https://user-images.githubusercontent.com/37763229/71696574-365bf180-2d6a-11ea-8a56-4a1f2ffd7838.png)

![Screen Shot 2020-01-02 at 2 16 07 PM](https://user-images.githubusercontent.com/37763229/71696690-79b66000-2d6a-11ea-9b1c-4e140eca3d64.png)

Can you change the live version to match Nicole's Figma?

**Comment by nclairesays** [comment]
@ExperimentsInHonesty sure i can try to finish it tonight

**Comment by ExperimentsInHonesty** [comment]
@nclairesays what is the status of password recovery and any other functionality to do with the login besides the actual saving (which john is working on)?

**Comment by ExperimentsInHonesty** [comment]
@nclairesays and @ExperimentsInHonesty reviewed current  - here are the notes: 

@mmorgs 
- [ ] fix css so that it reflects the fonts and styling and remove inline styles. Note: some of the pages have inline align center styling to differentiate them from the calculator pages.
- [ ] update the language to reflect the words chosen in the figma file.  Except Full name is First Name and Last name.
- [ ] remove rounded corners 

@nclairesays 
- [ ] make toast appear horizontally centered above content
- [ ] once login is achieved reroute to /calculations
- [ ] add "continue without saving" button to the /login page, with warning message on hover.  the page redirects to /calculation
- [ ] work with John on password recovery (optional if time allows)
   - [ ] add in password recovery page (place for them to put new password, and password confirmation fields.  Once completed, it takes them back to the /login).

@nekobox 
- [ ] please clarify  - unclear what is supposed to happen with the red msg for them choosing not to log in.  Does this happen on hover or when you click and then you have to click again?  And then when does the Login button turn green as depicted in A2-Login-No Save Warning
- [ ] please create password reset screen.  The current path is you click "send recovery email" on the A2-Login-Reset-Password then it will send an email to the person, with a link to reset.  They need to be delivered via that link to a page that has a place for them to put new password, and password confirmation fields.

@entrotech in the figma (A2 Login)  there is a "keep me signed in" check box under the login.  Are we doing anything with this?

**Comment by ExperimentsInHonesty** [comment]
@nclairesays @nekobox - After talking with John, we are going to drop the “keep me signed box “ box for now.

**Comment by nclairesays** [comment]
@mmorgs, I went ahead and updated the language to match figma with the above pull request (#156) and also tried to do some reorganization of the scss files because there were some duplicates/inconsistencies with what I was trying to do. After this pr gets merged into master, please feel free to update/edit the scss files as you see fit! There's a lot of cleaning up to do with the styles. Thanks ahead of time! :)

**Comment by nclairesays** [comment]
@bfojas if you're available and up for it, feel free to work on any of the unchecked items under my name. I won't be free until after 7/8pm to work on any of this.

**Comment by ExperimentsInHonesty** [comment]
I pushed @nclairesays latest PR.  Here is my review of the current state (we are getting close)
Bonnie's Review as of 11:00am pacific 2020-01-06

Who is going to take this on?

- [ ] @nclairesays (busy until 7pm Monday night)
- [ ] @mmorgs
- [ ] @bfojas 
    - [ ] The warning messages on the create new account (/register) need to be red.  They are currently blue:
        - [ ] First Name is required
        - [ ] Last Name is required
        - [ ] Invalid email address format
        - [ ] Password does not match
        - [ ] Password must be 8 characters at minimum

And all the open issues from the comment [above](https://github.com/hackforla/tdm-calculator/issues/71#issuecomment-570968495):

note moving css cleanup to another issue since its not just the login where we need it.

@nclairesays
- [ ] make incorrect password toast appear horizontally centered above content. Ideally this wouldn't be modal at all, just a red warning underneath the password field.

@nekobox
- [ ]  please clarify - unclear what is supposed to happen with the red msg for them choosing not to log in. Does this happen on hover or when you click and then you have to click again? And then when does the Login button turn green as depicted in A2-Login-No Save Warning
- [ ]  please create password reset screen. The current path is you click "send recovery email" on the A2-Login-Reset-Password then it will send an email to the person, with a link to reset. They need to be delivered via that link to a page that has a place for them to put new password, and password confirmation fields.

**Comment by ExperimentsInHonesty** [comment]
@nekobox says
Q: please clarify - unclear what is supposed to happen with the red msg for them choosing not to log in. Does this happen on hover or when you click and then you have to click again? And then when does the Login button turn green as depicted in A2-Login-No Save Warning
**A: On hover**

Who is going to take this on?
- [ ]  @nclairesays 
- [ ]  @mmorgs
- [ ]  @bfojas
 Please mark you acceptance of the task by clicking the check mark and then add your eta and any details as a comment below.

**Comment by nclairesays** [comment]
I implemented it in hover already. So the green button login isn’t
necessary anymore, correct?

**Comment by KPHowley** [comment]
![Screen Shot 2020-01-11 at 1 23 26 PM](https://user-images.githubusercontent.com/49739276/72210790-9db62780-3475-11ea-9335-63236d718986.png)
I just noticed this potential bug: This is how the buttons are coming up on for me when I use Firefox, but not when I use chrome....

**Comment by bfojas** [comment]
@KPHowley I should have a PR fixing this shortly. Looks like if a height isn't provided, chrome defaults to auto (which is what we wanted), but firefox doesn't default to auto and I actually have no idea where it pulls the height from. I added height: auto to the CSS for this.
