### ISSUE TITLE
Create FAQ Admin features

### ISSUE THREAD

**Issue by nicholaspung** [hackforla/tdm-calculator#76]
**Dependency:**
 - [x] #42 - we have enough feedback from this issue to remove it as a dependency.  The only remaining item is the view all answers button.  Which should not hold the admin interface issue up.

### Overview:
We need an admin interface for the FAQ, so that LADOT/LACP and HfLA can add Q&As for how to use the calculator or where to find official TDM info.

### Requirements
- Display current FAQs with edit/delete functionality
- Have a create FAQ functionality
- Should fit with the design system

**Comment by entrotech** [comment]
The middle-tier and back-end stored procedures for this are working, and there is a route for this page at /faqs, but the UI is not presentable at this time, so we are not showing links in the UI to get to the page.

**Comment by ExperimentsInHonesty** [comment]
This is a current functionality: https://tdm-calc-staging.herokuapp.com/faqs. What additional features do you want?

Issue #42 is setup to ask stakeholder.

**Comment by dazainus** [comment]
@JRAlexander72 - can design the visuals for the FAQ pages.

### Overview
The link Bonnie shared (http://tdm-calc-staging.herokuapp.com/faqs) is the FAQ page that engineers created back-end. It is an admin page where FAQ questions can be added, updated, and deleted. This information needs to be shown in our website as a FAQ page (not built yet).

We don’t want to necessarily come up with the questionnaires and answers since LADOT is most likely to be deliver them. But, you may take some of the questions from the website as placeholders for now.

### Action Items
- [ ] Design wireframe & high-fi mockup for FAQ page so our front-end engineers can start building it.
- [ ] Design wireframe & high-fi mockup for the FAQ admin page, making it more legible & systematic.

### Resources
@JRAlexander72 - Please share the link to Figma file for the front-end developers.

**Comment by dreams0ng** [comment]
CHANGES

- [X] Design wireframe & high-fi mockup for FAQ page so our front-end engineers can start building it.
- [X] Design wireframe & high-fi mockup for the FAQ admin page, making it more legible & systematic.

MOCKUPS
Basic Overview
![Screen Shot 2020-07-27 at 10 27 48 PM](https://user-images.githubusercontent.com/22779768/88622854-81b45500-d058-11ea-8564-93461cc29080.png)

Add New FAQ
![Screen Shot 2020-07-27 at 10 28 13 PM](https://user-images.githubusercontent.com/22779768/88622881-8f69da80-d058-11ea-89f7-d03441477996.png)

Update Existing FAQ
![Screen Shot 2020-07-27 at 10 27 57 PM](https://user-images.githubusercontent.com/22779768/88622921-9db7f680-d058-11ea-83fa-99f292065b91.png)

Delete Existing FAQ
![Screen Shot 2020-07-27 at 10 28 07 PM](https://user-images.githubusercontent.com/22779768/88622934-a6103180-d058-11ea-90dc-fcc6e2198d26.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=2190%3A11368

**Comment by dreams0ng** [comment]
CHANGES
1. Changed color of "Update" & "Delete" buttons
2. Visualized how title would be updated in "Update" feature
3. Visualized delete modal box for "Delete" button once clicked
4. Visualize login options for Admin page

MOCKUPS
1 & 2
![Screen Shot 2020-07-30 at 12 05 35 PM](https://user-images.githubusercontent.com/22779768/88964339-1f2ca600-d25e-11ea-85dc-33b758c680b6.png)

3
![Screen Shot 2020-07-30 at 12 05 18 PM](https://user-images.githubusercontent.com/22779768/88964356-2358c380-d25e-11ea-88be-f9f752c27e0a.png)

4a
![Screen Shot 2020-07-30 at 12 09 23 PM](https://user-images.githubusercontent.com/22779768/88964373-28b60e00-d25e-11ea-9b31-7aabe72da027.png)
4b
![Screen Shot 2020-07-30 at 12 09 47 PM](https://user-images.githubusercontent.com/22779768/88964384-2b186800-d25e-11ea-934d-a9afebccd18e.png)

LINKS
https://www.figma.com/file/6h72XLxK76m4INtsSu8Mt0/TDM-Calculator-Copy?node-id=0%3A1

**Comment by dreams0ng** [comment]
CHANGES
+Corrected delete modal on FAQ admin page
+fixed font family / sizes

MOCKUPS
![giphy-2](https://user-images.githubusercontent.com/22779768/90553925-02dba500-e14a-11ea-9dcd-9aed1318c921.gif)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by dreams0ng** [comment]
CHANGES
+replaced design for customer facing faq page
+integrated pre-existing delete icon

MOCKUPS
![adminfaq](https://user-images.githubusercontent.com/22779768/91371581-41b2d000-e7c6-11ea-9ab8-fa0e5813f949.gif)


LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/

**Comment by dreams0ng** [comment]
CHANGES
+decreased line width between sections

MOCKUPS
![Screen Shot 2020-09-02 at 12 38 35 PM](https://user-images.githubusercontent.com/22779768/92028684-4ec94500-ed19-11ea-9251-62acb56178a1.png)

LINKS
https://xd.adobe.com/view/f32a7d21-a346-43a1-6e66-809bd1399976-851b/?fullscreen&hints=off

**Comment by KPHowley** [comment]
Design for this and back end has been created, but this did not fit in with LADOT's desire to link to FAQ's on their website.

This functionality may be useful for a further revision.

**Comment by lexycatipon98** [comment]
CHANGES: 

- Added rearrange questions feature for Admin Mode, proposed drag and drop function with green highlight on the question being moved, proposed dotted lines to box questions in Admin Mode rather than the separating lines in the regular view
- Added icons to questions for edit and delete questions functionalities
- Added "+ Add new question" button for adding new FAQ functionality

MOCKUPS:
<img width="1105" alt="Screen Shot 2022-08-31 at 8 53 29 PM" src="https://user-images.githubusercontent.com/107448816/187828403-3444dac0-78da-47c8-90b9-05543a14bffd.png">
<img width="1103" alt="Screen Shot 2022-08-31 at 8 53 40 PM" src="https://user-images.githubusercontent.com/107448816/187828385-b0f93fbb-f8bd-453c-96fa-eeaa56c81d42.png">
<img width="1103" alt="Screen Shot 2022-08-31 at 8 53 50 PM" src="https://user-images.githubusercontent.com/107448816/187828902-dcc564f1-6d3c-4060-9342-ba6ed94ec1cf.png">

FIGMA LINKS:

- Link to playable flow for the rearrange questions feature: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11982&node-id=6818%3A35067&viewport=571%2C-1353%2C0.21&scaling=scale-down&starting-point-node-id=6818%3A35067

- Link to edit and delte screen on Figma: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6788%3A30760

**Comment by Reneedesigns** [comment]
-Added edit screens from suggestions at 9/3 mtg.  
-Dash line placement on option 3 varies, please select preference

Screen Views in Figma
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6873%3A25085

![Option 2](https://user-images.githubusercontent.com/99779174/188508057-f0507b27-3711-4add-b1c9-89e51e920db9.png)


![Option 3a](https://user-images.githubusercontent.com/99779174/188508137-92717ee2-b7a6-40f6-a556-76355c4aa758.png)



![Option 3b](https://user-images.githubusercontent.com/99779174/188508145-d90762c7-383a-422d-bc19-82ced93a171c.png)


![Option 3c](https://user-images.githubusercontent.com/99779174/188508151-061130fc-e9a9-4e31-b4ea-cf34f49022a6.png)

@SMR9220 @Biuwa

**Comment by Biuwa** [comment]
Stakeholders went with this option:

![image](https://user-images.githubusercontent.com/98936028/188756587-50fa5e6d-32c3-4840-9c6b-e2120da041eb.png)

**Comment by ExperimentsInHonesty** [comment]
User test these with a larger group using [UsabilityHub | User Research & Usability Testing Platformhttps://usabilityhub.com](https://usabilityhub.com/)

**Comment by Biuwa** [comment]
John suggested a 2 line question should be prototyped so we can help determine

**Comment by Reneedesigns** [comment]
@Biuwa @SMR9220 

> John suggested a 2 line question be prototyped, to help determine the placement of the right-sided buttons Alexander preferred


Admin-icons left side
![2 question line-admin  1](https://user-images.githubusercontent.com/99779174/189801472-cfb4b394-7cbd-4979-ad82-ca04b0b2cae9.png)



Admin-icons right side
![2 question line admin 2](https://user-images.githubusercontent.com/99779174/189801547-9ecdc2a2-f305-4278-9da7-3665624c3b91.png)



User-facing collapsed questions
![2 question line user-facing 1](https://user-images.githubusercontent.com/99779174/189801730-dba716b9-1528-47b5-8c38-d33ba4e1ca9d.png)



User-facing expanded questions
![2 question line user-facing 2](https://user-images.githubusercontent.com/99779174/189801778-9eb9b2f6-a47d-46f8-9a7b-456396c390c9.png)

**Comment by Jane4925** [comment]
UX team will start testing on the week of 09/19/2022

**Comment by jarmitageux** [comment]
Progress: Testing completed 10/1/2022, analysis completed, report in progress
Blockers: none
Availability: team will review report this week
ETA: report draft ready for leads meeting Oct. 15th

**Comment by Reneedesigns** [comment]
Features needed per testing @jarmitageux @Jane4925

- Categories (currently 5)
- Move questions around quickly at once (currently have "dots" icon in place)
- Clear indicator of Save/Edit mode
- Edit abilities for all areas (categories, questions, and answers)

**Comment by Reneedesigns** [comment]
Per 10/26 team meeting discussion, implement TDM FAQ Draft questions into the current FAQ screens

**Comment by entrotech** [comment]
For the question deletion warning dialog, it could be designed like the one for deleting projects:

![image](https://user-images.githubusercontent.com/9939032/199639137-e464b9fe-c760-4d18-8b4f-196d63a73c77.png)

**Comment by jarmitageux** [comment]
Jamie sketched out 2 FAQ admin design options and created these narrative videos explaining them.

https://user-images.githubusercontent.com/92768513/199647943-a5980614-904f-4615-8181-a9eaf993f048.mov


https://user-images.githubusercontent.com/92768513/199648038-34850fe4-998a-4aa5-8626-f8880d284f8f.mov

**Comment by jamiedesignedit** [comment]
Admin-facing FAQ page built off of Renee's design for the user-facing FAQ page w/ categories.

**Updates:**

- Keeping grippy dots because feedback was that they wanted to be able to move questions around quickly
- Made grippy dots darker grey because of accessibility, lighter grey wasn't contrasted enough on white background
- Added "edit section" and "save edits" button at top left that brings you in and out of edit mode
- Made the "answer" body text smaller, 18px (standard desktop body font size is 16-18px and I think it should be smaller than the headings)
- Hover feature to only make edit and trash icons appear when user hovers over a section to reduce visual clutter
- Slightly changed the "add question" button so it looks differentiated from the "save edits" button

Figma link showing full flow: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7195%3A26328

<img width="616" alt="Screen Shot 2022-11-08 at 3 05 11 PM" src="https://user-images.githubusercontent.com/114036754/200695224-8f0be063-14d9-48d7-aacf-092606987f01.png">

<img width="617" alt="Screen Shot 2022-11-08 at 3 05 20 PM" src="https://user-images.githubusercontent.com/114036754/200695187-111c0cfb-1b8f-4d13-b82e-8647f3121be4.png">

<img width="617" alt="Screen Shot 2022-11-08 at 3 05 29 PM" src="https://user-images.githubusercontent.com/114036754/200695247-11d8423d-a6ad-4d8d-bc3e-a471ac652848.png">

**Comment by entrotech** [comment]
@Reneedesigns @jahpe777 @jarmitageux   We can probably implement the flow that @jamiedesignedit proposes. Some questions:

1. Would it be awkward and confusing for users that they sort of have to switch the whole form into edit mode and then choose to edit a question/answer in order to change anything, and even more unintuitive that they have to click the "Done" link AND the Save Edits button to get anything to be saved permanently?  If I were a user, I would expect that clicking on Done would save my changes.  I'm guessing that clicking on the Done link just collapses the Question without saving anything, so it does the same thing as clicking on the minus sign. If so, we may not need the Done link, and users might be somewhat more aware that they need to press the Save Edits button to save their changes.
2. If you want to change the name or delete a category, would you also have the floating toolbar on the category row to allow you to do so?
3. Would the Add Question link also allow you to add a new category?  if so, the enbedded new Question/Category "form" would need a control that allows you to specify if you want to add a new Question or Category, and then show question and answer entry fields if you are entering a question, or just a name field if you are entering a category.
4. If a new question or category is added, where does it show up in the list?  Is it at the top, so you would need to add it and click the "Done" link, then drag it to the place you want it in the sort order?
5. If you choose to delete a category, what happens to the questions in that category? Are they deleted, or maybe "float" up to the next category above the deleted category, and if so, what happens if you delete the first category?
6. In the last wireframe where you show a question being edited, it might be good to have Q and A labels on the text boxes for clarity.
7. Dashed lines as borders around each question are sort of odd and don't match with any other places in the application where we have lists. What is the thinking about the borders?  The (user-facing) FAQ page looks like [this](https://tdmdev.azurewebsites.net/faqs) now, with simple horizontal lines between questions.  Maybe the dashed lines are supposed to emphasize that you are in edit mode?

**Comment by IMHieuVo** [comment]
I have updated mockups of the Warning Box per our 11/2 meeting (Jon noted that there is an existing Warning Box we could match).

Mockup A - Match. Match the existing warning box and the background fade as closely as possible while retaining the new language.

Mockup B - Dark Fade. Match the warning box but have the background be a darker fade.

Mockup C - New Style. Match elements of the warning boxes but have the look and feel of the newer style.

Mockup A - Match
![FAQ Screen Delete Warning Mockup - A - Match](https://user-images.githubusercontent.com/117132709/200762553-e60317c1-7f23-46e5-8ff6-eac8420559f6.png)

Mockup B - Dark Fade
![FAQ Screen Delete Warning Mockup - B- Dark Fade](https://user-images.githubusercontent.com/117132709/200762584-7c965edf-6e73-4dcc-b3ca-24c43fd9387d.png)

Mockup C - New Style
![FAQ Screen Delete Warning Mockup - C - New Style](https://user-images.githubusercontent.com/117132709/200762600-5e51ade8-0179-4cfc-93ad-03be3e521bb4.png)

**Comment by SMR9220** [comment]
Team has selected Mockup C as the preferred style.

**Comment by jamiedesignedit** [comment]
Hi all, posting admin-facing FAQ page with updates per out 11/9 meeting discussion.  Please let me know if this is comprehensive enough and if updates are what we wanted:

**Updates:**

- Move "add question" option to be within each category at the bottom
- Create "add category" CTA at top left to add a new category
- Clarify how text can be edited by double clicking into it
- Clarify how questions and categories can be re-ordered by dragging grippy dots

**Figma link to see all screens:** https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7262%3A25039&t=hGP6h8UMFREhbFn1-1

**Video quick walkthrough:** 

https://user-images.githubusercontent.com/114036754/201434737-fb63289f-c4cd-49dc-9e5b-6749c2aa4639.mov

**Comment by Reneedesigns** [comment]
@jamiedesignedit 
Is there a screen to show the edit/deletion of an answer to the questions? In the meeting on 11/9 the team discussed expanding questions to show the answers in edit mode. Do we want this to be the same process as editing a question?

Another addition to the FAQ Admin screen will be a "Warning" box should the Admin start to leave the screen without saving. This box will be designed based off of the design from https://github.com/hackforla/tdm-calculator/issues/76#issuecomment-1308311019 once iterations are completed.

**Comment by ExperimentsInHonesty** [comment]
1. Please list out all the features
   1. Edit Q&A Button
   1. Move whole section
   1. Move single Q&A
   2. Edit Q&A
   3. Edit Section Title
   4. Add a Q&A
1. Please make separate recordings for each feature.  It's hard to show the features to the stakeholder with it the way it is.  Because you have to keep pausing to discuss a specific feature.

**Comment by IMHieuVo** [comment]
@Biuwa @SMR9220 

Per the 11/9 meeting, the team has chosen Mockup C (Centered Text warning box with dark fade background). The latest iteration includes:

- Quoting the text of the question/answer that the user is deleting in the warning box.
- To avoid accidental deletion, move focus to/highlight the "cancel" option
- Includes a Leaving-the-page warning box

Link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7299%3A25362&t=0ztwOC3PNJ8aFPGN-1

Question Warning Box
![FAQ Question Warning Box - Option 2A (Dark Fade, Color Focus)](https://user-images.githubusercontent.com/117132709/201815385-bf6b93b6-b1c1-477e-be46-54133cccfa22.png)

Leaving Warning Box
![FAQ Leaving Warning Box - Option 2A (Dark Fade, Color Focus)](https://user-images.githubusercontent.com/117132709/201815454-df45161b-56db-4881-81d2-8a33e8f4ba84.png)

**Comment by jamiedesignedit** [comment]
Updates after Bonnie's last comment, including screens of **editing an answer** and making sure **not to delete the entire question when editing**.  Videos are included below each feature listed.  Link to Figma to look at all the two flows that have been iterated on from the last version: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7348%3A25328&t=o0WEWPpKLmhafQZp-1

1. Go into edit mode

https://user-images.githubusercontent.com/114036754/202098025-efe4b2df-0f24-48f8-94f8-86de377656b0.mov


2. Delete a question

https://user-images.githubusercontent.com/114036754/202098051-4360662c-ce5e-43da-99cf-cc69e10bde90.mov


3. Edit a question (iterated on since last post)

https://user-images.githubusercontent.com/114036754/202098076-f935a08b-573a-4c49-99b5-a6384502b32d.mov


4. Edit an answer (iterated on since last post)

https://user-images.githubusercontent.com/114036754/202098098-71bc0f5a-190d-4770-a60e-569dd5db7cb9.mov

5. Move a question & move a category

https://user-images.githubusercontent.com/114036754/202098142-684722d1-220a-45a5-9f15-e416108c8e40.mov


6. Add a new category


https://user-images.githubusercontent.com/114036754/202098252-578881ae-89c9-4a0c-b5ae-39576cfa2bec.mov

**Comment by IMHieuVo** [comment]
Below is the update of the warning boxes per accessibility considerations. The red text on the white background does not seem to pass the color contrast checker for accessibility so I opted to make the text black.

Option A) Uses the main red color as an outline
Option B) Uses bold white text on a dark red background.

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=7419%3A25419&t=79Ho5XdabKSIQwbM-1 

FAQ Question Warning Box, Option 1A - red outline
![FAQ Question Warning Box - Option 1A (Red Highlight)](https://user-images.githubusercontent.com/117132709/202841014-fbfd5d9f-6144-44e7-a4e2-5ea147372a23.png)

FAQ Question Warning Box, Option 1B - Red background
![FAQ Question Warning Box - Option 1B (Red BG)](https://user-images.githubusercontent.com/117132709/202841050-1e4c643f-57fc-4a3f-9056-ed58fdb4be12.png)

FAQ Leaving Warning Box, Option 2A - Red outline
![FAQ Leaving Warning Box - Option 2A (Red Highlight)](https://user-images.githubusercontent.com/117132709/202841071-57ce3926-cd00-47be-86f1-dc3b5aedd43f.png)

FAQ Leaving Warning Box, Option 2B - Red background
![FAQ Leaving Warning Box - Option 2B (Red BG)](https://user-images.githubusercontent.com/117132709/202841091-ccdf0c72-33f5-4d03-bfee-33e18cf7095e.png)

**Comment by ExperimentsInHonesty** [comment]
@IMHieuVo In the above post, you have several different warning messages, but two different color reds.  Please explain why two different reds (the orange red and the more brown red).

**Comment by IMHieuVo** [comment]
@ExperimentsInHonesty 
Short answer: Accessibility.
Long answer: The orange-red color is one of the 'core' colors of the site but it is a terrible color to use with white/gray in terms of accessibility. It fails both versions: white text on orange-red background and orange-red text on white background. In option A, we can still use the orange-red color because it is not directly interacting with the text. In option B, I had to go with a darker red color to pass the accessibility contrast.

![image](https://user-images.githubusercontent.com/117132709/202873292-f563f215-22fc-4973-9277-f8e12d8b4a9d.png)

**Comment by Biuwa** [comment]
Discussions about the warning dialogue box have been moved to #1279 and will continue there

**Comment by entrotech** [comment]
@Biuwa The editor seems to functioning pretty well, but there are a few remaining kinks to be worked out that cause some of the answers to be rendered incorrectly.  It's your call about whether we show this to the stakeholders tomorrow, or wait til these can be resolved.

@shanesween Here are the problems I found when testing the FAQ Admin feature in the development environment after merging

There are a few problems with the version in the above PR:
**Problem #1: Broken links:**
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/ec4fbd64-2651-4f0b-8935-2f259ca8b515)
 (This should open the checklist modal dialog)

![image](https://github.com/hackforla/tdm-calculator/assets/9939032/33d8dfcf-aaa3-478a-a030-6076af3429ba)
(Should open the corresponding document, as it does now in production)

Need to check all of the links in answers - I think most of the broken links are because the target and/or rel attribute settings were not accurately carried over from the previous version.

**Problem #2:** Several answers are rendered incorrectly, showing raw HTML instead of rendering the HTML properly, for example:
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/c9bb511f-b852-4261-9f2e-9a8f529c4c6c)


and

![image](https://github.com/hackforla/tdm-calculator/assets/9939032/aa07929a-3af4-4b9e-866b-70bbdbae3ef9)

and

![image](https://github.com/hackforla/tdm-calculator/assets/9939032/48d12995-8377-4f04-b007-c1bdf952190f)

These appear to be problems with missing or extra quotation marks around the HTML text.

Problem #3: If you are not in edit mode (or not logged in), the bold text in answers is not rendered as bold.
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/994c3215-7f2e-49cb-b08a-ec0379b20195)

This appears to be a styling problem with rendering non-editable answers using a font-weight of "bold" and font-family of "Calibri" for the answer paragraph, and using a font-family of "Calibri Bold" and font-weight of 400 (i.e. normal) for the <strong> style in App.scss, and the two combinations render text in an indistinguishable style. The easiest immediate fix is to change the styling of the answer paragraph to be font-weight: 400 (i.e., normal) and font-family: "Calibri". IMO, we should replace  "Calibri Bold" font family throughout the app with "Calibri" and use the font-weight property to control font-weight.  The other option is to use "Calibri" for normal text and "Calibri Bold" for bold text, but leave the font-weight as "normal" everywhere.

**Comment by entrotech** [comment]
@shanesween Problem #3 mentioned above is resolved. When not in edit mode, one of the divs enclosing the answer had font-family set to "Calibri Bold", which is apparently the same as font-family "Calibri" with a font-weight of bold (or 700), so applying the <strong> tag to text had no effect on the rendered text.

  I went through the whole app and changed all "Calibri Bold" styles to "Calibri" with a font-weight of "bold". The above-mentioned div is set to font-family "Calibri" and font-weight: regular, so answer text that is not styled will now show up as regular weight. When quill applies the <strong> tag, the font-weight: bold (set in App.scss) will be applied, so the text bolded in quill will appear as bolded.

**Comment by Biuwa** [comment]
- the links will be QA tracked by #1456
