### ISSUE TITLE
Add ? icon to habitable rooms  lines on Calculation/2 to designate tooltip. 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#836]
### Overview
People were unclear that tool tips were on this line, so we need to show an icon. 

### Action Items

- [x] add ? icon to Habitable to all three habitable rooms lines on Calculation/2. 

### Resources/Instructions

**Comment by jahpe777** [comment]
Added ? icon to Habitibal rooms lines on Calculation/2 to designate tooltip. #836

![Screen Shot 2021-06-13 at 12 53 52 PM](https://user-images.githubusercontent.com/40730303/121820244-a69cc100-cc46-11eb-9388-09811d986a4e.png)

**Comment by nclairesays** [comment]
@jahpe777 John and I were meeting so that he can show me the release process. We were going to use this issue as an example to be included in a small release, which is why we approved the PR. However,  the code needs to be improved. 

For the conditional logic, instead of using the `children`, it really should be using the `code`. When i tried to do a console log, I noticed it was undefined. I was actually about to tell you how to solve that, but this is a good example of how/where you could improve your knowledge of react and your code. I'll actually leave it at that see if you can debug on your own and make it work with the code prop. If you need help, lmk. 

Another thing to improve on: See if you can have it check only condition rather than using the `or` / `||` operator for those 3 rules.
