### ISSUE TITLE
Update for the TDM Summary Page

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#913]
We have a slightly new design for the Summary page after couple of cleanup along with LADOT.

- [ ] Confirm the Updated design from the figma file 
- [ ]  Update the Summary page for an authenticated user
- [ ] Update the summary page for a guest
- [ ] Update the page when the target points are achieved
- [ ] Update the page when the target points are not achieved

Resources:
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=2534%3A1 

Sample images:
![image](https://user-images.githubusercontent.com/20568596/130886583-88d6b584-b61c-4832-8980-1a21a4646a93.png)
![image](https://user-images.githubusercontent.com/20568596/130886616-addf09b3-d4ef-4476-ba3f-52847138bd62.png)

**Comment by fyliu** [comment]
WIP screenshot for discussion
![2021-09-01 15 19 16 localhost f75b85862936 annotated](https://user-images.githubusercontent.com/1160105/131756103-7c9cb9ef-8775-4f4a-9c49-fb113e499863.png)

**Comment by fyliu** [comment]
Documenting decisions from the meeting.
- fix the spacing issues, including centering earned points title for points column
- center target points achieved message line
- don't change last saved position
- don't change font size and weight for project details values
- no need to modify anything else since this issue is just rearranging positions in the page

**Comment by fyliu** [comment]
This shows how having different fonts affect the alignment. The baseline is at different heights in each box and centering them won't align them.
![2021-09-02 09 39 25 localhost bd45b599b240](https://user-images.githubusercontent.com/1160105/131885641-d40c8507-fca4-405a-b8cd-96bf0a7d127c.png)


Here are a few different things I tried

bottom align
![2021-09-02 10 06 13 localhost 5ec79a6e5b8d](https://user-images.githubusercontent.com/1160105/131887256-7b684351-2b63-4742-9bea-3fcf1f4f616f.png)


top align
![2021-09-02 10 05 54 localhost cc71a966eee8](https://user-images.githubusercontent.com/1160105/131887270-35258305-d184-4c98-ac2a-cb50ae0689bb.png)

baseline align
![2021-09-02 10 05 29 localhost 6924f47e507b](https://user-images.githubusercontent.com/1160105/131887456-0e53262c-457a-4a71-bee9-872c8ff7a95c.png)

I'm thinking baseline is the correct one.

**Comment by seenaiype** [comment]
[Figma file](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1744%3A3531), please refer to the Summary page Final Draft

-  Updated the color to match the style guide
-  Fixed the spacing of the Project Detail section

![image](https://user-images.githubusercontent.com/88021166/131802606-71e423c3-97db-4eed-b56a-1634fb8e2669.png)

**Comment by fyliu** [comment]
Progress screenshot
![2021-09-08 19 26 34 localhost 0d1cd64813da](https://user-images.githubusercontent.com/1160105/132612665-6fe09e77-ffb7-494d-be5b-ecba1e1b30b8.png)

**Comment by fyliu** [comment]
![2021-09-08 19 42 51 localhost d194180cb241](https://user-images.githubusercontent.com/1160105/132613677-4f6f9569-557e-426a-9654-2024cd1b4886.png)

**Comment by fyliu** [comment]
New updates
- [ ] check shade of gray for section headers
- [ ] target points reached message will be 2 lines
- [ ] bold text for project details points
- [ ] earned points title should be bold and larger
- [ ] green on white text might be unusable, need UX input on this first

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/132615445-6fd79621-33b6-4940-ad98-5f057f19af34.png)

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/132615597-e135f846-cc25-4f73-80fd-39198637f65b.png)

**Comment by fyliu** [comment]
I completed the changes requested yesterday. There are some differences from the Figma. Please tell me if there needs to be more changes.

For User-Defined strategy changes, please comment in issue #850 instead.

Screenshots
![2021-09-09 20 44 08 localhost 000fa51a832c](https://user-images.githubusercontent.com/1160105/132796511-039dc9a4-f8d2-41f4-b2a0-1196936b06da.png)
![2021-09-09 20 45 05 localhost 6f8dfb85a389](https://user-images.githubusercontent.com/1160105/132796504-540b065b-3354-456a-9aa3-32708fff0caa.png)

**Comment by seenaiype** [comment]
Looks good. Couple of things i noticed:

1. The title "Earned Points" seems too small on TDM strategies section.
2. The numbers in the project details looks bigger than the TDM earned points. IS that expected?
3. For "Enter Parking spaces req'd" and "Elementary/Middle...." rows, Instead of showing ...... Is it possible to just indent that row in couple of spaces?

**Comment by fyliu** [comment]
To answer:
1. Will check font size. I used the same size from the figma. Maybe the left title font is too large.

2. The difference is an illusion due to the numbers on the bottom being in the thousands. If you look at the 3 on both sections, they are the same size.

3. Yes, will do that. Is there an amount of spacing preference? I'll do 12px like the first indentation for now.

**Comment by fyliu** [comment]
Update:
1. Nevermind, the problem is that the project doesn't make use of Oswald font weight of 500, which is what medium is in figma. Font weights of 500, 700 still works better for the browser. Maybe see if there's a way to specify and use that in figma
2. I don't think change is needed based on previous comment.
3. I set it to 20px so it looks more like an indent than 12px. It can be another value if needed

Screenshot
![2021-09-10 10 50 54 localhost fcf37435f79a](https://user-images.githubusercontent.com/1160105/132896324-3647dd07-303c-4cdc-9bae-82082928ad1d.png)
