### ISSUE TITLE
Bug: Tooltip incorrectly displayed on Packages on the strategy seleciton page (calculation/5)

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#940]
### Overview

Currently there are tool tips displayed on the bonus packages on the strategies page. We should eliminate tool tips and not have them displayed here. 

### Action Items

- [x] Eliminate tool tip on bonus packages
- [x] Look into why this happened to prevent in the future (are tool tips automatically added when the tool tip field in the database is filled out?)

### Resources/Instructions
![Screen Shot 2021-09-18 at 11 17 34 AM](https://user-images.githubusercontent.com/49739276/133898569-6b81e0d4-c22c-4347-8959-5a9e35ab15b4.png)

**Comment by fyliu** [comment]
@KPHowley do you mean the icons or the actual tool tips as well? 

The tool tips are displayed when the field is filled out in the DB as far as I know. 

As for the icons, I made them hidden for the strategies page a while ago because someone(you?) told me to. Because every strategy has a tooltip so I guess there's no need to make the UI look more complicated.
