### ISSUE TITLE
Bug: Fix Email confirmation

### ISSUE THREAD

**Issue by jackrinjames** [hackforla/tdm-calculator#947]
### Overview
Fix when email is already confirmed, user should not need to confirm email again

### Action Items

- [x] Verify if bug exists, otherwise close issue

**Comment by entrotech** [comment]
This particular problem does not seem to exist anymore, but there is a problem when the user submits a new registration, the register page should show a message telling them to check their email for an email confirmation message, and this is not showing up.

We use a different SendGrid account in DEV, and this does not seem to be working at the moment.  I lost my phone and do not currently have access to Authy, which SendGrid uses for 2FA, so I am temporarily locked out of my personal SendGrid account.

**Comment by entrotech** [comment]
Actually, the problem did still exists, but there were other related bugs:
-  In the /server/.env file, we should have EMAIL_SENDER=tdm+sendgrid@hackforla.org, so that it matches what SendGrid expects. Since mine did not match, SendGrid was refusing to send the emails. This should not really have affected other devs of the production environment (which uses an LADOT Sendgrid account).
-  Moreover, when SendGrid failed, the failure was not reported back to the client, so, though the registration had succeeded in recording the new user email, the email had not been sent and the user could therefore not verify.
- On top of this, when I implemented server-side validation for the confirmPassword endpoint, I made an error requiring an "id" property, so any requests from the client to verify the password by a token on the confirmRegister page were failing, prompting the user to request another confirmation email, which put them in an endless loop of requesting the email, and the email verification not working.
- We had a problem where if you were on the login page, and clicked on the Register link, you would have to click on the link twice to get to the Register page, and likewise if you were on the Register page and clicked on the Login link, you would have to click twice to get to the Login page (same prob with the link on the Forgot Password page). This bug was apparently introduced when I implemented a change to set focus on the first element of each of  these pages, so I temporarily deleted this the auto-focus feature until we can figure that out.
